README.md
=> Replaced links on README.md from jpkrohling to open-telemetry

Makefile, deploy/crds/opentelemetry.io_opentelemetrycollectors_crd.yaml, pkg/apis/opentelemetry/v1alpha1/opentelemetrycollector_types.go, pkg/apis/opentelemetry/v1alpha1/zz_generated.openapi.go, pkg/controller/opentelemetrycollector/reconcile.go, pkg/controller/opentelemetrycollector/reconcile_deployment.go, pkg/controller/opentelemetrycollector/reconcile_deployment_test.go, pkg/controller/opentelemetrycollector/reconcile_serviceaccount.go, pkg/controller/opentelemetrycollector/reconcile_serviceaccount_test.go
- Creates a new service account to be used with the Collector instance
- Allows users to specify an existing service account, managed externally to the operator
Closes #14
=> Added support for service accounts

pkg/adapters/config_to_ports.go, pkg/adapters/config_to_ports_test.go, pkg/parser/receiver.go, pkg/parser/receiver_jaeger.go, pkg/parser/receiver_jaeger_test.go
A couple of fixes and improvements to the 'derive ports from config' based on real usage in a business application.
=> Follow-up fixes to the 'derive ports from config' feature

controllers/opentelemetrycollector_controller_test.go, internal/config/main.go, pkg/collector/adapters/config_to_ports_test.go, pkg/collector/container_test.go, pkg/collector/daemonset_test.go, pkg/collector/deployment_test.go, pkg/collector/parser/receiver_generic_test.go, pkg/collector/parser/receiver_jaeger_test.go, pkg/collector/parser/receiver_test.go, pkg/collector/upgrade/upgrade_test.go, pkg/collector/upgrade/v0_9_0_test.go, pkg/sidecar/pod_test.go
Remove use of deprecated controller runtime log API
=> Remove use of deprecated controller runtime log API

pkg/collector/reconcile/configmap.go, pkg/collector/reconcile/daemonset.go, pkg/collector/reconcile/deployment.go, pkg/collector/reconcile/service.go, pkg/collector/reconcile/serviceaccount.go
Fixes #54 by changing the reconciliation calls to use Patch instead of Update.
=> Use Patch instead of Update in the reconciliation

CHANGELOG.md, versions.txt
closes [https://github.com/open-telemetry/opentelemetry-operator/issues/93](https://github.com/open-telemetry/opentelemetry-operator/issues/93)
=> Bumped OpenTelemetry Collector to v0.13.0

CHANGELOG.md, pkg/collector/upgrade/v0_15_0.go, pkg/collector/upgrade/v0_15_0_test.go, pkg/collector/upgrade/versions.go, versions.txt
=> Bumped OpenTelemetry Collector to v0.15.0

pkg/collector/parser/receiver_jaeger.go, pkg/collector/parser/receiver_jaeger_test.go
The service port created for each Jaeger receiver does not currently set a Protocol, and therefore defaults to TCP. Some Jaeger receiver protocols (i.e. thrift_binary and thrift_compact) are UDP based rather than TCP, and therefore the operator currently creates service port entries that cannot be used due to the protocol mismatch. For example, the following manifest will currently create service port entries with the wrong protocol for thrift_compact and thrift_binary protocols;
```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
name: simplest
spec:
config: |
receivers:
jaeger:
protocols:
grpc:
thrift_compact:
thrift_binary:
thrift_http:
processors:
queued_retry:
exporters:
logging:
loglevel: debug
service:
pipelines:
traces:
receivers: [jaeger]
processors: …
```
=> Explicitly set Service Port Protocol for Jaeger Receivers

CHANGELOG.md, pkg/collector/parser/receiver_generic_test.go, pkg/collector/parser/receiver_otlp.go, pkg/collector/parser/receiver_otlp_test.go, versions.txt
=> Bumped OpenTelemetry Collector to v0.16.0

.github/workflows/publish-images.yaml, main.go
=> Set env vars correctly in workflow steps

pkg/collector/parser/receiver.go
=> Add correct boundary to integer parsing

internal/podinjector/main.go, internal/podinjector/main_test.go
fixes #200
if there are multiple collectors, but a single sidecar, the collector selection should not fail.
this fix ensures we filter the list of collectors first.
Signed-off-by: Vincent Behar <v.behar@free.fr>
=> fix: collector selection should not fail if there is a single sidecar

config/rbac/role.yaml, controllers/opentelemetrycollector_controller.go
Still need to test this changes on an OCP cluster, but this should be enough for fix https://github.com/open-telemetry/opentelemetry-operator/issues/211
See other similar issues here:
https://github.com/operator-framework/operator-sdk/issues/1736
https://github.com/spotahome/redis-operator/issues/98
Signed-off-by: Ruben Vargas <ruben.vp8510@gmail.com>
=> Add permissions for opentelemetry finalizer resource

Makefile, config/crd/bases/opentelemetry.io_opentelemetrycollectors.yaml, config/crd/patches/cainjection_in_opentelemetrycollectors.yaml, config/crd/patches/webhook_in_opentelemetrycollectors.yaml
Change Description
- Upgrade controller-gen version to v0.4.0. It by default creates CRDs using apiVersion apiextensions.k8s.io/v1
- Fix webhook patches to work with apiextensions.k8s.io/v1
=> Upgrade controller-gen to v0.4.0 and change CRDs apiVersion to v1

config/rbac/role.yaml, controllers/opentelemetrycollector_controller.go, main.go, pkg/collector/annotations.go, pkg/collector/annotations_test.go, pkg/collector/daemonset.go, pkg/collector/deployment.go, pkg/collector/reconcile/configmap.go, pkg/collector/reconcile/params.go
Resolves #197 
**Change Description**
Annotate deployment/daemonset with SHA256 of the config data. Publish an event for configmap, whenever config changes. On the reconcile loop triggered by configmap event - deployment/daemonset would be updated leading to rolling restart of the pod.
=> Restart collector pod when config is updated

config/default/webhookcainjection_patch.yaml, config/rbac/auth_proxy_client_clusterrole.yaml, config/webhook/manifests.yaml
Update apiVersion for metrics-reader clusterRole to rbac.authorization.k8s.io/v1
=> Change apiVersion for webhook manifests & patches

bundle/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, bundle/manifests/opentelemetry.io_opentelemetrycollectors.yaml
=> Update bundle to 0.21.0

config/certmanager/certificate.yaml
This prevents cert-manager from creating a certificate with an empty DN, which is invalid according to RFC 5280. See: https://github.com/jetstack/cert-manager/issues/3634#issuecomment-773894638
Fixes #255
=> Force a dummy subject for the self-signed Issuer

Makefile
This fixes the manifests being updated with a wrong version pattern. It just appends a v for the image version only.
Fixes #240
=> Fix manifests being updated with a wrong version pattern

.gitignore, pkg/collector/reconcile/configmap.go, pkg/collector/reconcile/configmap_test.go, pkg/collector/reconcile/daemonset.go, pkg/collector/reconcile/daemonset_test.go, pkg/collector/reconcile/deployment.go, pkg/collector/reconcile/deployment_test.go, pkg/collector/reconcile/opentelemetry_test.go, pkg/collector/reconcile/suite_test.go
Resolves #35 
* Add unit tests for configmap, daemonset, deployment reconcilers
* Fix Patch calls for  configmap, daemonset, deployment reconcilers
Raised https://github.com/open-telemetry/opentelemetry-operator/pull/261 for service and service account reconcilers
=> [Part 1]Add unit tests for reconcile methods

.gitignore, pkg/collector/reconcile/service.go, pkg/collector/reconcile/service_test.go, pkg/collector/reconcile/serviceaccount.go, pkg/collector/reconcile/serviceaccount_test.go, pkg/collector/reconcile/suite_test.go
Second PR for the same issue. As the first one - https://github.com/open-telemetry/opentelemetry-operator/pull/250, was getting big, have split the work into two PRs
This PR covers -
* Add unit tests for service and service account reconcile functions
* Fix patch call for service and service account.
Fixes #35 
=> [Part 2]Add unit tests for reconcile methods 

CHANGELOG.md, versions.txt
This PR bumps the operator to work with the latest stable version of the collector (0.26.0).
Fixes [Issue #264](https://github.com/open-telemetry/opentelemetry-operator/issues/264)
=> Update to collector v0.26.0

config/manager/manager.yaml
This is a change to fix the OOMKilled issue reported in #279 when running operator manager on Openshift 4.7. 
Closes #279
=> Increase memory resource requests and limits

pkg/collector/parser/receiver_otlp.go, pkg/collector/parser/receiver_otlp_test.go
The legacy gRPC port(55680) in OTLP Receiver will be disabled in OTel Collector before the collector GA.
This CR replaced all gRPC port occurrences from `55680` to `4317` in this repo. The same PRs have been posted to the rest of OTel repos. 
**Link to tracking Issue:** 
https://github.com/open-telemetry/opentelemetry-collector/issues/2565
=> Remove the OTLP receiver legacy gRPC port(55680) references

pkg/collector/reconcile/service.go, pkg/collector/reconcile/service_test.go
Copy services from the desired service when reconciling.
For now it only copies the `ports` attribute. We might need to copy additional fields as well. Let me know!
Fixes #256 
Fixes #295
=> Copy desired Service ports when reconciling

.github/workflows/release.yaml
bump operator-sdk version to 1.8.0
closes #298
=> bump operator-sdk version to 1.8.0

Makefile, config/crd/bases/opentelemetry.io_opentelemetrycollectors.yaml
We have the go-lint checks in place in CI. But we do not have it in Makefile to test the linting locally before committing. So added it into Makefile for a better development experience.
=> add go lint rule in Makefile

.github/workflows/release.yaml
=> Refresh go proxy module info on release

api/v1alpha1/opentelemetrycollector_webhook.go, config/webhook/manifests.yaml
The delete webhook configures the `failurePolicy: Ignore` to delete otelcol successfully when the Otel operator isn't available
fixes: #56
=> Add delete webhook

.github/workflows/release.yaml, bundle.Dockerfile, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, config/manager/kustomization.yaml
FIxes: #322 
Note: I tested the operator-sdk version bump by running the operator locally & created a sample CR.
=> Bump operator-sdk to v1.9.0, change v0.27.0 tags to v0.28.0

PROJECT, api/v1alpha1/opentelemetrycollector_types.go, api/v1alpha1/zz_generated.deepcopy.go, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, bundle/manifests/opentelemetry.io_opentelemetrycollectors.yaml, config/crd/bases/opentelemetry.io_opentelemetrycollectors.yaml, docs/otelcol_cr_spec.md, pkg/collector/container.go, pkg/collector/container_test.go
This allows users to customize the container security context settings. It's helpful when some collector features need elevated privileges.
=> Allow customizing security context

pkg/collector/upgrade/v0_31_0.go, pkg/collector/upgrade/v0_31_0_test.go, pkg/collector/upgrade/versions.go
Upgrade routine to fix `influxdb` receiver breaking change in upstream otelcol-contrib repo.
Fixes: #350
=> Add v0.31.0 upgrade routine

pkg/collector/parser/receiver_fluent-forward.go, pkg/collector/parser/receiver_fluent-forward_test.go, pkg/collector/parser/receiver_generic_test.go
[fluentforward](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/fluentforwardreceiver) receiver
Part of #128
=> Add fluentforward receiver

bundle/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml, bundle/manifests/opentelemetry-operator-webhook-service_v1_service.yaml, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, config/default/manager_auth_proxy_patch.yaml, config/rbac/auth_proxy_service.yaml, config/webhook/service.yaml
This PR adds `protocol: TCP` value under `ports` key. This should resolve the error caused by a known [limitation](https://github.com/kubernetes-sigs/structured-merge-diff/issues/130) of Kubernetes 1.19 and eariler.
cc @alolita @jpkrohling
=> Add `protocol: TCP` value under `ports` key to avoid the known limitation for Kubernetes 1.19

.github/workflows/continuous-integration.yaml, .github/workflows/release.yaml, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml
Closes #386 by bumping the operator SDK version to v1.10.1 and re-generating the bundles with this version.
=> Bump operator-sdk to v1.10.1

CONTRIBUTING.md, pkg/collector/parser/receiver_generic.go, pkg/collector/parser/receiver_generic_test.go, pkg/collector/parser/receiver_statsd.go, pkg/collector/parser/receiver_statsd_test.go
[Statsd](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/statsdreceiver) receiver 
As part of #128
=> Add statsd receiver

tests/e2e/smoke-statefulset/00-assert.yaml, tests/e2e/smoke-targetallocator/02-assert.yaml, tests/e2e/statefulset-features/00-assert.yaml, tests/e2e/targetallocator-features/02-assert.yaml
Closes #396
This increases the timeout for the KUTTL StatefulSet assert steps ensuring that the StatefulSet has enough time for completely rolling out. Hopefully this fixes the flaky tests.
=> Increase StatefulSet timeout for KUTTL tests

kuttl-test.yaml, tests/e2e/smoke-statefulset/00-assert.yaml, tests/e2e/smoke-targetallocator/02-assert.yaml, tests/e2e/statefulset-features/00-assert.yaml, tests/e2e/targetallocator-features/02-assert.yaml
Replaces the test specific timeout introduced for StatefulSet KUTTL tests with a global timeout for all the tests.
=> Added global timeout

pkg/collector/parser/receiver_aws-xray.go, pkg/collector/parser/receiver_aws-xray_test.go, pkg/collector/parser/receiver_generic_test.go
Syncing AWS XRAY receiver from [collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/awsxrayreceiver#aws-x-ray-receiver). Added the default port as `2000` as mentioned in `README.md`.
Just to be clear I am not adding any other default config parameters such as `transport` as `udp`  and other fields as we expect this to be taken care by users right?. We are only concerned with default port that needs to be exposed for this particular receiver.
WDYT @jpkrohling ?
Part of #128
=> Add aws xray receiver

bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, config/manager/manager.yaml
The command in CSV is not needed because the dockerfile uses entrypoint.
It is useful to rely on the default conventions to allow easy override
of the operator image - e.g. a productized version with vendor specific
functionality.
=> Remove cmd from CSV

api/v1alpha1/opentelemetrycollector_types.go, api/v1alpha1/zz_generated.deepcopy.go, bundle/manifests/opentelemetry.io_opentelemetrycollectors.yaml, config/crd/bases/opentelemetry.io_opentelemetrycollectors.yaml, docs/otelcol_cr_spec.md, pkg/collector/container.go, pkg/collector/container_test.go
Add support for passing `envFrom` values into Collector's pods.
=> feat: add `envFrom` to collector spec

pkg/sidecar/annotation.go, pkg/sidecar/annotation_test.go, pkg/sidecar/pod.go, pkg/sidecar/pod_test.go, pkg/sidecar/podmutator.go
Making these APIs private as there is no need to expose them. Before they were public bc the sidecar implementation was split between two packages.
=> Make some APIs in the sidecar package private

.github/workflows/publish-images.yaml
Updates #492 
Now just publish to both registries and after the following release we can switch to GHCR in CSV, makefile and other places.
=> Publish images to GHCR

CONTRIBUTING.md, Makefile, README.md
Closes #490
- Creating Compatibility matrix cert-manager.
- Creating variable CERTMANAGER_VERSION.
=> Compatibility matrix cert manager

.github/workflows/publish-autoinstrumentation-nodejs.yaml, .gitignore, autoinstrumentation/nodejs/.dockerignore, autoinstrumentation/nodejs/Dockerfile, autoinstrumentation/nodejs/package.json, autoinstrumentation/nodejs/src/autoinstrumentation.ts, autoinstrumentation/nodejs/tsconfig.json, versions.txt
Created image: https://github.com/anuraaga/opentelemetry-operator/pkgs/container/opentelemetry-operator%2Fautoinstrumentation-nodejs
I think the autoinstrumentation wrapper could be pushed to js-contrib though we'll still need to package something with Docker. Hopefully it's OK to include it here for now to try out the autoinstrumentation experience.
@pavolloffay @jpkrohling 
/cc @dyladan 
Would be used by https://github.com/open-telemetry/opentelemetry-operator/pull/507
=> Add docker image containing nodejs auto instrumentation

README.md, pkg/instrumentation/sdk_test.go, tests/e2e/instrumentation-java/00-install-instrumentation.yaml, tests/e2e/instrumentation-java/01-assert.yaml
The GRPC exporter uses 4317 port not 4318.
=> Fix port in Instrumentation exporter to 4317 to use grpc

README.md
* codecov - disabled
* quay - we are migrating to ghcr
* code climate does not seem to work
=> Remove badges from readme

CONTRIBUTING.md, Makefile
The OLM instructions are outdatted, now there is a much simpler way to deploy OLM in k8s and deploy the freshly build image.
=> Update OLM instructions

.github/workflows/publish-autoinstrumentation-python.yaml, autoinstrumentation/python/Dockerfile, autoinstrumentation/python/requirements.txt, versions.txt
Created https://github.com/anuraaga/opentelemetry-operator/pkgs/container/opentelemetry-operator%2Fautoinstrumentation-python with it
I will write up the PR for the operator change after #507 is in. The mechanism, which I verified locally, is
`PYTHONPATH=/otel-autoinstrumentation/opentelemetry/instrumentation/auto_instrumentation:$PYTHONPATH:/otel-autoinstrumentation`
The trick is that the first entry is pointing to the folder with OTel's `sitecustomize.py` which gets automatically executed.
This is the same as what the `opentelemetry-instrument` script does I think except also appends the opentelemetry libraries to pythonpath, which otherwise is usually pip installed.
https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/opentelemetry-instrumentation/src/opentelemetry/i …
=> Create Docker image for Python auto-instrumentation.

.github/workflows/release.yaml, Makefile, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml
https://github.com/open-telemetry/opentelemetry-operator/pkgs/container/opentelemetry-operator%2Fopentelemetry-operator
=> Use operator image from GHCR

apis/v1alpha1/propagators.go, bundle/manifests/opentelemetry.io_instrumentations.yaml, config/crd/bases/opentelemetry.io_instrumentations.yaml
The propagator name should be "none" https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md
=> Fix no propagator to none

autoinstrumentation/nodejs/package.json, versions.txt
Reverts open-telemetry/opentelemetry-operator#546
Fixes #550 
@pavolloffay Oops sorry for not noticing when reviewing. It looks like `js` has released 0.27.0 but not `js-contrib` yet from what I can tell, which has the instrumentations.
https://github.com/open-telemetry/opentelemetry-js-contrib/releases
=> Revert "Upgrade nodejs auto instrumentation to 1.27.0"

apis/v1alpha1/opentelemetrycollector_types.go, apis/v1alpha1/zz_generated.deepcopy.go, bundle/manifests/opentelemetry.io_opentelemetrycollectors.yaml, config/crd/bases/opentelemetry.io_opentelemetrycollectors.yaml, docs/api.md, pkg/collector/daemonset.go, pkg/collector/daemonset_test.go, pkg/collector/deployment.go, pkg/collector/deployment_test.go, pkg/collector/statefulset.go, pkg/collector/statefulset_test.go
=> Add support for podSecurityContext

internal/webhookhandler/webhookhandler_test.go, pkg/instrumentation/podmutator_test.go
This allows tests to be run multiple times without needing to manually delete the namespaces, or recreate the cluster, between runs.
Fixes #523
=> Delete namespaces created in tests.

apis/v1alpha1/instrumentation_types.go, apis/v1alpha1/opentelemetrycollector_types.go
The removed annotations seem to be noop. The CSV/CRD does not change after removal.
=> Remove unused operator-sdk annotations from kinds

apis/v1alpha1/instrumentation_webhook.go, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, config/rbac/role.yaml, main.go, pkg/instrumentation/upgrade/upgrade.go, pkg/instrumentation/upgrade/upgrade_suite_test.go, pkg/instrumentation/upgrade/upgrade_test.go
At the moment only the Java image is being upgraded automatically.
=> Add upgrade for Instrumentation kind

config/manager/kustomization.yaml, pkg/instrumentation/podmutator_test.go, pkg/instrumentation/sdk.go, pkg/instrumentation/sdk_test.go, tests/e2e/instrumentation-java/01-assert.yaml, tests/e2e/instrumentation-nodejs/01-assert.yaml, tests/e2e/instrumentation-python/01-assert.yaml
Pod name, UID and node name might not be set in pod object in webhook.
Resolves #554
=> Add some resource attributes via k8s downward API

pkg/collector/adapters/config_to_probe.go, pkg/collector/adapters/config_to_probe_test.go, pkg/collector/container.go, pkg/collector/container_test.go
Add liveness probe to created container if otelcol configuration supports a health_check.
Fixes #571
Signed-off-by: Adrian Kostrubiak <adrian.kostrubiak@tomtom.com>
=> Add liveness probe to created container if otelcol configuration supports a health_check.

Makefile
The current approach is flaky and cert-manager
docs suggests to use cmctl to test if the cert-manager is
ready.
This should fix flaky CI e2e jobs:
* https://github.com/open-telemetry/opentelemetry-operator/runs/4331745148?check_suite_focus=true
=> Use cmctl to test if cert-manager is ready

bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, config/manager/manager.yaml, main.go
add healthz, readyz probes to controller manager.
fixes #602
Signed-off-by: Adrian Kostrubiak adrian.kostrubiak@tomtom.com
-------
I'm unclear if there's a good way to add unit/etc tests for this change. If there is, I'd welcome any ideas or suggestions.
=> add healthz, readyz probes to controller manager.

pkg/instrumentation/sdk_test.go
The PR #464 introduced a test that is printing debugging information to the console even when the test is passing. This PR fixes that.
=> Remove fmt.Println from test

README.md, apis/v1alpha1/opentelemetrycollector_types.go, apis/v1alpha1/opentelemetrycollector_webhook.go, apis/v1alpha1/upgrade_strategy.go, bundle/manifests/opentelemetry.io_opentelemetrycollectors.yaml, config/crd/bases/opentelemetry.io_opentelemetrycollectors.yaml, controllers/suite_test.go, docs/api.md, internal/webhookhandler/webhookhandler_suite_test.go, pkg/collector/reconcile/suite_test.go, pkg/collector/upgrade/suite_test.go, pkg/collector/upgrade/upgrade.go, pkg/collector/upgrade/upgrade_test.go
Add OpenTelemetryCollector.Spec.UpgradeStrategy with allowable values: `automatic`, `none`
fixes #598
Signed-off-by: Adrian Kostrubiak adrian.kostrubiak@tomtom.com
=> Add OpenTelemetryCollector.Spec.UpgradeStrategy

pkg/collector/parser/receiver.go, pkg/collector/parser/receiver_test.go
This PR is an attempt  to fix #527 to ignore certain kubeletstats receivers when deriving service from config 
Signed-off-by: Mritunjay Sharma <mritunjaysharma394@gmail.com>
=> [FIX]: adds case to handle kubeletstats reciever to ignore endpoint

pkg/naming/triming.go, pkg/naming/triming_test.go
Fixes #596
In the previous PR for this issue a case was missed when submitting the name trimming code.
This issue caused, in certain cases, an error where `fmt.Sprintf()` would receive less values that the format expected and would therefore have a missing parameter. 
The result of this are formatted texts that look like this:
```bash
--- FAIL: TestTruncate (0.00s)
--- FAIL: TestTruncate/first_value_gets_truncated,_second_added (0.00s)
/home/mihai/projects/open-telemetry/opentelemetry-operator/pkg/naming/triming_test.go:78: 
Error Trace:	triming_test.go:78
Error:      	Not equal: 
expected: "4d96-11ea-b174-c85b7644b6b5-5d0c1e62-4d96-11ea-b174--collector"
actual  : "4d96-11ea-b174-c85b7644b6b5-5d0c1e62-4d96-11e-%!s(MISSING)-coll"
Diff:
--- Expected
+++ Actual
@@ -1 +1 @@ …
```
=> Fix issue in name trimming not adding all values

autoinstrumentation/java/Dockerfile, autoinstrumentation/nodejs/Dockerfile, autoinstrumentation/python/Dockerfile
Fixes Java auto-instrumentation permissions when fsGroup is in use in the container. 
Fixes #636
=> Add read permission to 'group' for java autoinstrumentation JAR

.github/workflows/publish-images.yaml
Fixes:
```
docker run --rm -it  ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator:v0.41.0                                                                                         ploffay@fedora
{"level":"info","ts":1640160584.5407813,"msg":"Starting the OpenTelemetry Operator","opentelemetry-operator":"0.41.0","opentelemetry-collector":"otel/opentelemetry-collector:0.41.0","opentelemetry-targetallocator":"quay.io/opentelemetry/target-allocator:0.1.0","auto-instrumentation-java":"ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:0.0.0","build-date":"2021-12-10T16:30:10Z","go-version":"go1.17.5","go-arch":"amd64","go-os":"linux"}
{"level":"error","ts":1640160584.5411556,"logger":"controller-runtime.client …
```
=> Set instrumentation versions when building official image

CHANGELOG.md, README.md, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, versions.txt
This is an operator patch release, previous PRs fix the issue in auto-instrumentation nodejs, python and java image version will be picked.
=> Otel-Operator patch release

internal/config/main.go, main.go
Signed-off-by: Ruben Vargas <ruben.vp8510@gmail.com>
`pflag.Parse()` Should be called before we use the arguments to initialize the config structure. If not, the variables won't contain the argument values, and the operator won't honor the argument values.
Also, removed the config flags, as this is not used anymore since this PR https://github.com/open-telemetry/opentelemetry-operator/pull/449 migrated the flags to `main.go`
=> Parse flags before using them in config

autoinstrumentation/python/requirements.txt
=> Add b3, jaeger, ottrace propagators to python instrumentation

.github/workflows/publish-autoinstrumentation-nodejs.yaml, autoinstrumentation/nodejs/package.json, autoinstrumentation/nodejs/src/autoinstrumentation.ts, autoinstrumentation/nodejs/tsconfig.json
=> Update nodejs instrumentation to 0.27.0

bundle/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml, bundle/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, bundle/manifests/opentelemetry-operator-webhook-service_v1_service.yaml, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, bundle/manifests/opentelemetry.io_instrumentations.yaml, bundle/manifests/opentelemetry.io_opentelemetrycollectors.yaml, config/default/kustomization.yaml
Resolves #652
Example objects.yaml: 
[out.txt](https://github.com/open-telemetry/opentelemetry-operator/files/8031610/out.txt)
=> Use unique label and selector for operator objects

apis/v1alpha1/instrumentation_webhook.go, pkg/instrumentation/podmutator_test.go, tests/e2e/instrumentation-java/00-install-instrumentation.yaml, tests/e2e/instrumentation-java/01-assert.yaml, tests/e2e/instrumentation-nodejs/00-install-instrumentation.yaml, tests/e2e/instrumentation-nodejs/01-assert.yaml, tests/e2e/instrumentation-python/00-install-instrumentation.yaml, tests/e2e/instrumentation-python/01-assert.yaml
Resolves https://github.com/open-telemetry/opentelemetry-operator/issues/706
=> Add SPLUNK_ env prefix support to Instrumentation kind

pkg/collector/adapters/config_to_ports_test.go, pkg/collector/parser/receiver_generic.go, pkg/collector/parser/receiver_jaeger.go, pkg/collector/parser/receiver_otlp.go, pkg/collector/parser/receiver_zipkin.go, pkg/collector/reconcile/service_test.go, tests/e2e/smoke-simplest/00-assert.yaml
Signed-off-by: Sergei Semenchuk <pdp.eleven11@gmail.com>
=> Add appProtocol for otlp and jaeger receiver parsers

versions.txt
=> Bump default java auto-instrumentation version to 1.11.1

main.go, pkg/collector/upgrade/upgrade.go, pkg/collector/upgrade/upgrade_test.go, pkg/collector/upgrade/v0_15_0.go, pkg/collector/upgrade/v0_15_0_test.go, pkg/collector/upgrade/v0_19_0.go, pkg/collector/upgrade/v0_19_0_test.go, pkg/collector/upgrade/v0_24_0.go, pkg/collector/upgrade/v0_24_0_test.go, pkg/collector/upgrade/v0_2_10.go, pkg/collector/upgrade/v0_31_0.go, pkg/collector/upgrade/v0_31_0_test.go, pkg/collector/upgrade/v0_36_0.go, pkg/collector/upgrade/v0_36_0_test.go, pkg/collector/upgrade/v0_38_0.go, pkg/collector/upgrade/v0_38_0_test.go, pkg/collector/upgrade/v0_39_0.go, pkg/collector/upgrade/v0_39_0_test.go, pkg/collector/upgrade/v0_41_0.go, pkg/collector/upgrade/v0_41_0_test.go, pkg/collector/upgrade/v0_43_0.go, pkg/collector/upgrade/v0_43_0_test.go, pkg/collector/upgrade/v0_9_0.go, pkg/collector/upgrade/v0_9_0_test.go, pkg/collector/upgrade/versions.go
- Creating struct to include Record parameter
- Changing signature of upgrade functions
- Switching upgrades messages to events.
Resolves #486
=> Storing upgrade status into events

.github/workflows/continuous-integration.yaml, .github/workflows/release.yaml, .github/workflows/scorecard.yaml, Makefile
This PR installs operator-sdk to ./bin which makes sure
that always correct version of operator-sdk is used.
This should solve issues like https://github.com/open-telemetry/opentelemetry-operator/pull/719#discussion_r810917431
=> Make sure correct version of operator-sdk is always used

apis/v1alpha1/opentelemetrycollector_types.go, bundle/manifests/opentelemetry.io_opentelemetrycollectors.yaml, config/crd/bases/opentelemetry.io_opentelemetrycollectors.yaml, docs/api.md
This is follow-up after #707. It's better to inform users that status messages are not used anymore.
=> Deprecate otelcol status messages

main.go
Depends on https://github.com/open-telemetry/opentelemetry-operator/pull/719
=> Use OTEL collector image from GHCR

Makefile
Avoid issues like https://github.com/open-telemetry/opentelemetry-operator/pull/719#discussion_r812638158
=> Fail CI if bundle.Dockerfile is not the same as generated one

.ci/create-release-github.sh, .github/workflows/release.yaml
Right now the release process is using @jpkrohling personal token (https://github.com/open-telemetry/opentelemetry-operator/releases). It works but it confused me that he actually explicitly created the release I was working on.
Using standard token should be preferred as we don't care about e.g. expiration.
=> Use default github token to publish the release

pkg/collector/daemonset.go, pkg/collector/daemonset_test.go, pkg/collector/deployment.go, pkg/collector/deployment_test.go, pkg/collector/statefulset.go, pkg/collector/statefulset_test.go, pkg/collector/utils.go
Resolves https://github.com/open-telemetry/opentelemetry-operator/issues/690
I added a simple check to make the pods' DNSPolicy matching the `hostNetwork` option
=> Match pod `dnsPolicy` to `hostNetwork` config

bundle/tests/scorecard/config.yaml, config/scorecard/patches/basic.config.yaml, config/scorecard/patches/olm.config.yaml
This should have been done as part of the bump operator-sdk version.
=> Bump scorecard version to 1.17.0 to align with operator-sdk version

.github/workflows/publish-images.yaml
The configuration for the docker meta action is not correct at the moment: https://github.com/open-telemetry/opentelemetry-operator/runs/5304084350?check_suite_focus=true#step:6:1
=> Fix docker meta action

README.md
I am no longer able to allocate time to be a maintainer of the operator
due to focusing on other parts of OpenTelemetry.
I am moving myself to the Emeritus section according to the rules introduced in
https://github.com/open-telemetry/community/pull/961
I have also listed approvers and maintainers directly in the README, like we
do in the Collector repos. I will also remove Collector github teams' permissions
from this repo since we have github teams for operator to avoid confusion as to
who has what permissions.
=> Remove tigrannajaryan as a maintainer

.github/workflows/publish-images.yaml
Latest publish builds are failing  https://github.com/open-telemetry/opentelemetry-operator/runs/5388522267?check_suite_focus=true#step:6:28
This PR should fix it and publish the `main` tag
=> Fix publishing main docker tag for operator image

autoinstrumentation/nodejs/package.json
Bump NodeJS auto-instrumentation packages - [changes](https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/auto-instrumentations-node-v0.27.4)
=> chore(nodejs): bump auto-instrumentations

.github/workflows/e2e.yaml, .github/workflows/scorecard.yaml, README.md
Resolves #734 
This PR changes CI to run tests on the lowest supported k8s version 1.19 and highest 1.23 
The PR essentially ensures that the operator is supported on a broader range of Kubernetes versions. We are committed to resource the support on k8s 1.19 and higher. 
The tests are run on 1.19 and the highest version, the versions in between does not have to be tested as there is no breaking change "in between". We are taking the same approach in other k8s operators.
=> Support k8s 1.19 and higher

Makefile, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml
All other OTEL images are published as `X.Y.Z` (without `v` prefix).  
The operator image is already published without prefix - https://github.com/open-telemetry/opentelemetry-operator/pkgs/container/opentelemetry-operator%2Fopentelemetry-operator 
@jpkrohling is there any reason why the operator image has `v` prefix?
=> Remove v prefix from the container image version/tag

README.md, autoinstrumentation/java/Dockerfile, autoinstrumentation/nodejs/Dockerfile, autoinstrumentation/python/Dockerfile
=> doc: customized auto-instrumentation

config/manager/manager.yaml, config/prometheus/monitor.yaml, config/rbac/auth_proxy_service.yaml, config/webhook/service.yaml
Fixes #791.
Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>
=> add labels in order to make selectors unique

internal/config/main.go, internal/config/options.go, main.go, pkg/collector/daemonset.go, pkg/collector/daemonset_test.go, pkg/collector/deployment.go, pkg/collector/deployment_test.go, pkg/collector/horizontalpodautoscaler.go, pkg/collector/labels.go, pkg/collector/labels_test.go, pkg/collector/reconcile/configmap.go, pkg/collector/reconcile/service.go, pkg/collector/reconcile/service_test.go, pkg/collector/serviceaccount.go, pkg/collector/statefulset.go, pkg/collector/statefulset_test.go
=> Filter out unneeded labels

pkg/collector/reconcile/deployment.go
Resolves #803 
Since the spec.replicas in [docs](https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api.md#opentelemetrycollectorspec) is not required, so it may be nil.
Need check whether replicas is nil before get value of it.
=> fix panic when spec.replicas is nil

apis/v1alpha1/opentelemetrycollector_webhook.go, apis/v1alpha1/opentelemetrycollector_webhook_test.go
=> Set replicas to default value

internal/webhookhandler/webhookhandler.go, internal/webhookhandler/webhookhandler_test.go
=> Do not block pod creating on internal error in webhook

README.md
This PR updates the sidecar example in the README, as it does not work. It removes the unnecessary  `otlpreceiver` and changes the `jaegerreceiver` protocol to `thrift_compact` instead of `grpc`. This is also reflected in a PR on the `opentelemetry-helm-charts` repository, [183](https://github.com/open-telemetry/opentelemetry-helm-charts/pull/183).
=> Update sidecar example in README

README.md, pkg/collector/reconcile/service.go, pkg/collector/reconcile/service_test.go
resolves #818 
Signed-off-by: Robert Kukura <rkukura@redhat.com>
=> Create serving certs for headless services on OpenShift (#818)

pkg/collector/reconcile/deployment.go, pkg/collector/reconcile/deployment_test.go
If number of replicas in current deployment status is bigger than
MaxReplicas and HPA is enabled set deployment replicas to MaxReplicas.
=> Set replicas to MaxReplicas if HPA is enabled

main.go
This addresses issue #841
The PR corrects the default instrumentation image names if no annotation is provided.  The previous behavior was that nodejs image would default to Java but now it should correctly fill in the Java, Nodejs, and Python images, if no annotation is provided.
=> Fix Default Image Annotations

README.md, pkg/constants/env.go, pkg/instrumentation/sdk.go, pkg/sidecar/attributes.go, pkg/sidecar/attributes_test.go, pkg/sidecar/pod.go, pkg/sidecar/pod_test.go, pkg/sidecar/podmutator.go, tests/e2e/smoke-sidecar/01-assert.yaml
This PR adds an env var `OTEL_RESOURCE_ATTRIBUTES` to the sidecar pod, this envvar contains the k8s attributes of the pod, this is to be used for example with the resource detector processor to attach k8s attributes to spans,logs and metrics.
Updates #573 
Signed-off-by: Ruben Vargas <ruben.vp8510@gmail.com>
=> Add resource attributes to collector sidecar

pkg/instrumentation/sdk.go, pkg/instrumentation/sdk_test.go, tests/e2e/instrumentation-java/01-assert.yaml, tests/e2e/instrumentation-nodejs/01-assert.yaml, tests/e2e/instrumentation-python/01-assert.yaml
Move OTEL_RESOURCE_ATTRIBUTES to last position on env list.
When `OTEL_RESOURCE_ATTRIBUTES` environment variable uses other env vars as attributes value they have to be configured before. It is mandatory to set right order to avoid attributes with value pointing to the name of used environment variable instead of its value.
**Correct order of env vars**
```
env:
- name: OTEL_RESOURCE_ATTRIBUTES_NODE_NAME
valueFrom:
fieldRef:
fieldPath: spec.nodeName
- name: OTEL_RESOURCE_ATTRIBUTES_POD_NAME
valueFrom:
fieldRef:
fieldPath: metadata.name
- name: OTEL_RESOURCE_ATTRIBUTES
value: k8s.node.name=$(OTEL_RESOURCE_ATTRIBUTES_NODE_NAME),k8s.pod.name=$(OTEL_RESOURCE_ATTRIBUTES_POD_NAME)
```
This PR fixes: https://github.com/open-telemetry/opentelemetry-operator/issues/793
=> Fix K8s attributes values in OTEL_RESOURCE_ATTRIBUTES env var

README.md
@pavolloffay : missing documentation for multiple injection based on "instrumentation.opentelemetry.io/container-names"  #689
=> Documentation for container-names annotation

pkg/collector/daemonset.go, pkg/collector/daemonset_test.go, pkg/collector/deployment.go, pkg/collector/deployment_test.go, pkg/collector/labels.go, pkg/collector/labels_test.go, pkg/collector/reconcile/daemonset.go, pkg/collector/reconcile/deployment.go, pkg/collector/reconcile/statefulset.go, pkg/collector/serviceaccount.go, pkg/collector/statefulset.go, pkg/collector/statefulset_test.go
- Add a new `SelectorLabels` to get the static labels for selectors
- Make sure `Labels` uses `SelectorLabels`
- Make sure selector labels aren't updated on `Deployment`, `DaemonSet` and `StatefullSet` update to avoid reconciliation errors.
close #840
=> avoid non static labels in workload objects selector

Dockerfile, cmd/otel-allocator/Dockerfile
=> Fix docker multiarch build for operator

main.go
This PR is related to the following issues: 
* https://github.com/open-telemetry/opentelemetry-helm-charts/issues/214
* https://github.com/open-telemetry/opentelemetry-operator/issues/896
It includes a new CLI flag `webhook-port` to allow the user to select a different port in case the default `9443` is already in use by another cluster add-on. 
The second commit fixes a typo in the code that prevented the correct use of the CLI flag `health-probe-addr`, before the change, you'll get the following error if you attempt to pass the flag. 
```
unknown flag: --health-probe-addr
```
=> Added extra cli flag webhook-port

README.md, pkg/instrumentation/podmutator.go, tests/e2e/instrumentation-java-other-ns/00-cleanup-other-ns.yaml, tests/e2e/instrumentation-java-other-ns/00-install-collector.yaml, tests/e2e/instrumentation-java-other-ns/00-install-instrumentation.yaml, tests/e2e/instrumentation-java-other-ns/01-assert.yaml, tests/e2e/instrumentation-java-other-ns/01-install-app.yaml
This PR adds support for specifying the namespace of an instrumentation instance in the `inject-*` annotations.
closes #886
=> Cross namespace instrumentation

cmd/otel-allocator/discovery/discovery.go, cmd/otel-allocator/discovery/discovery_test.go, cmd/otel-allocator/go.mod, cmd/otel-allocator/main.go, cmd/otel-allocator/watcher/file.go, cmd/otel-allocator/watcher/main.go, cmd/otel-allocator/watcher/promOperator.go
Updated the module name and imports for multiple files within otel-allocator from github.com/otel-allocator to github.com/open-telemetry/opentelemetry-operator/cmd/otel-allocator
This closes #907
=> updated module name and imports

Makefile, README.md
Signed-off-by: Yuri Sa [yurimsa@gmail.com]
- Modifying makefile to install cert-manager 1.8.0.
- Adding on Compatibility Matrix this cert-manager version for the last release.
=> Add cert manager 1.8.0

go.mod
Resolves #912 
see https://go.dev/blog/go116-module-changes#TOC_5.
=> Retract version 1.51.0 from gomod

pkg/collector/reconcile/deployment.go, pkg/collector/reconcile/deployment_test.go
Fix the issue that the number of target-allocator replicas
=> Fix the issue that the number of target-allocator replicas 

config/prometheus/monitor.yaml
=> Fixing monitor configuration

README.md, pkg/instrumentation/annotation.go, pkg/instrumentation/podmutator.go, pkg/instrumentation/sdk.go, pkg/instrumentation/sdk_test.go, tests/e2e/instrumentation-sdk/00-install-collector.yaml, tests/e2e/instrumentation-sdk/00-install-instrumentation.yaml, tests/e2e/instrumentation-sdk/01-assert.yaml, tests/e2e/instrumentation-sdk/01-install-app.yaml
Closes #990.
Adds support for injecting SDK environment variables only,
without injecting language-specific libraries or config.
Usage:
```bash
instrumentation.opentelemetry.io/inject-sdk: "true"
```
=> Enable instrumentation injecting only core SDK config

versions.txt
Updates python auto instrumentation to it's current version of 0.32b0 to match autoinstrumentation/python/requirements.txt, which it normally mirrors.
=> chore(operator): update python inst to 0.32b0

pkg/collector/adapters/config_to_ports.go, pkg/collector/adapters/config_to_ports_test.go
Signed-off-by: Kevin Earls <kearls@redhat.com>
This should fix #969.  If there is more than one receiver defined, ports may be returned in a different order than that in which they were created.  Ideally they would always be in the same order as they are defined, but because Go does not guarantee order when iterating over keys from a map, we cannot guarantee this.
=> Sort order of ports returned to fix flaky tests

pkg/collector/parser/receiver.go, pkg/collector/reconcile/deployment.go, pkg/collector/reconcile/deployment_test.go
This PR closes #1008 by removing the special target allocator behavior for not updating the container's spec. The desired behavior is to update the TA on a spec change. This also fixes a superfluous print from the operator that clogs operator logs due to the fact that the prometheus receiver has no endpoint to expose as it is a scrape based receiver.
```
targetAllocator:
...
prometheusCR:
enabled: false
```
There was no prometheusCR flag initially
```
targetAllocator:
...
prometheusCR:
enabled: true
```
=> Update the target allocator on any manifest change

cmd/otel-allocator/allocation/allocator.go, cmd/otel-allocator/collector/collector.go, cmd/otel-allocator/discovery/discovery.go, cmd/otel-allocator/main.go, cmd/otel-allocator/watcher/main.go
This PR closes #1029 by adding in instrumentation for the target allocator through Prometheus. The amount of metrics was kept to be minimal so that we can migrate this to use the otel go SDK in the future. The current implementation adds a prometheus endpoint `/metrics` to the existing `:8080` port. It also adds in a mux middleware to track some metrics about requests made to the endpoints.
<details>
<summary>Metrics Reported</summary>
<br>
```
```
</details>
=> Instrument TA with prometheus

cmd/otel-allocator/allocation/allocator.go, cmd/otel-allocator/allocation/allocator_test.go, cmd/otel-allocator/allocation/http.go, cmd/otel-allocator/main.go
This PR addresses and closes #1037 by introducing a new hashing function that ensure no collisions between targets based on the target's label set. This also introduces a small change that scopes the target items list to be private within the allocator and a new getter to expose that to other packages. A new test was added as well to verify that this change works as expected.
=> Resolve bug where TA doesn't allocate all targets

cmd/otel-allocator/allocation/allocator.go, cmd/otel-allocator/allocation/allocator_test.go, cmd/otel-allocator/allocation/http.go
fixes https://github.com/open-telemetry/opentelemetry-operator/issues/1034
`Allocator.targetItems` and `Allocator.collectors` can no longer be accessed outside of Allocator functions.  Instead, two functions that copy the respective maps and return them for read-only use are exported.
=> Protect allocator maps behind mutex, create getter funcs for them

CHANGELOG.md, README.md, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, versions.txt
[x] Release OpenTelemetry Operator v0.58.0
[x] Adding missing PRs into the changelog and compatibility table related to v0.57.2
=> Otel Operator Release v0.58.0

.github/workflows/continuous-integration.yaml, .github/workflows/e2e.yaml, .github/workflows/release.yaml, .github/workflows/scorecard.yaml, Dockerfile, cmd/otel-allocator/Dockerfile, cmd/otel-allocator/config/config.go, cmd/otel-allocator/go.mod, go.mod, pkg/collector/adapters/config_validate.go, pkg/collector/reconcile/horizontalpodautoscaler_test.go, pkg/collector/reconcile/suite_test.go, pkg/collector/upgrade/noop.go, pkg/targetallocator/serviceaccount.go
=> Use golang 1.19

internal/config/main.go
Signed-off-by: Kevin Earls <kearls@redhat.com>
=> Change log message to V(2), be sure to pass strings so it doesn't panic

pkg/instrumentation/sdk.go
Signed-off-by: Kevin Earls <kearls@redhat.com>
This fixes some of the test failures we occasionally see in CI as described in #959 
There are others which I believe are related to acquiring a leader lease taking more than 2.5 minutes.  I will add more information about that to #959 
Resolves #959
=> Add retry loop for client.get of replicaset as that sometimes fails

pkg/autodetect/main.go, pkg/autodetect/main_test.go
Signed-off-by: Kevin Earls <kearls@redhat.com>
=> Make sure we return the right version when autoscaling v2 is found

.github/workflows/e2e.yaml, .github/workflows/scorecard.yaml, kind-1.19.yaml, kind-1.20.yaml, kind-1.21.yaml, kind-1.22.yaml, kind-1.23.yaml, kind-1.24.yaml, kind-1.25.yaml
Signed-off-by: Israel Blancas <iblancasa@gmail.com>
This PR:
* Upgrades the `kind` container images to the latest
* Add testing for Kubernetes 1.25
=> Upgrade kind images and add testing for Kubernetes 1.25

README.md
As many probably copy the first example in the README, this should contain the suggested two default processors. Running without them is a bad idea, therefore I suggest this change.
=> Add default settings to README

controllers/opentelemetrycollector_controller.go
Saw randomly that a new context is created in the reconciler. Or is there a reason for this?
=> reconcile otel collector on given context

apis/v1alpha1/opentelemetrycollector_webhook.go, apis/v1alpha1/opentelemetrycollector_webhook_test.go
Separating this unit test and logic changes into their own PR as suggested [here](https://github.com/open-telemetry/opentelemetry-operator/pull/1070#discussion_r984666286)
=> Add missing nil checks in collector validating webhook

apis/v1alpha1/opentelemetrycollector_types.go, apis/v1alpha1/opentelemetrycollector_webhook.go, apis/v1alpha1/opentelemetrycollector_webhook_test.go, bundle/manifests/opentelemetry.io_opentelemetrycollectors.yaml, config/crd/bases/opentelemetry.io_opentelemetrycollectors.yaml, docs/api.md, pkg/collector/daemonset.go, pkg/collector/daemonset_test.go, pkg/collector/deployment.go, pkg/collector/deployment_test.go, pkg/collector/statefulset.go, pkg/collector/statefulset_test.go
=> Adds support of priorityClassName for otel collector

CHANGELOG.md, README.md, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, versions.txt
=> Release v0.61.0

pkg/collector/reconcile/service.go, pkg/collector/reconcile/service_test.go
=> Using immutable labels as service selectors

bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, config/manager/manager.yaml
=> Avoid OOM of the operator

CHANGELOG.md, README.md, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, versions.txt
Are there any missing migrations? [[otelcol-contrib-v0.62.0](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.62.0)][[otelcol-contrib-v0.63.0](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.63.0)]
Please have a look on the bumped versions in `version.txt`.
Ups i didnt see https://github.com/open-telemetry/opentelemetry-operator/issues/1210#issuecomment-1295696100. Let me change it to `v0.63.1`.
Closes #1210 #1176
cc @pavolloffay
=> Prepare release 0.63.1

cmd/otel-allocator/allocation/consistent_hashing.go, cmd/otel-allocator/allocation/http.go, cmd/otel-allocator/allocation/http_test.go, cmd/otel-allocator/allocation/least_weighted.go, cmd/otel-allocator/allocation/least_weighted_test.go, cmd/otel-allocator/allocation/strategy.go, cmd/otel-allocator/discovery/discovery.go, cmd/otel-allocator/discovery/discovery_test.go, cmd/otel-allocator/main.go, cmd/otel-allocator/target/target.go
Resolves https://github.com/open-telemetry/opentelemetry-operator/issues/1213
=> [target-allocator] create new target package

apis/v1alpha1/opentelemetrycollector_types.go, bundle/manifests/opentelemetry.io_opentelemetrycollectors.yaml, cmd/otel-allocator/allocation/consistent_hashing.go, cmd/otel-allocator/allocation/least_weighted.go, cmd/otel-allocator/allocation/strategy.go, cmd/otel-allocator/config/config.go, cmd/otel-allocator/discovery/discovery.go, cmd/otel-allocator/discovery/discovery_test.go, cmd/otel-allocator/main.go, cmd/otel-allocator/prehook/prehook.go, cmd/otel-allocator/prehook/relabel.go, cmd/otel-allocator/prehook/relabel_test.go, config/crd/bases/opentelemetry.io_opentelemetrycollectors.yaml, docs/api.md, pkg/collector/reconcile/configmap.go, pkg/collector/reconcile/configmap_test.go
PR to resolve https://github.com/open-telemetry/opentelemetry-operator/issues/1064
The goal of this PR is to drop targets before targets are assigned to the collectors by the allocator.  Not necessary to allocate targets that will be dropped in the relabel step.
Now the `Allocator` will check if there is a `Filter` set and apply it to filter down the list of targets.
`filterStrategy=relabel-config` drops targets based on Prometheus relabel_config 
No filtering is the default.
=> [target-allocator] Add a pre-hook to the allocator to filter out dropped targets

main.go
=> fix min tls setting for webhook server (#1225)

pkg/collector/reconcile/service.go
Resolves https://github.com/open-telemetry/opentelemetry-operator/issues/898
=> add headless label

CHANGELOG.md, README.md, RELEASE.md, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, versions.txt
=> Prepare for 0.66.0 release

pkg/collector/container.go, pkg/collector/volumeclaim.go, pkg/collector/volumeclaim_test.go
Resolves https://github.com/open-telemetry/opentelemetry-operator/issues/1281
=> Remove default claims - fixes #1281

internal/config/change_handler.go, internal/config/change_handler_test.go, internal/config/main.go, internal/config/main_test.go, internal/config/options.go
Description: https://github.com/open-telemetry/opentelemetry-operator/pull/1206#issuecomment-1332316819
=> Add change handler to register callbacks

.chloggen/1028-restart-podwatcher.yaml, cmd/otel-allocator/collector/collector.go, cmd/otel-allocator/collector/collector_test.go
Resolves https://github.com/open-telemetry/opentelemetry-operator/issues/1028
Before fix:
```
{"level":"info","ts":1668017421.9970064,"msg":"Starting the Target Allocator"}
{"level":"info","ts":1668017421.9972935,"logger":"allocator","msg":"Unrecognized filter strategy; filtering disabled"}
{"level":"info","ts":1668017422.0179584,"logger":"setup","msg":"Starting server..."}
{"level":"info","ts":1668017422.0202508,"logger":"allocator","msg":"Successfully started a collector pod watcher","component":"opentelemetry-targetallocator"}
{"level":"info","ts":1665127338.1837273,"logger":"allocator","msg":"false","component":"opentelemetry-targetallocator"}
{"level":"info","ts":1665127338.1838017,"logger":"allocator","msg":"Collector pod watch event stopped no …
```
=> [target-allocator] restart pod watcher when no event is found

.chloggen/update-python-metrics-exporter.yaml, pkg/instrumentation/podmutator_test.go, pkg/instrumentation/python.go, pkg/instrumentation/python_test.go, pkg/instrumentation/sdk_test.go, tests/e2e/instrumentation-python-multicontainer/01-assert.yaml, tests/e2e/instrumentation-python-multicontainer/02-assert.yaml, tests/e2e/instrumentation-python/00-install-instrumentation.yaml, tests/e2e/instrumentation-python/01-assert.yaml
Closes https://github.com/open-telemetry/opentelemetry-operator/issues/1168.
Updates the default exporters for python to use `otlp` and `OTEL_EXPORTER_OTLP_[TRACES|METRICS]_PROTOCOL=http/protobuf`
Depends on https://github.com/open-telemetry/opentelemetry-operator/pull/1321
=> Update default python exporters to use OTLP

.chloggen/1298-change-ta-build-proc.yaml, .github/workflows/publish-target-allocator.yaml
Closes #1298
This changes the target allocator image building process to set the versions the same the operator does. This means that when a new release is created, the target allocator will be made using that version tag. This also will have a "main" release like the operator as well.
=> [target-allocator] Change the github action to match the operator

README.md
Related to https://github.com/open-telemetry/opentelemetry-operator/issues/924
Updates the README's Instrumentation object to explicitly set python's OTEL_EXPORTER_OTLP_ENDPOINT value to 4318.  
If we want we can also update the python injection to update any existing OTEL_EXPORTER_OTLP_ENDPOINT value to be `4318` so that this distinction isn't necessary, but I think that change needs some scrutiny to make sure users can still configure anything they want with confidence that we aren't messing with it.
=> [chore] Update Instrumentation example with python env var

.chloggen/1337-fix-routes-openshift.yaml, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/opentelemetrycollector_controller.go
After #1206 , OpenShift routes are supported by the OpenTelemetry Collector Operator.
In upstream, this works because we're installing the OpenShift Routes CRD in the Kubernetes cluster. But, for OpenShift, the creation of routes don't work.
When this manifest is deployed:
```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
name: simplest
spec:
mode: "deployment"
ingress:
type: route
hostname: "example.com"
annotations:
something.com: "true"
route:
termination: "insecure"
config: |
receivers:
otlp:
protocols:
grpc:
exporters:
logging:
service:
pipelines:
traces:
receivers: [otlp]
processors: []
exporters: [logging]
```
This error is logged in the OTEL Collector Operator:
```json
{"level":"error","ts":"2022-12-21T16:32:48.213626Z","msg":"Reconciler …
```
=> [bug_fix] Missing resource from OpenShift Routes prevents them to be deployed in OpenShift clusters

README.md
I struggled to get the target allocator to work, mostly because of the lack of documentation. After reading the sources and talking to some folks (thanks @jaronoff97 and @Aneurysm9), I understood how to get it working and how it works behind the scenes. I tried to record my learnings in a new section as part of the readme, keeping it simple and with end-users in mind.
=> Add basic TA readme documentation

CONTRIBUTING.md
Make sure the dev image has always a new tag so it's deployed.
=> Make sure dev image is always overridden

.chloggen/1383-replace-deperecated-gorilla-dependency.yaml, cmd/otel-allocator/go.mod, cmd/otel-allocator/go.sum, cmd/otel-allocator/server/server.go
Resolves #1352.
This change aims to replace the deprecated `gorilla/mux` with `gin` while maintaining the functionality of current solution.
Note: Due to difference in convention for path variables used by both frameworks (`gorilla/mux` using curly braces, .e.g `/jobs/{job_id}/targets` vs. `gin` using colon e.g. `/jobs/:job_id/targets`), the only change will be in the reported metric label for the jobs path.
Signed-off-by: Matej Gera <matej.gera@coralogix.com>
=> [target-allocator] Replace deprecated `gorilla/mux` dependency with `gin`

.chloggen/allocator-pprof.yaml, cmd/otel-allocator/server/server.go
These are generally useful for tracking down performance issues.
Allocator clients are generally trusted, these shouldn't need to be on a separate endpoint.
=> register pprof endpoints for allocator

hack/install-metrics-server.sh, hack/install-openshift-routes.sh, tests/e2e/daemonset-features/00-add-scc.yaml, tests/e2e/daemonset-features/01-install.yaml, tests/e2e/daemonset-features/02-assert.yaml, tests/e2e/daemonset-features/03-add-sa-collector.yaml, tests/e2e/daemonset-features/03-assert.yaml, tests/e2e/daemonset-features/add-sa-collector.sh, tests/e2e/daemonset-features/add-scc-openshift.sh, tests/e2e/daemonset-features/scc.yaml
Signed-off-by: Israel Blancas <iblancasa@gmail.com>
Fixes #1353
=> [chore] Fix daemonset-features E2E test for OpenShift

README.md
Hello!
I've been very active in the operator project and have taken a greater role in the project with the merging of #1339 and  #1326. In addition to that, I've been part of leading the work for the target allocator and we've seen great adoption of it as a result of our efforts. You can see the [list of issues and PRs i've submitted.](https://github.com/open-telemetry/opentelemetry-operator/pulls?q=author%3Ajaronoff97) I've also been active in responding to people in our community slack for support. I would love to help out in a greater capacity.
cc @open-telemetry/operator-maintainers
=> Promote @jaronoff97 to maintainer

cmd/otel-allocator/server/server_test.go
Signed-off-by: Matej Gera <matej.gera@coralogix.com>
We were occasionally seeing a failure in `TestServer_TargetsHandler/Multiple_entry_target_map_of_same_job_with_label_merge` with the following output:
```
server_test.go:177: 
Error Trace:	/home/runner/work/opentelemetry-operator/opentelemetry-operator/cmd/otel-allocator/server/server_test.go:177
Error:      	Not equal: 
expected: []*target.Item{(*target.Item)(0xc000717d40), (*target.Item)(0xc000717da0)}
actual  : []*target.Item{(*target.Item)(0xc00017a840), (*target.Item)(0xc00017a8a0)}
Diff:
--- Expected
+++ Actual
@@ -1,2 +1,16 @@
([]*target.Item) (len=2) {
+ (*target.Item)({
+  JobName: (string) "",
+  Link: (target.LinkJSON) {
+   Link: (string) ""
+  },
+  TargetURL: ([]string) (len=1) {
+   (string) (len=9) "test-url2"
+  },
+ …
```
=> [target allocator] Fix flaky server test in targets handler

.chloggen/1414-adjust-gin-config.yaml, cmd/otel-allocator/server/server.go
Signed-off-by: Matej Gera <matej.gera@coralogix.com>
This is a follow-up to #1383.
This PR changes the `gin` router configuration to be suitable for production use, namely:
- It sets `gin` to be used in `release` mode (to my surprise, the default was `debug`)
- it opts out of using the default logger middleware. The logging seems rather verbose (logging each request) and the middleware is not using logging format that is consistent with logging format of the rest of the components in `target-allocator`. 
Eventually, it would be nice if we introduced our own logging middleware with formatting consistent with other components, but for now the default one seems noisy and not too useful to me.
cc @kristinapathak
=> [target-allocator] Use `gin` in release mode and without default logger middleware

tests/e2e/instrumentation-dotnet-multicontainer/01-install-app.yaml, tests/e2e/instrumentation-dotnet-multicontainer/02-install-app.yaml, tests/e2e/instrumentation-dotnet/01-install-app.yaml, tests/e2e/instrumentation-java-multicontainer/01-install-app.yaml, tests/e2e/instrumentation-java-multicontainer/02-install-app.yaml, tests/e2e/instrumentation-nodejs-multicontainer/01-install-app.yaml, tests/e2e/instrumentation-nodejs-multicontainer/02-install-app.yaml, tests/e2e/instrumentation-python-multicontainer/01-install-app.yaml, tests/e2e/instrumentation-python-multicontainer/02-install-app.yaml
Kubernetes uses imagePullPolicy: Always for images with latest or no tag, which can trigger docker.com rate limits if one runs the e2e tests too often.
=> [chore] Use tagged images in e2e tests to not trigger docker.com rate limit

README.md
I guess it's my time now to step out from maintainership. I was already away for a while, just lurking around in case something needed someone to break a deadlock, but there are enough maintainers now so this problem won't happen. I also trust that the current maintainers are doing a great job, and I don't deserve to be called a "maintainer" and be compared with you, the ones actually doing the work. 
Thank you for bringing this project forward, it means a lot to me.
=> jpkroehling resigns as maintainer

README.md, cmd/otel-allocator/README.md
Add some documentation for what is required for the Target Allocator to work with Prometheus CRs. Assists with #1316
=> [target-allocator] Improve TargetAllocator README (#1316)

README.md, apis/v1alpha1/instrumentation_types.go, bundle/manifests/opentelemetry.io_instrumentations.yaml, config/crd/bases/opentelemetry.io_instrumentations.yaml, docs/api.md
Updates the sampler and propagation documentation to explicitly state which environment variables get set when this fields are used.  Added links to otel specification.  For propagators, added list of valid values.
I updated the docs directly, but I get the sense they are auto-generated.  I couldn't figure out what the root source of truth is, so if I've updated stuff incorrectly please point me in the right direction.
Related to https://github.com/open-telemetry/opentelemetry.io/pull/2253
=> [docs] Update sampler and propagation docs

Makefile, hack/modify-test-images.sh
Opt for using `gsed` instead of the MacOS version of `sed`, which is incompatible with certain flags that work on Linux.
=> [chore] Fix `make` on MacOS by using `gsed`

.chloggen/1492-fix-stateful-set-reconcile.yaml, pkg/collector/reconcile/statefulset.go, pkg/collector/reconcile/statefulset_test.go, pkg/collector/statefulset.go, pkg/collector/volumeclaim.go, pkg/collector/volumeclaim_test.go, tests/e2e/statefulset-features/01-assert.yaml, tests/e2e/statefulset-features/01-update-volume-claim-templates.yaml
Fixes #1491.
Since `volumeClaimTemplates` is an immutable field, this PR provides a solution based on recreation of the stateful set when a change in this field is detected. This is analogous to how other immutable field (selector) is handled.
In addition, this PR simplifies the `VolumeClaimTemplates` method and removes unnecessary parameter.
A unit test has been added. This has also been tested manually.
=> Recreate stateful set on change in immutable field `volumeClaimTemplates`

CONTRIBUTING.md, cmd/otel-allocator/README.md
Related to changes introduced in https://github.com/open-telemetry/opentelemetry-operator/pull/1540.
Update cluster role with rules for `endpointslices`.
Add also small clarification on usage of `[chore]` tag in PR titles.
=> [chore] [target-allocator] Update docs with correct `ClusterRole` after latest release

Makefile
Use non-default name for the `kind` cluster and make it configurable. Often, when testing locally, the default cluster (`kind`) will already exist, making the the operation fail.
=> [chore] Use non-default kind cluster name

autoinstrumentation/dotnet/Dockerfile, autoinstrumentation/java/Dockerfile, autoinstrumentation/nodejs/Dockerfile, autoinstrumentation/python/Dockerfile
Description:
Recently, my team and I wanted to build a minimal Docker image to be used for operator auto-instrumentation. We tried to create an image from [scratch](https://hub.docker.com/_/scratch) that only contained our instrumentation libraries, but we found out that the Linux [cp command is required for auto-instrumentation container injection](https://github.com/open-telemetry/opentelemetry-operator/search?q=cp).
This PR is only adding comments to notify other users about this undocumented requirement.
=> Update Dockerfile comments for undocumented requirement

main.go
=> Notify users when webhooks are disabled

README.md
Followup #1465 
Addresses https://github.com/open-telemetry/opentelemetry-operator/issues/1465#issuecomment-1465896037
=> Add a note that dotnet autoinstrumentation defaults to http/protobuf

tests/e2e/autoscale/00-install.yaml, tests/e2e/autoscale/02-install.yaml, tests/e2e/autoscale/03-verify-simplest-set-collector-hpa-metrics.yaml
We've been having trouble with the autoscale test in the helm chart CI and I believe I have narrowed down the issue.  
The core problem is that the `e2e/autoscale` test relies on scaling up the collector under load and then scaling down when the load disappears.  We don't want it scaling up early and we want it to scale down reliably once the load disappears.  Based on my testing today the proposed changes should make this sequence consitent.
These changes have 2 goals:
1. ensure the collector does not scale up until tracegen has started sending it telemetry
2. ensure the collector scales down once the load disappears.
I achieved these goals by modifying the initial `autoscaler` values of the `simplest-set-utilization` to high and long values.  With a target CPU of 99 and a …
=> [HPA/e2e] Increase e2e/autoscale reliability

.chloggen/bump-nodejs-versions.yaml, autoinstrumentation/nodejs/package.json
Replacement for #1625, this only bumps all versions in the nodejs auto instrumentation to latest.
=> Bump dependencies in Node.JS autoinstrumentation to latest

.chloggen/fix_targetallocator_update-scrape-configs.yaml, cmd/otel-allocator/target/discovery.go, cmd/otel-allocator/target/discovery_test.go, cmd/otel-allocator/target/testdata/test.yaml
Only take scrape configs from the most recently applied config, and only save them if we've successfully updated. As a result, we now correctly get rid of targets after a ServiceMonitor or PodMonitor is deleted, fixing #1415.
I've also fixed an issue where we would overwrite the job to scrapeConfig mapping even if the actual update failed - the test for this was incorrect, as it didn't deepcopy the mapping, and basically asserted that two references to the same map were equal.
I've modified the existing discovery test to look at scrape config updates, and added another job to the test data to make sure it gets deleted after an update.
I've also done a proper manual e2e test on this, and it worked as expected.
=> [target-allocator] fix updating scrape configs

.chloggen/add-featuregate-for-dotnet.yaml, README.md, main.go, pkg/featuregate/featuregate.go, pkg/instrumentation/podmutator.go, pkg/instrumentation/podmutator_test.go, pkg/instrumentation/upgrade/upgrade.go
This PR puts the dotnet instrumentation behind a feature gate named `operator.autoinstrumentation.dotnet`.  This feature gate is enabled by default, but operator managers could disable it if they do not want Instrumentation to be able to inject dotnet instrumentation.
I'm using dotnet as the guinea pig, but if the pattern is good I'll submit PRs for the other languages as well.
=> [pkg/instrumentation] Add feature gate for dotnet instrumentation

.chloggen/1672-bump-otel-net-auto-to-0.7.0.yaml, versions.txt
Fixes #1672 
Can be merged after #1673
=> Bump OpenTelemetry .NET Automatic Instrumentation to 0.7.0 - part 2/2

pkg/instrumentation/podmutator.go
This PR cleans up the dotnet featuregate implementation by ensuring the log and event are only written if the `instr` pointer is not nil and the feature gate is disabled.  The unit tests didn't catch this because to don't do any mocking/expecting of the recorder or logging, I found it while working on the Go autoinstrumentation support.
=> [instrumentation] Prevent event and log for disabled instrumentation when instr is nil

.chloggen/python-featuregate.yaml, README.md, pkg/featuregate/featuregate.go, pkg/instrumentation/podmutator.go, pkg/instrumentation/podmutator_test.go, pkg/instrumentation/upgrade/upgrade.go
This PR puts the python instrumentation behind a feature gate named `operator.autoinstrumentation.python`.  This feature gate is enabled by default, but operator managers could disable it if they do not want Instrumentation to be able to inject python instrumentation.
=> [pkg/instrumentation] Add featuregate to python instrumentation

.chloggen/java-featuregate.yaml, README.md, pkg/featuregate/featuregate.go, pkg/instrumentation/podmutator.go, pkg/instrumentation/podmutator_test.go, pkg/instrumentation/upgrade/upgrade.go
This PR puts the java instrumentation behind a feature gate named `operator.autoinstrumentation.java`.  This feature gate is enabled by default, but operator managers could disable it if they do not want Instrumentation to be able to inject java instrumentation.
=> [pkg/instrumentation] Add featuregate to java instrumentation

.chloggen/otelallocator-flag.yaml, README.md, pkg/collector/reconcile/config_replace.go, pkg/collector/reconcile/config_replace_test.go, pkg/collector/reconcile/configmap.go, pkg/collector/reconcile/configmap_test.go, pkg/featuregate/featuregate.go, pkg/targetallocator/adapters/config_to_prom_config.go, pkg/targetallocator/adapters/config_to_prom_config_test.go
These are changes from #1557, rebased on main and using the feature flag machinery from #1619.
One addition I've made is clearing the scrape configs in prometheus receiver itself. This doesn't actually change the semantics, but it makes it clearer what is actually going on. The change is in a separate commit here: https://github.com/open-telemetry/opentelemetry-operator/commit/15ac0ce91e3e34144a3609f76cd0e3cb9246405d.
I've done some manual E2E testing on these changes and everything worked as expected.
Fixes #1581
=> Add feature flag for target allocator config addition

.chloggen/nodejs-featuregate.yaml, README.md, pkg/featuregate/featuregate.go, pkg/instrumentation/podmutator.go, pkg/instrumentation/podmutator_test.go, pkg/instrumentation/upgrade/upgrade.go
This PR puts the NodeJS instrumentation behind a feature gate named `operator.autoinstrumentation.nodejs`.  This feature gate is enabled by default, but operator managers could disable it if they do not want Instrumentation to be able to inject NodeJS instrumentation.
=> [pkg/instrumentation] Add featuregate to nodejs instrumentation

.github/workflows/reusable-operator-hub-release.yaml, README.md, RELEASE.md
Hello!
I would like top formally request to be made an Approver for opentelemetry-operator. I have been an active contributor to this repo since December 2022 helping out in issues, PR reviews, and [contributing PRs](https://github.com/open-telemetry/opentelemetry-operator/pulls/TylerHelmuth), with a focus on our Instrumentation capabilities. I also re-organized and filled in [opentelemetry.io's Operator auto-instrumentation docs](https://opentelemetry.io/docs/k8s-operator/automatic/).
I would like to continue driving progress in this space by helping out in a formal capacity.
/cc @open-telemetry/operator-maintainers
=> Promote @TylerHelmuth to Approver

.github/workflows/publish-autoinstrumentation-dotnet.yaml, .github/workflows/publish-autoinstrumentation-java.yaml, .github/workflows/publish-autoinstrumentation-nodejs.yaml, .github/workflows/publish-autoinstrumentation-python.yaml, .github/workflows/publish-images.yaml, .github/workflows/publish-operator-opamp-bridge.yaml, .github/workflows/publish-target-allocator.yaml
This PR makes it so that we only attempt github action logins on a main push to the repo rather than on every PR which was causing failures due to missing credentials.
=> [chore] Only Login on main push

.chloggen/fix-go-release.yaml, .github/workflows/publish-images.yaml, tests/e2e/instrumentation-go/01-install-app.yaml
Fixes https://github.com/open-telemetry/opentelemetry-operator/issues/1756.
While testing I noticed that the `productcatalogservice` containers wasn't actually starting because it was missing some env vars.  This didn't affect the test bc we don't actually check if the instrumentation is working, only that the instrumentation could be injected, but I figured I'd clean things up anyways.
=> [instrumentation] Fix issue where default Go auto-instrumentation version was not being used in our release operator image.

autoinstrumentation/python/Dockerfile
Switch to building the python requirements on the `3.11` image instead of the `3.11-alpine` image.  This ensures that the requirements are built using all necessary python dependencies.
Closes https://github.com/open-telemetry/opentelemetry-operator/issues/1515
=> [instrumentation] Switch to python:3.11 image

.chloggen/fix_validate-ta-config.yaml, apis/v1alpha1/opentelemetrycollector_webhook.go, cmd/otel-allocator/config/config.go, cmd/otel-allocator/config/config_test.go, cmd/otel-allocator/main.go, cmd/otel-allocator/target/discovery.go, cmd/otel-allocator/target/discovery_test.go, pkg/collector/reconcile/config_replace.go, pkg/collector/reconcile/configmap.go, pkg/targetallocator/adapters/config_to_prom_config.go, pkg/targetallocator/adapters/config_to_prom_config_test.go
In a follow-up to #1688, improve validation for prometheus receiver configuration. This turned out to be more complicated than expected, so I'd like some more eyes to verify I haven't missed anything.
The validation logic for the prometheus receiver config itself is:
* if target allocator is not enabled on the Collector CR, prometheus config under the `config` key is required
* if target allocator is enabled
- either `config` has to exist to inject http_sd_configs, or `target_allocator` needs to exist 
- if additionally target allocator rewrite is enabled, nothing is required
However, I also noticed that target allocator itself doesn't correctly validate its configuration. For example, it's possible to pass an empty Prometheus config, but this will cause a crash in the targetDiscoverer. …
=> Improve config validation for prometheus receiver and target allocator

.chloggen/bump-oteljs-versions.yaml, autoinstrumentation/nodejs/package.json
Bumps all the js packages to their latest versions.
=> [instrumentation] Bump js packages to 1.13.0/0.39.1

.chloggen/1811-fix-empty-scrape-interval.yaml, cmd/otel-allocator/watcher/promOperator.go
Resolves #1811.
After recent changes (https://github.com/open-telemetry/opentelemetry-operator/pull/1653) to update some TA dependencies (Prometheus Operator and Prometheus), the Prometheus CR watcher's method `LoadConfig` started to fail. This has been traced to the fact that we have previously removed the default scrape interval from the config passed to the method for config generation. This change simply reinstates the default to fix unmarshalling again.
Although for now this has been tested manually, ideally we'll have this tested as part of the unit tests, but we're missing some more changes in order to introduce unit tests. This is part of work in https://github.com/open-telemetry/opentelemetry-operator/pull/1710 which I intend to finish and update soon.
=> [target allocator] Re-add default global scrape interval in Promethues CR watcher configuration.

README.md
Updates the README to call out the elevated permission requirements of the Go auto-instrumentation sidecar.  
Related to https://github.com/open-telemetry/opentelemetry-operator/issues/1846
=> [autoinstrumentation/go] List permission requirements

.chloggen/bump-nodejs.yaml, autoinstrumentation/nodejs/package.json
Bumps the node js packages to 1.14.0/0.40.0 and all corresponding contrib bumps.
=> [autoinstrumentation/nodejs] Bump js packages

.github/workflows/e2e.yaml, .github/workflows/scorecard.yaml, hack/install-kuttl.sh, kind-1.19.yaml, kind-1.20.yaml, kind-1.21.yaml, kind-1.22.yaml, kind-1.23.yaml, kind-1.24.yaml, kind-1.25.yaml, kind-1.26.yaml, kind-1.27.yaml
Up until now we depended on the `kind` version shipped by Github, which opened us up to unexpected breakage whenever they upgraded. This has happened recently with an upgrade from `0.19.0` to `0.20.0`.
This change:
- explicitly sets the kind version in CI
- updates Node images for kind 0.20.0
- uses kind 0.17.0 to run tests for K8s <1.21, which kind 0.20.0 doesn't support out of the box
- updates kuttl to the latest released version
=> Explicitly set kind version when running tests in CI

cmd/otel-allocator/README.md
Kubernetes accepted the manifest when copy / pasting from the docs, but ended up with verb `watch"`. Couldn't understand why target allocator failed. Simple typo in doc
=> target-allocator : Fix typo in documentation

.chloggen/targetallocator-reject-no-targets.yaml, apis/v1alpha1/opentelemetrycollector_webhook.go, apis/v1alpha1/opentelemetrycollector_webhook_test.go, pkg/targetallocator/adapters/config_to_prom_config.go, pkg/targetallocator/adapters/config_to_prom_config_test.go
Fixes #1859. I've also extracted some common logic in the adapters package to a separate function.
=> Only admit configurations where Target Allocator has targets

tests/e2e-openshift/Dockerfile
We will be running end-to-end tests for OpenTelemetry Operator in our [OpenShift release](https://github.com/openshift/release) using Prow CI jobs. These jobs will encompass various cluster configurations, and the Dockerfile will containerize the tests for execution within the Prow CI.
=> [chore] Add Dockerfile for OpenShift containerized test execution on Prow CI.

.chloggen/fix_sampler-type-required.yaml, apis/v1alpha1/instrumentation_webhook.go, apis/v1alpha1/instrumentation_webhook_test.go
Fixes #1886. I've also added an E2E test with a minimal configuration to ensure optional attributes stay optional.
=> Fix `.sampler.type` being incorrectly required for Instrumentation

README.md
Fixes minimal example for target allocator when using feature flag `operator.collector.rewritetargetallocator`. 
Fixes #1891
=> Fixed minimal target allocator example in readme

.github/workflows/continuous-integration.yaml, Makefile
Golangci-lint output can vary significantly between versions, and each project uses a different one. It makes for a better local dev experience if we explicitly install the version we want, just as we do with other local tools.
I've also made the CI use this for consistency's sake.
=> Install golangci-lint in the local tools dir

pkg/targetallocator/annotations.go, pkg/targetallocator/annotations_test.go, tests/e2e/smoke-targetallocator/00-assert.yaml, tests/e2e/smoke-targetallocator/00-install.yaml, tests/e2e/smoke-targetallocator/01-change-ta-config.yaml
Fix a critical issue in #1889. We were reading the configuration string from the wrong ConfigMap field and not checking the result, and therefore always adding the hash of the empty string.
You might wonder how it is that the E2E test passes even though the hash doesn't change. In this specific case, the spec is modified by enabling PrometheusCR, which actually adds a command line argument to the target allocator, and thus causes it to be restarted regardless. I've updated the test to account for this.
I've made the unit test for this more specific as well, so we check if we have the hash of the right value, not just that it's syntactically correct.
Finally, I've actually tested it manually as well, and it does work.
=> [target allocator] Fix Target Allocator config reload

tests/e2e/instrumentation-apache-multicontainer/00-install-collector.yaml, tests/e2e/instrumentation-apache-multicontainer/00-install-instrumentation.yaml, tests/e2e/instrumentation-apache-multicontainer/01-assert.yaml, tests/e2e/instrumentation-apache-multicontainer/01-install-app.yaml, tests/e2e/instrumentation-apache-multicontainer/02-assert.yaml, tests/e2e/instrumentation-apache-multicontainer/02-install-app.yaml
Temporarily skips the `instrumentation-apache-multicontainer` e2e test.
Related to https://github.com/open-telemetry/opentelemetry-operator/issues/1936
=> [chore] Skip flaky test instrumentation-apache-multicontainer

.github/workflows/reusable-operator-hub-release.yaml, README.md, RELEASE.md
Title! This PR adds Mikołaj Świątek as an approver for the project. When this is merged, I'll open a PR in the community repo so he can be added to the otel team. Looking for @open-telemetry/operator-approvers and @open-telemetry/operator-maintainers to add their support for this.
Looking through Mikołaj's history for PRs and reviews, he's an indispensable member of the team who has vastly improved the operator's QOL and velocity. I'm sure with him as an approver we will continue having high standards for code reviews!
=> Add Mikołaj Świątek as an approver

.chloggen/1954-remove-legacy-port.yaml, pkg/collector/adapters/config_to_ports_test.go, pkg/collector/parser/receiver_otlp.go, pkg/collector/parser/receiver_otlp_test.go, tests/e2e/ingress/00-assert.yaml, tests/e2e/managed-reconcile/00-assert.yaml, tests/e2e/managed-reconcile/01-assert.yaml, tests/e2e/managed-reconcile/02-assert.yaml, tests/e2e/smoke-init-containers/00-assert.yaml, tests/e2e/smoke-simplest/00-assert.yaml
Resolves #1954 
The legacy OTLP HTTP port was removed from the collector in Feb 2022 - https://github.com/open-telemetry/opentelemetry-collector/pull/4916#issue-1148683041
=> Remove legacy OTLP HTTP port

.github/dependabot.yml
=> Add dependabot rules for target allocator and opamp-bridge Dockerfiles

.chloggen/1987-adding-support-for-sidecar-containers.yaml, apis/v1alpha1/opentelemetrycollector_types.go, apis/v1alpha1/opentelemetrycollector_webhook.go, apis/v1alpha1/opentelemetrycollector_webhook_test.go, apis/v1alpha1/zz_generated.deepcopy.go, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, bundle/manifests/opentelemetry.io_opentelemetrycollectors.yaml, config/crd/bases/opentelemetry.io_opentelemetrycollectors.yaml, config/manager/kustomization.yaml, docs/api.md, internal/manifests/collector/daemonset.go, internal/manifests/collector/daemonset_test.go, internal/manifests/collector/deployment.go, internal/manifests/collector/deployment_test.go, internal/manifests/collector/statefulset.go, internal/manifests/collector/statefulset_test.go
Adds `AdditionalContainers` field to the Collector spec to allow configuring sidecars to run along side the collector container in the pod. 
This is required for a use case I have where the company I'm shipping metrics too requires using their agent to ship metrics into their cloud. 
This solves #1987
=> Adding Additional Containers to the Collector spec

.chloggen/servicename-daemonset.yaml, pkg/instrumentation/sdk.go
Daemonsets can be instrumented so the generated servicename should use their name for better discoverability.
Related issue:  https://github.com/open-telemetry/opentelemetry-operator/issues/2015
=> get servicename from daemonset if possible

.chloggen/route-grpc.yaml, internal/manifests/collector/route.go, internal/manifests/collector/service.go, internal/manifests/collector/service_test.go
Updates #1969 
The appProtocol set to h2c should work for secure (TLS) and insecure routes. 
Some test yamls: 
```yaml
kubectl apply -f - <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
name: certs
data:
ca.crt: |
-----BEGIN CERTIFICATE-----
MIIDNjCCAh4CCQDm8/gmxPra7zANBgkqhkiG9w0BAQsFADBdMQswCQYDVQQGEwJB
VTESMBAGA1UECAwJQXVzdHJhbGlhMQ8wDQYDVQQHDAZTeWRuZXkxEjAQBgNVBAoM
CU15T3JnTmFtZTEVMBMGA1UEAwwMTXlDb21tb25OYW1lMB4XDTIyMDgwMzA0NDQ0
OFoXDTMyMDczMTA0NDQ0OFowXTELMAkGA1UEBhMCQVUxEjAQBgNVBAgMCUF1c3Ry
YWxpYTEPMA0GA1UEBwwGU3lkbmV5MRIwEAYDVQQKDAlNeU9yZ05hbWUxFTATBgNV
BAMMDE15Q29tbW9uTmFtZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
AKDQxV8fMvsl4YhMiY3EiT0ylKQ0VkUwvWE4yfem6LFYaZa0fOe1zc3V9DXmcH9A
PXXa+XwlK7xfXSddGoD7XfxLKdU8FiU+bXs/pEeRPQ+5oraInTcAQ265HXkPmiiQ …
```
=> Make OpenShift Route work with gRPC receivers

.github/workflows/e2e.yaml
Looks like we accidentally combined e2e and upgrade which meant upgrade never ran and e2e ran twice
=> [chore] Fix ci runner

.chloggen/fix-otel-collector-service-reconciliation.yaml, pkg/collector/reconcile/service.go, pkg/collector/reconcile/service_test.go
This PR fixes #2061 and adds a unit test for that case.
=> Fixes reconciling Internal Traffic Policy changes and adds test

autoinstrumentation/dotnet/Dockerfile
Towards #1849
- includes musl version
- remove redundant, zip files from final image
- execute commands in a batch, to reduce number of layers in final image
Tested locally with defined spec->dotnet->image
```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
name: my-instrumentation
spec:
exporter:
endpoint: http://otel-collector:4317
propagators:
- tracecontext
- baggage
- b3
sampler:
type: parentbased_traceidratio
argument: "0.25"
python:
env:
- name: OTEL_EXPORTER_OTLP_ENDPOINT
value: http://otel-collector:4318
dotnet:
image: local-auto:dotnet
env:
- name: OTEL_EXPORTER_OTLP_ENDPOINT
value: http://otel-collector:4318
```
By application hosted on alpine linux. with manually redefined environmental variable (operator is not injecting variable if it is already in …
=> .NET auto-instrumentation include musl in docker image

.github/workflows/continuous-integration.yaml, .github/workflows/e2e.yaml, .github/workflows/release.yaml, .github/workflows/scorecard.yaml
This is a defensive PR to force a minimum go version used in gha workflows. The latest patch version contains security fixes.
=> [chore] Update go version used in workflows

.chloggen/bump-go-autoinstrumentation.yaml, tests/e2e-instrumentation/instrumentation-go/02-assert.yaml, versions.txt
https://github.com/open-telemetry/opentelemetry-go-instrumentation/releases/tag/v0.3.0-alpha
=> [autoinstrumentation] bump go autoinstrumentation to 0.3.0-alpha

.chloggen/feat_ta-cliconfig.yaml, cmd/otel-allocator/config/config.go, cmd/otel-allocator/config/config_test.go, cmd/otel-allocator/config/flags.go, cmd/otel-allocator/config/flags_test.go, cmd/otel-allocator/main.go, cmd/otel-allocator/server/bench_test.go, cmd/otel-allocator/server/server.go, cmd/otel-allocator/server/server_test.go, cmd/otel-allocator/target/discovery_test.go, cmd/otel-allocator/watcher/file.go, cmd/otel-allocator/watcher/promOperator.go
TargetAllocator config is internally (rather arbitrarily) split into config from cli, contained in the `CLIConf` struct, and config loaded from the config file, contained in the `Config` struct. This change moves all configuration attributes to the latter, and explicitly gives the CLI arguments higher priority.
I've also moved the flag arguments into an explicit flag set and added tests for it.
Resolves #2129.
=> Refactor target allocator config handling

.chloggen/proxy.yaml, go.mod, go.sum, internal/manifests/collector/container.go, internal/manifests/collector/container_test.go, internal/manifests/targetallocator/container.go, internal/manifests/targetallocator/container_test.go
For more details see https://github.com/jaegertracing/jaeger-operator/pull/2330 and https://github.com/jaegertracing/jaeger/pull/4769
=> Propagate proxy env vars

.chloggen/discoverymanager_metrics.yaml, cmd/otel-allocator/main.go
This adds the following metrics:
`prometheus_sd_failed_configs`
`prometheus_sd_discovered_targets`
`prometheus_sd_received_updates_total`
`prometheus_sd_updates_delayed_total`
`prometheus_sd_updates_total`
I was trying to profile the target allocator in a busy cluster, and would've found these very useful. I have tested manually that this works, but haven't found a reasonable way to unit test it.
Resolves #2170
=> Enable discovery manager metrics in target allocator

.golangci.yaml
We were using configuration for depguard v1, but golangci-lint 1.54 ships depguard v2.
Note: This was failing on my local machine, but not in CI, which was confusing. I believe the CI was using cached values somehow. I deleted the golangci-lint cache manually and got the same failure I did locally on a job that succeeded with the cache present: https://github.com/open-telemetry/opentelemetry-operator/actions/runs/6389543772/job/17347446252
=> Fix depguard linter configuration

.github/workflows/publish-operator-bundle.yaml
Updates https://github.com/open-telemetry/opentelemetry-operator/issues/2001
=> Change GHCR bundle image to fix publish issues

.github/workflows/publish-autoinstrumentation-java.yaml, .github/workflows/publish-autoinstrumentation-nodejs.yaml, .github/workflows/publish-autoinstrumentation-python.yaml, autoinstrumentation/nodejs/Dockerfile
=> [chore] Publish IBM P/Z images for those autoinstrumentation images where it is supported

tests/instrumentation-e2e-apps/apache-httpd/Dockerfile
Related to #2073.
Changed the base image to use the glibc version and not musl (not supported).
=> [chore] Change the base image to use the glibc version and not the musl version of test image

.github/workflows/publish-autoinstrumentation-nodejs.yaml, autoinstrumentation/nodejs/Dockerfile
Revert the change done by bumping the NodeJS version for 0.41.1 NodeJS autoinstrumentation.
**Link to tracking Issue:** #2236
=> [chore] Revert change in NodeJS autoinstrumentation base image for 0.41.1

.chloggen/ta-reload-beta.yaml, README.md, internal/manifests/collector/config_replace_test.go, internal/manifests/collector/configmap_test.go, internal/manifests/collector/testdata/config_expected_targetallocator.yaml, internal/manifests/collector/testdata/http_sd_config_ta_test.yaml, pkg/featuregate/featuregate.go, tests/e2e/smoke-targetallocator/00-assert.yaml
Move the `operator.collector.rewritetargetallocator` flag to `Beta`, enabling it by default.
**Link to tracking Issue:** #2208
**Testing:**
Converted existing tests for both the flag-enabled and flag-disabled cases. Added some unit tests to check the basic rewrite case. Also added a check for the content of the created ConfigMap in E2e tests.
Reflected the fact that this is now enabled by default in the main README.
=> Enable Target Allocator Rewrite by default

.chloggen/ta_update-rate-limit.yaml, cmd/otel-allocator/watcher/promOperator.go, cmd/otel-allocator/watcher/promOperator_test.go
Limit the rate on updates to scrape configs. The idea and code are very similar to what Prometheus' Service Discovery manager does: https://github.com/prometheus/prometheus/blob/79be1b835789d7c3fde2a907003a8799c308733f/discovery/manager.go#L341. The end result is that we emit events about changes to Prometheus CRs at most every 5 seconds.
This should help with #1544
=> Add rate limiting for scrape config updates

.chloggen/bug-fix-labeling-process.yaml, internal/manifests/collector/labels.go, internal/manifests/collector/labels_test.go, tests/e2e/smoke-pod-labels/00-assert.yaml, tests/e2e/smoke-pod-labels/00-install.yaml
Fixed the labeling process which was broken at the moment to capture the current image tag when the users set the sha256 reference.
resolves #1982 
Created a test using an image being declared with a sha256 and checked if there was a label with only the version number. 
=> Fixed Labels with sha256 image ref

Makefile, hack/install-targetallocator-prometheus-crds.sh, hack/modify-test-images.sh, tests/e2e/targetallocator-prometheuscr/00-assert.yaml, tests/e2e/targetallocator-prometheuscr/00-install.yaml, tests/e2e/targetallocator-prometheuscr/01-assert.yaml, tests/e2e/targetallocator-prometheuscr/01-install.yaml
Adds an E2E test verifying collecting metrics defined by a ServiceMonitor using the target allocator.
This is done by:
* adding a ServiceMonitor covering the collector's own metrics port
* scraping the metrics with Prometheus receive,  target allocator enabled
* exporting the metrics on a different port via Prometheus exporter
* running a Job which curls the above endpoint and checks that a particular metric is present
This is a little bit convoluted, but I haven't figured out how to make it any simpler. The Job approach actually ends up working well with kuttl, as we end up just needing to check the status of a K8s resource.
**Link to tracking Issue:** #2262 
Note: This will fail before #2273 is merged. The intent of this test is to catch issues like #2262 in the future.
=> Add E2E test for metrics collection using Prometheus CRs

.chloggen/update-opamp-bridge-spec.yaml, cmd/operator-opamp-bridge/agent/agent.go, cmd/operator-opamp-bridge/agent/agent_test.go, cmd/operator-opamp-bridge/agent/collector_key.go, cmd/operator-opamp-bridge/agent/collector_key_test.go, cmd/operator-opamp-bridge/agent/testdata/basic.yaml, cmd/operator-opamp-bridge/agent/testdata/invalid.yaml, cmd/operator-opamp-bridge/agent/testdata/updated.yaml, cmd/operator-opamp-bridge/operator/client.go, cmd/operator-opamp-bridge/operator/client_test.go, cmd/operator-opamp-bridge/operator/testdata/collector.yaml, cmd/operator-opamp-bridge/operator/testdata/invalid-collector.yaml, cmd/operator-opamp-bridge/operator/testdata/reporting-collector.yaml, cmd/operator-opamp-bridge/operator/testdata/updated-collector.yaml
Right now, the bridge doesn't entirely conform to the design, it didn't support an annotation for reporting on managed instances. The naming structure also didn't match the design here:
> As part of the Bridge’s AgentToServer message, the effective configuration reported will be a map of a collector’s namespaced name `(<namespace>/<otelcol-name>)` to that collector’s CRD resource. This will let the server know what should exist in the cluster. This data can be used to enrich information received from the collector’s OpAMP extension by joining on the collector’s pool name.
Further, we also weren't allowing servers to send full CRDs, only specs (another inaccuracy)
**Link to tracking Issue:** #2131 
**Testing:** Tests were updated to reflect the changes
=> Update OpAMP Bridge to comply with its design

apis/v1alpha1/opampbridge_webhook.go, apis/v1alpha1/opampbridge_webhook_test.go, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, config/webhook/manifests.yaml, controllers/suite_test.go, main.go
This PR updates the OpAMPBridge Webhook code to make it consistent with the changes that are made in Collector webhook as a part of #2210. 
**Link to tracking Issue:** NA
**Testing:** Tested locally. 
**Documentation:** NA
=> [operator-opamp-bridge][chore]: Refactor OpAMPBridge Webhook

.chloggen/target-allocator-container-port.yaml, internal/manifests/targetallocator/container.go, internal/manifests/targetallocator/container_test.go, internal/manifests/targetallocator/service.go, internal/manifests/targetallocator/service_test.go
**Description:** Specified containerport in target allocator container
**Link to tracking Issue:** #2312
**Testing:** Unit Testing
=> Declare ContainerPort for Target Allocator

.github/workflows/e2e.yaml, .github/workflows/publish-images.yaml, Dockerfile, Makefile
Cross-compile the manager binary on the host and copy the appropriate binary into the container during the build. This makes image building *much* faster, as we don't need to rely on emulation via QEMU.
I've also removed our local toolchain's dependency on buildx while I was at it, as it's not strictly necessary.
Looks like we could build the binaries in a matrix job, but given that they take around 15 minutes without cache, I don't think it's worth it to mess around with artifacts.
**Issue**: #2295 
**Testing:**
Temporarily made the build happen for this PR, and it worked fine.
=> Build manager on the host

.github/workflows/publish-operator-opamp-bridge.yaml, Makefile, cmd/operator-opamp-bridge/Dockerfile
#2293  for the opamp bridge. The changes are almost identical.
**Link to Tracking Issue**: #2295 
**Testing:**
Temporarily made the build happen for this PR, and it worked fine.
=> Build opamp-bridge on the host

.chloggen/truncate-pod-label.yaml, pkg/sidecar/pod.go, pkg/sidecar/pod_test.go
Truncate `sidecar.opentelemetry.io/injected` sidecar pod label to 63 characters since Kubernetes labels must be 63 characters or less.
**Link to tracking Issue:**
resolves #1031
**Testing:**
Tested with a unit test in `pod_test.go`.
=> fix(operator): truncate sidecar pod injected label to 63 chars

.chloggen/allocator-affinity.yaml, apis/v1alpha1/opentelemetrycollector_types.go, apis/v1alpha1/zz_generated.deepcopy.go, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, bundle/manifests/opentelemetry.io_opentelemetrycollectors.yaml, config/crd/bases/opentelemetry.io_opentelemetrycollectors.yaml, docs/api.md, internal/manifests/targetallocator/deployment.go, internal/manifests/targetallocator/deployment_test.go, tests/e2e/targetallocator-features/00-assert.yaml, tests/e2e/targetallocator-features/00-install.yaml
Add target allocator affinity configuration
#2263 
I've added additional manifest assertions, if this not how it should be done, please let me know :)
=> Add target allocator affinity configuration

.chloggen/related_images_env_vars.yaml, main.go
For disconnected environments, various tools expect the image location to be set in RELATED_IMAGE_ environment variables:
https://redhat-connect.gitbook.io/certified-operator-guide/troubleshooting-and-resources/offline-enabled-operators#golang-operators
https://docs.openshift.com/container-platform/4.14/operators/operator_sdk/osdk-generating-csvs.html#olm-enabling-operator-for-restricted-network_osdk-generating-csvs
This change allows setting the image locations with the RELATED_IMAGE_ environment variables. It's fully backwards compatible, and the precedence is: flag > env var > default value.
Resolves #2326
I tested the change locally, …
=> Support configuring images via RELATED_IMAGE_ environment variables

.github/dependabot.yml
Right now it opens 4 PRs for the same module, which is annoying.
=> Add otel sdk group to dependabot config

.chloggen/disable-hot-reload.yaml, cmd/otel-allocator/config/config.go, cmd/otel-allocator/config/flags.go, cmd/otel-allocator/config/flags_test.go, cmd/otel-allocator/main.go
Added a flag to control configuration hot reloading in target allocator. The flag is disabled by default, and the functionality is hence considered deprecated and slated for removal in an upcoming release.
I could've done an official feature flag, but the target allocator doesn't have support for feature flags, and I don't think it's necessary to add it just for this.
**Link to tracking Issue:** #2032
**Testing:**
Added a unit test for the flag.
=> Disable configuration hot reload in target allocator

tests/e2e-instrumentation/instrumentation-apache-httpd/00-install-collector.yaml, tests/e2e-instrumentation/instrumentation-apache-httpd/01-install-app.yaml
**Testing:**
```
$ kuttl test --test=instrumentation-apache-httpd tests/e2e-instrumentation/
2023/11/06 12:30:23 kutt-test config testdirs is overridden with args: [ tests/e2e-instrumentation/ ]
=== RUN   kuttl
harness.go:462: starting setup
harness.go:252: running tests using configured kubeconfig.
harness.go:275: Successful connection to cluster at: https://api.REDACTED:6443
harness.go:360: running tests
harness.go:73: going to run test suite with timeout of 150 seconds for each step
harness.go:372: testsuite: tests/e2e-instrumentation/ has 17 tests
=== RUN   kuttl/harness
=== RUN   kuttl/harness/instrumentation-apache-httpd
=== PAUSE kuttl/harness/instrumentation-apache-httpd
=== CONT  kuttl/harness/instrumentation-apache-httpd
logger.go:42: 12:30:26 | instrumentation-apache-httpd | …
```
=> [Chore] Fix test instrumentation-apache-httpd to work on OpenShift.

bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, config/samples/kustomization.yaml
Resolves the following warning from the scorecard tests:
```
Warning: Value opentelemetry.io/v1alpha1, Kind=OpAMPBridge: provided API should have an example annotation
```
-
-
-
=> Add OpAMP example to CSV

.chloggen/ta_really-consistent-hashing.yaml, cmd/otel-allocator/allocation/allocatortest.go, cmd/otel-allocator/allocation/consistent_hashing.go, cmd/otel-allocator/allocation/consistent_hashing_test.go
For the consistent-hashing strategy, base target allocation decisions only on the target url. This way, for a given collector count, we always assign targets with the same url to the same collector. Before, this decision was based on all target labels, and targets could therefore be moved between collectors even if collector count stayed the same.
**Link to tracking Issue:** #2280 
**Testing:**
Tested this in a ~500 Node production cluster in addition to the unit tests. It behaved as expected and over time resulted in an average drop of around 10% in CPU and memory usage with around 4000 scrape targets.
=> Use only target address for allocation in consistent-hashing strategy

.chloggen/opamp-bridge-headers-config.yaml, cmd/operator-opamp-bridge/agent/agent.go, cmd/operator-opamp-bridge/config/config.go, cmd/operator-opamp-bridge/config/config_headers.go, cmd/operator-opamp-bridge/config/config_test.go, cmd/operator-opamp-bridge/config/headers.go, cmd/operator-opamp-bridge/config/testdata/agentwithheaders.yaml
This PR adds a `Headers` field to the opamp bridge config and weaves that value through to the opamp client startup settings. In a subsequent PR this field will be configured to populate in the CRD
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-operator/issues/2410
**Testing:** A test was added to `config_test.yaml` to show this field will be populated by the agent config yaml.
**Documentation:** None
=> Add the ability to set headers in the opamp bridge config

.chloggen/fix-collector-container-log.yaml, internal/manifests/collector/container.go
this fix the bug that prints out error logs without checking when creating collector container resource
=> fix error logging in collector container creation

CONTRIBUTING.md, Makefile, RELEASE.md, hack/ignore-createdAt-bundle.sh, hack/modify-test-images.sh
=> Improve developer experience by minimizing local changes

tests/e2e-openshift/kafka/00-assert.yaml, tests/e2e-openshift/kafka/00-create-kafka-instance.yaml, tests/e2e-openshift/kafka/01-assert.yaml, tests/e2e-openshift/kafka/01-create-kafka-topics.yaml, tests/e2e-openshift/kafka/02-assert.yaml, tests/e2e-openshift/kafka/02-otel-kakfa-receiver.yaml, tests/e2e-openshift/kafka/03-assert.yaml, tests/e2e-openshift/kafka/03-otel-kakfa-exporter.yaml, tests/e2e-openshift/kafka/04-assert.yaml, tests/e2e-openshift/kafka/04-generate-traces.yaml, tests/e2e-openshift/kafka/05-assert.yaml, tests/e2e-openshift/kafka/check_traces.sh
**Testing:**
This e2e case tests the Kafka receiver and exporter. 
```
$ kuttl test --timeout=180 --test=kafka tests/e2e-openshift
2023/12/08 08:15:36 kutt-test config testdirs is overridden with args: [ tests/e2e-openshift ]
=== RUN   kuttl
harness.go:462: starting setup
harness.go:252: running tests using configured kubeconfig.
I1208 08:15:37.940200    8630 request.go:682] Waited for 1.024173085s due to client-side throttling, not priority and fairness, request: GET:https://api.crc.testing:6443/apis/console.openshift.io/v1?timeout=32s
harness.go:275: Successful connection to cluster at: https://api.crc.testing:6443
harness.go:360: running tests
harness.go:73: going to run test suite with timeout of 180 seconds for each step
harness.go:372: testsuite: tests/e2e-openshift has 5 tests
=== …
```
=> [Chore] Add e2e test case for OTEL Kafka receiver and exporter.

tests/e2e-openshift/monitoring/03-create-monitoring-roles.yaml, tests/e2e-openshift/otlp-metrics-traces/03-assert.yaml, tests/e2e-openshift/otlp-metrics-traces/03-metrics-traces-gen.yaml
The Thanos Querier has switched to using kube-rbac-proxy in OpenShift 4.15 which requires creation of additional role and binding to query for metrics. https://issues.redhat.com/browse/MON-3379 This PR adds the required ClusterRole and ClusterRolebinding so that the in-cluster monitoring dependent cases work on OCP 4.15.
Tested on both OpenShift 4.14 and 4.15. 
```
--- PASS: kuttl (139.01s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/otlp-metrics-traces (136.04s)
PASS
--- PASS: kuttl (168.76s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/monitoring (165.21s)
PASS
```
=> [Chore] Add cluster role and binding required for OpenShift monitoring dependent cases.

tests/e2e/targetallocator-features/00-install.yaml
The PR fixes the targetallocator-features test case to work on OpenShift by adding the required securityContext configurations. Note the namespace annotations openshift.io/sa.scc.uid-range=1000/1000 openshift.io/sa.scc.supplemental-groups=3000/1000 has no effect in Kubernetes
=> [Chore] Fix targetallocator-features test case to work on OpenShift.

.chloggen/fix_ta-serviceaccount.yaml, internal/manifests/targetallocator/serviceaccount.go, internal/manifests/targetallocator/serviceaccount_test.go
Fix default ServiceAccount name for target allocator. Up until now it erroneously used the collector name.
Don't create the ServiceAccount for the target allocator if the user provided one themselves.
**Link to tracking Issue:** #2443 
**Testing:**
Added some unit tests and modified existing ones.
Looks like we don't have any builder tests for target allocator manifests. Adding them will require some refactoring, so I'd like to do it in a separate PR.
=> Fix ServiceAccount naming for target allocator

cmd/otel-allocator/config/config.go, cmd/otel-allocator/config/testdata/no_config.yaml
Unmarshal the target allocator config in non-strict mode, which makes it ignore fields it doesn't know, as opposed to erroring on them. This will make it easier for us to change target allocator configuration while preserving backwards compatibilty - see #2466 for example.
I don't think this is worth calling out in the changelog, but I can add an entry if anyone feels strongly about it.
=> Skip unknown fields in target allocator config

.chloggen/main.yaml, internal/manifests/collector/parser/receiver/receiver_oc.go
add missing appProtocol in opencensus receiver
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-operator/issues/2487
=> feat: add default appProtocol on oc receiver

tests/e2e-instrumentation/instrumentation-go/02-assert.yaml, versions.txt
Bumps go autoinstrumentation version to v0.10.0-alpha.  Reviewing the changelogs for v0.9.0-alpha and v0.10.0-alpha I dont see anything that needs updated in our code.
=> [autoinstrumentation] Bump go autoinstrumentation to v0.10.0-alpha

.chloggen/feat_targetallocator-selector.yaml, cmd/otel-allocator/collector/collector.go, cmd/otel-allocator/collector/collector_test.go, cmd/otel-allocator/config/config.go, cmd/otel-allocator/config/config_test.go, cmd/otel-allocator/config/testdata/config_test.yaml, cmd/otel-allocator/config/testdata/pod_service_selector_test.yaml, cmd/otel-allocator/main.go, cmd/otel-allocator/target/testdata/test.yaml, cmd/otel-allocator/target/testdata/test_update.yaml, controllers/builder_test.go, controllers/reconcile_test.go, internal/manifests/targetallocator/configmap.go, internal/manifests/targetallocator/configmap_test.go
Make the label selector for collectors in target allocator configuration use the K8s standard format. We can later explicitly expose this in the TargetAllocator CRD.
One annoying aspect of using the core struct is that it only has tags for json serialization, and the yaml marshaler just lowercases the name. So we end up with `matchlabels` rather than `matchLabels` or `match_labels`. I'm not sure the additional complexity of using a custom struct and then converting is worth it, given that target allocator is almost exclusively used and configured by the operator.
**Link to tracking Issue:** #2422
Resolves https://github.com/open-telemetry/opentelemetry-operator/issues/2422 
**Testing:**
Modified existing tests.
=> Use standard collector selectors in target allocator config

.chloggen/fix-ta-security-context.yaml, apis/v1alpha1/opentelemetrycollector_types.go, apis/v1alpha1/zz_generated.deepcopy.go, bundle/manifests/opentelemetry.io_opentelemetrycollectors.yaml, config/crd/bases/opentelemetry.io_opentelemetrycollectors.yaml, internal/manifests/targetallocator/container.go, internal/manifests/targetallocator/container_test.go, internal/manifests/targetallocator/deployment.go, internal/manifests/targetallocator/deployment_test.go, tests/e2e/targetallocator-features/00-assert.yaml, tests/e2e/targetallocator-features/00-install.yaml
The target allocator CR `securityContext` field is currently the Pod Security Context. This change makes it the container security context, as originally intended. 
**Link to tracking Issue:** #2490 
**Testing:**
Added a unit test and modified an E2E test to specifically check fields unique to the container security context.
=> Use container securityContext for target allocator

.chloggen/pods-in-bridge-message.yaml, Makefile, cmd/operator-opamp-bridge/agent/agent.go, cmd/operator-opamp-bridge/agent/agent_test.go, cmd/operator-opamp-bridge/agent/kube_resource_key.go, cmd/operator-opamp-bridge/agent/kube_resource_key_test.go, cmd/operator-opamp-bridge/config/config.go, cmd/operator-opamp-bridge/config/config_test.go, cmd/operator-opamp-bridge/config/testdata/agentbadconf.yaml, cmd/operator-opamp-bridge/operator/client.go, cmd/operator-opamp-bridge/operator/client_test.go, tests/e2e-opampbridge/opampbridge/00-install.yaml
**Description:** Adds the ability to set pods in component health. This lets users know how many pods are running for each of their collector pools
**Link to tracking Issue:** Part 1 of #2489 
**Testing:** new unit tests
=> Show pods in component health message

cmd/otel-allocator/config/config.go, cmd/otel-allocator/config/config_test.go, cmd/otel-allocator/main.go, cmd/otel-allocator/target/discovery.go, cmd/otel-allocator/target/discovery_test.go
I've made defaults for some options easier to work with by following Go conventions - used string values with an empty string signifying no value, instead of pointers.
I've also made an internal change to target allocator, where it's now clear that we only use scrape configs out of the Prometheus config, and ignore everything else. I'd like to make this more explicit in the future and reject configurations which include anything other than scrape configs.
=> [chore] Clean up config handling in target allocator

.chloggen/fix-ta-pod-security-context.yaml, apis/v1alpha1/opentelemetrycollector_types.go, apis/v1alpha1/zz_generated.deepcopy.go, bundle/manifests/opentelemetry.io_opentelemetrycollectors.yaml, config/crd/bases/opentelemetry.io_opentelemetrycollectors.yaml, internal/manifests/targetallocator/deployment.go, internal/manifests/targetallocator/deployment_test.go, tests/e2e/targetallocator-features/00-assert.yaml, tests/e2e/targetallocator-features/00-install.yaml
Add Pod securityContext to target allocator as it was removed in previous changes.
#2495 
Added a unit and E2E test to specifically check fields unique to the Pod security context.
=> Add Pod securityContext for target allocator

.chloggen/2395-automate-permissions-k8sattribures.yaml, internal/manifests/collector/parser/processor/processor_k8sattributes.go
Continuation of #2394.
**Link to tracking Issue:**  #2395
=> Automate the creation of the permissions needed by k8sattributes.

cmd/otel-allocator/allocation/least_weighted_test.go
Resolves #1291. This test was checking behaviour the least-weighted strategy doesn't exhibit. Allocation using this strategy is not stable.
=> [chore] Remove invalid skipped TA test

tests/e2e/targetallocator-features/00-assert.yaml, tests/e2e/targetallocator-features/00-install.yaml
Small fix for the targetallocator-features test case to work on OpenShift. The test had started failing after changes in PR https://github.com/open-telemetry/opentelemetry-operator/pull/2492 
Tested on OpenShift 4.14, 4.13.
=> [Chore] Fix targetallocator-features e2e case

apis/v1alpha2/common.go, docs/api.md
Closes https://github.com/open-telemetry/opentelemetry-operator/issues/2540
=> add shareProcessNamespace capability to v1alpha2

.github/dependabot.yml
There isn't much benefit to having it daily, and it will reduce the number of PRs it opens for groups. This matters much less for our Docker base images, which change much less frequently, but I changed it there as well for the sake of consistency.
=> [chore] Set dependabot interval to weekly

tests/e2e/targetallocator-prometheuscr/00-install.yaml, tests/e2e/targetallocator-prometheuscr/01-install.yaml
I've made the target allocator Prometheus CR test significantly faster by avoiding restarts in the metrics checking job, checking a metric that is available earlier, and decreasing the scrape interval. All this adds up to the job running 2x as fast.
=> [chore] Fix flaky target allocator e2e test

Makefile
=> Makefile: add api-docs to bundle rule 

RELEASE.md
Update release process to warn against bumping Java and .NET versions.
Related to https://github.com/open-telemetry/opentelemetry-operator/issues/2542
=> [chore] Update release process

.chloggen/feat_ta_monitor-selectors.yaml, cmd/otel-allocator/config/config.go, cmd/otel-allocator/config/config_test.go, cmd/otel-allocator/config/testdata/pod_service_selector_test.yaml, cmd/otel-allocator/watcher/promOperator.go, cmd/otel-allocator/watcher/promOperator_test.go, controllers/builder_test.go, controllers/reconcile_test.go, internal/manifests/targetallocator/configmap.go, internal/manifests/targetallocator/configmap_test.go
Use standard label selectors in target allocator config instead of plain maps. This is a step towards resolving #1907 in `v1alpha2` CRs, by using these selectors in the CRDs themselves as well.
I'd wanted to keep backwards compatibility with older target allocator versions to make upgrades easier, so I couldn't simply change the types of existing config fields. Instead, I decided to move all of these fields under the `prometheus_cr` section in the configuration, which imo is the more intuitive location for it anyway.
There's also a difference in semantics between our current `v1alpha1` CRD and standard behaviour for these selectors that I needed to handle. For selectors:
* a `nil` selector means "select nothing", which is also the default in prometheus-operator CRs
* an …
=> Use standard label selectors in target allocator config

go.mod, go.sum
I found this dependency was updated automatically but to the wrong version. That version is from 2018.
=> [chore] Upgrade openshift-api dependency to latest

Makefile
Signed-off-by: Todd  Yan <38701187+Toaddyan@users.noreply.github.com>
**Description:** Changing Makefile string interpretation
when running make install run, I expect the command to work. instead, I run into string interpolation errors:
```
"github.com/open-telemetry/opentelemetry-operator/internal/version.version=0.91.0-20-gd013d45": invalid char '='
```
**Testing:** make install run now succeeds
**Documentation:** NA as it's already in contributing.md
=> fix: Make install run within Makefile string interpolation issue

.chloggen/bridge-config-env-variables.yaml, cmd/operator-opamp-bridge/config/config.go, cmd/operator-opamp-bridge/config/config_test.go, cmd/operator-opamp-bridge/config/testdata/agentwithheaders.yaml
The opamp bridge now substitutes env variables in its yaml config with their respective value from the local environment upon startup
**Link to tracking Issue:** closes #2577
**Testing:** I added a unit test which includes env variables as args and expects that they are parsed into headers according to the updated `agentwithheaders.yaml`
=> Opamp Bridge can read env variables on config generation

cmd/operator-opamp-bridge/agent/agent.go, cmd/operator-opamp-bridge/agent/agent_test.go
Fixes a bug in the opamp bridge where a nil start time for a pod would lead to a nil pointer panic. This PR sets the starttime to 0 and healthy to false if this occurs
**Link to tracking Issue:** n/a
**Testing:** updated unit tests to include a case that checks when this field is nil
=> Fix nil pointer in opamp bridge generateCollectorHealth

kuttl-test-pdb.yaml
It looks like this test can time out sometimes because deleting the namespace can take a bit of time. We don't really gain anything from having this lower, as we always need to wait for all these test suites, and each runs concurrently.
=> Increase PDB test timeout to 150s

kuttl-test-autoscale.yaml, kuttl-test-multi-instr.yaml, kuttl-test-openshift.yaml, kuttl-test-pdb.yaml, kuttl-test.yaml
We don't really lose much by having the same timeout for all test suites. It looks like we can sometimes have delays due to namespace deletion - this change should help with those.
=> Set a timeout of 300s for all e2e tests

.github/workflows/continuous-integration.yaml, .github/workflows/e2e.yaml, .github/workflows/scorecard.yaml, Makefile, hack/install-kuttl.sh
Speed up tests in the CI via the following changes:
* Avoid unnecessary binary rebuilds of target allocator and opamp bridge. This was probably added to mitigate https://github.com/golang/go/issues/9344, but is not necessary anymore.
* Install kind and kuttl locally via the Makefile.
* Cache tool binaries in the CI
As a result, we save 2-4 minutes per e2e test invocation.
Before:
After:
=> Speed up tests in CI

tests/e2e-targetallocator/targetallocator-features/00-install.yaml, tests/e2e-targetallocator/targetallocator-kubernetessd/00-install.yaml, tests/e2e-targetallocator/targetallocator-kubernetessd/01-install.yaml, tests/e2e-targetallocator/targetallocator-prometheuscr/00-install.yaml, tests/e2e/prometheus-config-validation/00-promreceiver-allocatorconfig.yaml, tests/e2e/smoke-targetallocator/00-install.yaml
We had a race condition where concurrently running tests used the same ClusterRole name with different RBAC permissions.
=> Fix flaky target allocator tests

tests/e2e/smoke-pod-labels/00-assert.yaml, tests/e2e/smoke-pod-labels/00-install.yaml
Fix smoke-pod-labels test case to use multiarch collector image so that we can run the test on non-amd64 clusters. 
**Testing:** 
Tested on a ARM cluster.
--- PASS: kuttl (17.78s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/smoke-pod-labels (12.73s)
PASS
=> [Chore] Update test to use multiarch image.

.chloggen/fix-protocol-handling-in-serviceports.yaml, .chloggen/fix-syslog-tcplog-udplog.yaml, internal/manifests/collector/parser/receiver/receiver.go, internal/manifests/collector/parser/receiver/receiver_syslog.go, internal/manifests/collector/parser/receiver/receiver_syslog_test.go, internal/manifests/collector/parser/receiver/receiver_tcplog.go, internal/manifests/collector/parser/receiver/receiver_tcplog_test.go, internal/manifests/collector/parser/receiver/receiver_udplog.go, internal/manifests/collector/parser/receiver/receiver_udplog_test.go, internal/manifests/collector/service.go, internal/manifests/collector/service_test.go
Fixes three bugs:
1. The "type/value" naming format was wrongly handled inside common receiver code (used by generic receiver)
2. The Protocol (TCP/UDP) was not detected when creating K8s ServicePort
3. The same port number could not be exposed with different protocol
**Link to tracking Issue:**
resolves: #2597
resolves:  #767
**Testing:**
Added tests and also tested `udplog` and `tcplog` in our deployment.
This is purely a bugfix, so no documentation.
=> Added protocol handling for ServicePort and fixed type/value naming inside generic receiver

tests/e2e-prometheuscr/create-sm-prometheus-exporters/08-install.yaml, tests/e2e/prometheus-config-validation/00-promreceiver-allocatorconfig.yaml, tests/e2e/smoke-targetallocator/00-install.yaml
ClusterRoles with the same name in different tests can cause hard to debug test failures due to race conditions. With this fix, all ClusterRoles have unique names.
=> Ensure unique names for ClusterRoles in e2e tests

cmd/otel-allocator/watcher/promOperator_test.go
The test was calling an assert inside an Eventually callback, which in essence meant it only ever tried once. I changed it into an explicit timed wait on a channel.
=> [chore] Fix flaky Prometheus watcher test

Makefile, RELEASE.md
The release guide was a bit out of date, so I updated it and rearranged some sections. I've also automated adding the components section to the changelog. Finally, I've added instructions for the release manager to update the operator Helm Chart after the release succeeds.
Maybe we should have a bot automatically create an issue with these instructions as a checklist?
=> Update release instructions

.ci/create-release-github.sh
Automatically add release notes to the release generated by the CI. This is done in a very simple way, by using sed to cut out the relevant lines from the changelog based on current and previous release tags. Here's a release I generated using this script: https://github.com/swiatekm-sumo/opentelemetry-operator/releases/tag/v0.94.0.
=> [chore] Automate adding release notes to the release

.ci/create-release-github.sh, .github/workflows/publish-operator-hub.yaml, .github/workflows/release.yaml, RELEASE.md
Automatically create a draft release if the latest tagged version and the version from versions.txt don't match. This changes the release workflow dependencies a bit.
Right now we have:
* Create release job is triggered on tag.
* When it succeeds, the operatorhub publishing job runs in the same workflow.
* All the other jobs are independently triggered on tag.
After this change:
* Create release is triggered on changes to `version.txt` in `main`.
* If needed, it creates a draft release and tag.
* Other jobs are triggered by the tag.
* Once the release manager publishes the release, this triggers the operatorhub publishing workflow.
=> ci: create release based on changes to versions.txt

.chloggen/fix-common-fields.yaml, internal/api/convert/v1alpha.go, internal/api/convert/v1alpha_test.go
Fixes a bug that maps the args incorrectly.
- Resolves: #2689 
**Testing:** unit test added
=> Fix conversion from v1alpha1 to v1beta1

apis/v1alpha1/convert.go, apis/v1alpha1/convert_test.go, apis/v1beta1/opentelemetrycollector_types.go, controllers/opentelemetrycollector_controller.go, pkg/sidecar/pod_test.go, pkg/sidecar/podmutator.go
This PR adds only the conversion APIs to the types. The conversion webhook is still disabled. 
Updates #2620 
=> Add conversion go APIs

cmd/otel-allocator/allocation/per_node_test.go, cmd/otel-allocator/target/target.go
The standard setup for collecting kubelet metrics, using a service with no selector to point at each node, results in targets without the `__meta_kubernetes_endpoint_node_name` label, instead it includes:
```yaml
labels:
"__meta_kubernetes_endpointslice_address_target_kind": "Node"
"__meta_kubernetes_endpointslice_address_target_name": "mynode"
```
This update handles this situation.
- Resolves: #2718
**Testing:**
Unit tests added
None needed (this is a fix to existing functionality)
=> fix(targetallocator): support endpointslice (fixes #2718)

apis/v1beta1/ingress.go, apis/v1beta1/opentelemetrycollector_types.go, apis/v1beta1/targetallocator_types.go
=> chore: make v1beta1 strucs more readable

controllers/builder_test.go, controllers/reconcile_test.go, internal/manifests/targetallocator/annotations.go, internal/manifests/targetallocator/annotations_test.go, internal/manifests/targetallocator/configmap.go, internal/manifests/targetallocator/configmap_test.go, internal/manifests/targetallocator/container.go, internal/manifests/targetallocator/container_test.go, internal/manifests/targetallocator/deployment.go, internal/manifests/targetallocator/deployment_test.go, internal/manifests/targetallocator/labels.go, internal/manifests/targetallocator/labels_test.go, internal/manifests/targetallocator/poddisruptionbudget.go, internal/manifests/targetallocator/poddisruptionbudget_test.go, internal/manifests/targetallocator/service.go, internal/manifests/targetallocator/service_test.go, internal/manifests/targetallocator/serviceaccount.go, internal/manifests/targetallocator/serviceaccount_test.go, internal/manifests/targetallocator/servicemonitor.go, internal/manifests/targetallocator/targetallocator.go, internal/manifests/targetallocator/volume.go, internal/manifests/targetallocator/volume_test.go, internal/naming/main.go
Use our internally converted TargetAllocator CR for manifest generation. This is a purely internal change that will make introduction of the TA CR easier, similar to https://github.com/open-telemetry/opentelemetry-operator/pull/2532.
=> Generate target allocator manifests from TargetAllocator CR

.github/workflows/continuous-integration.yaml, .github/workflows/e2e.yaml, .github/workflows/publish-images.yaml, .github/workflows/publish-operator-opamp-bridge.yaml, .github/workflows/publish-target-allocator.yaml, .github/workflows/release.yaml, .github/workflows/scorecard.yaml, go.mod
=> [chore] require Go 1.22

.chloggen/2622-bump-autoinstrumentation-nodejs-to-allow-disabling-instrumentations-via-env.yaml, autoinstrumentation/nodejs/package.json
* Updated only @opentelemetry/auto-instrumentations-node version, so it would contain [PR that allows enabling selected instrumentations via environment variable](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1953).
* **Motivation**: [application startup is super-slow when all instrumentations are enabled](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1953#issuecomment-1961107798)
- Resolves: #2622 (but allows enabling/disabling any instrumentation, not just fs instrumentation)
**Testing:**
* Tests are included in the [PR](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1953) of the updated library
* The change is backwards compatible - all instrumentations are still enabled by default …
=> bump `@opentelemetry/auto-instrumentations-node` to allow enabling only selected instrumentations via env

.github/workflows/e2e.yaml, controllers/builder_test.go, pkg/featuregate/featuregate.go
**Description:** Move the operator.observability.prometheus flag to beta. This flag has been in alpha for plenty long.
**Link to tracking Issue(s):** n/a
**Testing:** e2e
=> Move operator.observability.prometheus to be beta

.github/workflows/continuous-integration.yaml, .github/workflows/e2e.yaml, .github/workflows/publish-images.yaml, .github/workflows/publish-operator-opamp-bridge.yaml, .github/workflows/publish-target-allocator.yaml, .github/workflows/release.yaml, .github/workflows/scorecard.yaml, go.mod
This reverts commit 2409359885e241495e7c5480f85ec3b49feee7be.
Fixes #2752.
=> Revert "[chore] require Go 1.22 (#2747)"

.github/workflows/continuous-integration.yaml, .github/workflows/e2e.yaml, .github/workflows/scorecard.yaml
The caching of tools should take into account the go version. 
For instance this job https://github.com/open-telemetry/opentelemetry-operator/actions/runs/8249577251/job/22562259975 should pass. But it's failing because it's using tools from cache with golang 1.22 that was reverted.
=> Cache tools with go version

autoinstrumentation/nodejs/package.json
Bump NodeJS dependencies
- To trigger release of for #2622, main change done in #2745
**Testing:**
* Tests for #2622 are included in the https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1953 of the updated library
* all the `dependencies` that affect the runtime are semver minor or patch-level, so shouldn't break consumers
* changes in `devDependencies` contain also semver major-level, but those are not included in runtime, so shouldn't break consumers.
=> bump all dependencies to trigger release for dependency updates in autoinstrumentation/nodejs

.chloggen/opampbridge-version-label.yaml, internal/manifests/opampbridge/configmap.go, internal/manifests/opampbridge/configmap_test.go
Fixing a bug where the version label for the opamp bridge config map is too long.  We had custom logic for the config map that was overriding the version label being set by `manifestutils.Labels()`:
https://github.com/open-telemetry/opentelemetry-operator/blob/be172d96401b328176dea0c3d60e2c546d0caf5c/internal/manifests/manifestutils/labels.go#L52-L65
I removed the custom logic and added a unit test for this use case.
- Resolves: #2583
I refactored the unit tests a bit to include this use case and make the test table driven.
None
=> opamp bridge configmap: use manifestutils.Labels() logic to set version label

.chloggen/featuregate_cli_python.yaml, internal/config/main.go, internal/config/options.go, main.go, pkg/constants/env.go, pkg/featuregate/featuregate.go, pkg/instrumentation/podmutator.go, pkg/instrumentation/podmutator_test.go, pkg/instrumentation/upgrade/upgrade.go, pkg/instrumentation/upgrade/upgrade_test.go
change python instrumentation into command line
- Resolves: #2672
=> Python instrumentation featuregate to cli

.chloggen/remove-env-var-validation.yaml, apis/v1alpha1/instrumentation_webhook.go
Removes instrumentation env var prefix validation
Closes https://github.com/open-telemetry/opentelemetry-operator/issues/2098
=> [instrumentation] Remove env var prefix validation

.chloggen/promote-rewrite-featuregate.yaml, internal/manifests/collector/config_replace_test.go, internal/manifests/collector/configmap_test.go, pkg/featuregate/featuregate.go
Promote the flag to stable, with the intent of removing it before the next release.
**Link to tracking Issue(s):** https://github.com/open-telemetry/opentelemetry-operator/issues/2796
**Testing:**
Removed tests for the case where the flag is disabled.
=> Promote operator.collector.rewritetargetallocator feature flag to stable

.chloggen/js-build-remove-dev.yaml, autoinstrumentation/nodejs/package.json
The autoinstrumentation has several build-time dependencies which aren't necessary for the final image, like typescript. Comparison of builds without typescript, typescript + rimraf, and finally all dev dependencies:
```
$ docker image ls --format 'table {{.Repository}} {{.Tag}} {{.Size}}'
autoinstrumentation-nodejs 60d37e18ce 272MB
autoinstrumentation-nodejs no-ts 208MB
autoinstrumentation-nodejs no-ts-rmrf 201MB
autoinstrumentation-nodejs no-dev 200MB
```
We extend the existing `postcompile` script. After building into `build/workspace`, we `prune` to remove extraneous packages. Doing that requires the `package.json` in the build directory.
- Resolves: #2802 
**Testing:** Locally instrumenting a nodejs application.
=> Remove nodejs autoinstrumentation dev dependencies from image

internal/manifests/collector/horizontalpodautoscaler.go, pkg/instrumentation/upgrade/upgrade.go
This PR puts more things into debug logs where they were providing no value to users. The logs and events for autoinstrumentation were particularly noisy – a user doesn't really care if we need to upgrade something that isn't enabled. We just end up crowding logs and events for autoinstrumentation with garbage:
```
{"level":"error","ts":"2024-04-04T19:45:02Z","logger":"instrumentation-upgrade","msg":"autoinstrumentation not enabled for this language","flag":"enable-nginx-instrumentation","stacktrace":"github.com/open-telemetry/opentelemetry-operator/pkg/instrumentation/upgrade.(*InstrumentationUpgrade).upgrade\n\t/Users/jacob.aronoff/workspace/playground/opentelemetry-operator/pkg/instrumentation/upgrade/upgrade.go:147\ngithub.com/open-telemetry/opentelemetry-operator/pkg …
```
=> Quiets some SUPER noisy logs

.github/dependabot.yml, kind-1.23.yaml, kind-1.24.yaml, kind-1.25.yaml, kind-1.26.yaml, kind-1.27.yaml, kind-1.28.yaml, kind-1.29.yaml
#2604 erroneously updated all the versions to 1.29. I've reverted that change and updated dependabot configuration to only apply patch updates to these images.
=> Use all supported kind versions in tests

.chloggen/disable-looking-for-podmonitor-servicemonitor-when-not-needed.yaml, controllers/opampbridge_controller_test.go, controllers/opentelemetrycollector_controller.go, controllers/reconcile_test.go, controllers/suite_test.go, internal/autodetect/main.go, internal/autodetect/main_test.go, internal/autodetect/prometheus/operator.go, internal/config/main.go, internal/config/main_test.go, internal/config/options.go, internal/manifests/collector/podmonitor.go, internal/manifests/collector/podmonitor_test.go, internal/manifests/collector/servicemonitor.go, internal/manifests/collector/servicemonitor_test.go, internal/manifests/collector/suite_test.go, main.go
**Description:** Changes the prometheus operator integration to fail by logging (rather than panicking) and as a result only allowing the creation of prometheus resources when it is safe to do so.
- Resolves: #2810 
**Testing:** unit tests, e2e testing, local confirmation
=> Only add to scheme when prometheus is available

internal/manifests/collector/container.go
**Description:** Makes another super noisy log a debug statement
=> [chore] Make another noisy log a debug

README.md
I'd like to propose promoting me to maintainer. I've been an active contributor in this project for over a year, and an Approver for most of that time, as well as a prolific SIG meeting participant. My original area of interest was the target allocator (https://github.com/open-telemetry/opentelemetry-operator/pull/1889 https://github.com/open-telemetry/opentelemetry-operator/pull/1923 https://github.com/open-telemetry/opentelemetry-operator/pull/2189), but I've also improved both the local dev experience (https://github.com/open-telemetry/opentelemetry-operator/pull/2317 https://github.com/open-telemetry/opentelemetry-operator/pull/2774 https://github.com/open-telemetry/opentelemetry-operator/pull/2654) and the CI (https://github.com/open-telemetry/opentelemetry-operator/pull/2595 …
=> Promote @swiatekm-sumo to maintainer

.chloggen/fix_drop-ta-config-backwards-compat.yaml, controllers/builder_test.go, controllers/reconcile_test.go, internal/manifests/targetallocator/configmap.go, internal/manifests/targetallocator/configmap_test.go
We've made a breaking change to the target allocator configuration in 0.93.0. This change removes operator compatibility with target allocator versions older than that.
**Link to tracking Issue(s):** #1907 
**Testing:**
Modified existing tests.
=> Drop compatibility with older target allocator versions

apis/v1alpha1/opentelemetrycollector_types.go, apis/v1beta1/opentelemetrycollector_types.go, apis/v1beta1/targetallocator_types.go, cmd/otel-allocator/README.md, docs/api.md
Made it clear in both the field description and target allocator README that the per-node allocation strategy ignores targets without a Node.
**Link to tracking Issue(s):** https://github.com/open-telemetry/opentelemetry-operator/issues/2792
- Resolves: #2792 
Added a section on allocation strategies in the target allocator README.
=> Improve allocation strategy documentation

.chloggen/chore_remove-ta-rewrite-flag.yaml, apis/v1alpha1/collector_webhook.go, internal/manifests/collector/config_replace.go, internal/manifests/targetallocator/adapters/config_to_prom_config.go, internal/manifests/targetallocator/adapters/config_to_prom_config_test.go, pkg/featuregate/featuregate.go
This feature gate is slated for removal in 0.99.0. 
After merging this, we should rethink how the prometheus config validation should work. It's probably still too strict in some cases the way it is now.
**Link to tracking Issue(s):** #2796 
- Resolves: #2796
**Testing:**
Removed some tests for the non-enabled case.
=> Remove `operator.collector.rewritetargetallocator` feature flag

docs/api.md
#2848 was merged without being completely up to date against main, and missed some updates to api docs as a result. Fix that here.
=> Fix outdated api docs

apis/v1beta1/allocation_strategy.go, bundle/manifests/opentelemetry.io_opentelemetrycollectors.yaml, config/crd/bases/opentelemetry.io_opentelemetrycollectors.yaml, config/crd/bases/opentelemetry.io_targetallocators.yaml, docs/api.md
=> Add missing per-node strategy to TA CRD

.chloggen/fix-unescaping.yaml, internal/manifests/collector/targetallocator_test.go, internal/manifests/targetallocator/adapters/config_to_prom_config.go, internal/manifests/targetallocator/adapters/config_to_prom_config_test.go, tests/e2e-targetallocator/targetallocator-features/00-install.yaml
Fixed a bug where unescaping `$$` values in prometheus receiver configuration wouldn't apply to metric relabel configs if target relabel configs weren't also present.
**Link to tracking Issue(s):** #2867 
- Resolves: #2867 
**Testing:**
Added more unit tests to the unescaping function. Also added a test to TargetAllocator CR generation, and modified a E2E test to specifically check this configuration
=> Fix a metric relabel config unescaping bug

cmd/otel-allocator/README.md
fixes an incorrect doc
- Resolves: #2866
**Testing:** n/A
=> Update README.md to make clear TA doesn't support collector as a deployment

config/manager/kustomization.yaml, tests/e2e/multiple-configmaps/00-install.yaml, tests/e2e/smoke-pod-labels/00-install.yaml
Logging exporter is deprecated, switches to use the debug exporter
Unblocks https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1154
=> [chore] switch to using debug exporter in tests

apis/v1beta1/targetallocator_types.go, config/crd/bases/opentelemetry.io_targetallocators.yaml
Without this annotation, we get no data at all, as it's all discarded during serialization.
=> Add missing annotation to TargetAllocator ScrapeConfigs field

.chloggen/add-service-instance-id.yaml, pkg/instrumentation/podmutator_test.go, pkg/instrumentation/sdk.go, pkg/instrumentation/sdk_test.go, tests/e2e/env-vars/01-assert.yaml, tests/e2e/env-vars/02-assert.yaml, tests/e2e/env-vars/03-assert.yaml
I'm using newrelic with opentelemetry and according to their [documentation](https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-resources/) they rely on the `service.instance.id` to group jvm metrics.
https://opentelemetry.io/docs/specs/semconv/resource/#service-experimental
After a few explorations, I noticed that this was expected here https://github.com/open-telemetry/semantic-conventions/pull/312
But while the pod is being created it may not have a name yet, which results on an absent property.
This PR will change it to be more dynamic at runtime.
- Resolves: …
=> Add service.instance.id with Pod name

docs/crd-changelog.md
I ended up adding a more general "CRD changelog" document, with the first entry explaining the v1alpha1 -> v1beta1 transition. We can put other, similar sections in here in the future, for example introducing new CRDs.
=> Add document explaining v1beta1 changes

README.md, cmd/otel-allocator/README.md
This should be merged after v1beta1 is released.
=> Use v1beta1 in docs

.chloggen/fix_load-initial-servicemonitors.yaml, cmd/otel-allocator/main.go, internal/manifests/targetallocator/configmap.go, internal/manifests/targetallocator/configmap_test.go, tests/e2e-targetallocator/targetallocator-prometheuscr/00-install.yaml, tests/e2e-targetallocator/targetallocator-prometheuscr/01-install.yaml
The target allocator readiness check is broken in two ways:
* The target allocator doesn't do an initial load of targets from Prometheus CRs. So if there aren't any CRs, no targets are generated.
* If there are no scrape configs, but there is an empty scrape configs array, targets are loaded from these, and the target allocator becomes ready even though it shouldn't be.
This PR fixes both of these issues by:
* Loading targets from Prometheus CRs at startup.
* Not loading targets from scrape configs if there aren't any.
* For good measure, the target allocator config now doesn't even have the prometheus configuration section if there aren't any scrape targets.
**Link to tracking Issue(s):** #2903 
- Resolves: #2903 
**Testing:**
I changed an integration test with only …
=> Fix target allocator readiness check

cmd/otel-allocator/collector/collector.go, cmd/otel-allocator/collector/collector_test.go, cmd/otel-allocator/main.go
Use an informer for tracking collector Pods in the target allocator, instead of the custom active watcher we've had till now. This is just to make things more standardized and maintainable. I've also implemented a rate limiter on collector updates while at it.
This will make it easier to fix #2201 in a follow-up.
Most likely fixes #2916.
=> [chore] Use informer to track collector Pods in target allocator

autoinstrumentation/nodejs/package.json
Update Node.js Auto Instrumentation to v0.46.0
https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/auto-instrumentations-node-v0.46.0
=> [autoinstrumentation/nodejs] Update to v0.46.0

tests/e2e-openshift/Dockerfile, tests/e2e-openshift/scrape-in-cluster-monitoring/chainsaw-test.yaml, tests/e2e-openshift/scrape-in-cluster-monitoring/check_logs.sh, tests/e2e-openshift/scrape-in-cluster-monitoring/create-clusterrolebinding-assert.yaml, tests/e2e-openshift/scrape-in-cluster-monitoring/create-clusterrolebinding.yaml, tests/e2e-openshift/scrape-in-cluster-monitoring/create-otel-instance-assert.yaml, tests/e2e-openshift/scrape-in-cluster-monitoring/create-otel-instance.yaml
The PR adds a test case to scrape the OpenShift in-cluster monitoring stack. 
```
--- PASS: chainsaw/scrape-in-cluster-monitoring (41.11s)
PASS
Done.
```
=> [Chore] Test case for scraping OpenShift in-cluster monitroing stack

README.md
I have been unable to provide this position the bandwidth that it deserves and it is time to formalize recognition of that fact.
=> Move Aneurysm9 to emeritus status

.chloggen/fix-collector-node-selector.yaml, internal/manifests/mutate.go, tests/e2e/node-selector-collector/00-assert-daemonset-without-node-selector.yaml, tests/e2e/node-selector-collector/00-assert-deployment-without-node-selector.yaml, tests/e2e/node-selector-collector/00-assert-statefulset-without-node-selector.yaml, tests/e2e/node-selector-collector/00-install-collectors-without-node-selector.yaml, tests/e2e/node-selector-collector/01-assert-daemonset-with-node-selector.yaml, tests/e2e/node-selector-collector/01-assert-deployment-with-node-selector.yaml, tests/e2e/node-selector-collector/01-assert-statefulset-with-node-selector.yaml, tests/e2e/node-selector-collector/01-install-collectors-with-node-selector.yaml, tests/e2e/node-selector-collector/chainsaw-test.yaml
- Resolves: https://github.com/open-telemetry/opentelemetry-operator/issues/2940
With e2e, create and update collectors (Deployment/Daemonset/Statefulset) and add/remove nodeSelector.
=> Fix Pod NodeSelector changes from OpenTelemetryCollector

.chloggen/customized-log-encoder.yaml, DEBUG.md, internal/config/options.go, main.go
Added 5 new parameters to enable a customized JSON log Encoder: 
`--enable-customized-log-encoder` = It will enable the feature to set customized `keys` and `formats` to the logs, otherwise, the operator will use the zap-devel config. 
`--log-message-key` = It will replace the Key of the Message field (e.g. "msg") 
`--log-level-key` = It will replace the Key of the Level field (e.g. "severity")
`--log-time-key`= It will replace the Key of the Time field (e.g. "timestamp")
`--log-time-format` = It will replace the Format of the Time field (e.g. "epoch", "epochmillis", "epochnano", "iso8601", "rfc3339" or "rfc3339nano")
`--log-level-format` = It will replace the Format of the Level field (e.g. "uppercase", "lowercase")
**Link to tracking …
=> Added new Log Enconder Config

README.md, RELEASE.md
I'd like to recognize @VineethReddy02's contributions to the project, especially during its early period. Recognizing that Vineeth might not have time to dedicate to the project anymore, I'd like to propose moving Vineeth to emeritus maintainer. 
=> [chore] move VineethReddy02 to emeritus

.chloggen/cleanup-roles.yaml, controllers/common.go, controllers/opentelemetrycollector_controller.go, controllers/reconcile_test.go, controllers/suite_test.go, internal/config/main.go
=> Cleanup cluster roles and bindings 

.chloggen/fix-ta-check-policy.yaml, apis/v1beta1/collector_webhook.go
Fixed non-expected warnings on TA webhook.
- Resolves: #2685 
=> Fixed non-expected warnings on TA webhook.

.chloggen/verify-prom-crd-resources.yaml, internal/autodetect/main.go, internal/autodetect/main_test.go
Currently the Prometheus CRs availability checks today that the API group `monitoring.coreos.com` is installed, and then adds the ServiceMonitor and PodMonitor to the scheme. However, I only have the ServiceMonitor CRD installed which results in the operator is unable to start. 
This change adds verification that both the expected resources are installed and not only that the API group is installed.
=> Verify ServiceMonitor and PodMonitor are installed in prom cr availability check

.chloggen/refactor-strategies.yaml, cmd/otel-allocator/allocation/allocator.go, cmd/otel-allocator/allocation/allocator_test.go, cmd/otel-allocator/allocation/consistent_hashing.go, cmd/otel-allocator/allocation/consistent_hashing_test.go, cmd/otel-allocator/allocation/least_weighted.go, cmd/otel-allocator/allocation/least_weighted_test.go, cmd/otel-allocator/allocation/per_node.go, cmd/otel-allocator/allocation/per_node_test.go, cmd/otel-allocator/allocation/strategy.go, cmd/otel-allocator/allocation/testutils.go
Allocation strategies are currently messy and duplicate a lot of logic. This is an attempt at making them more DRY.
* Factored out the bookkeeping into a new Allocator struct. It keeps track of targets, collectors, allocation, metrics, etc.
* Added a new Strategy interface that strategies need to implement. Right now, the minimum needed is just a method that takes a collector map and a target, and returns the assigned collector.
* Added some generic allocator tests that run for all strategies.
I'm not entirely happy with the end result, and I've left some TODOs in the code I'd like to address in a follow-up. I haven't included those changes in this PR in the interest of keeping it simpler.
=> [chore] Refactor allocation strategies

.chloggen/bring-back-wh-port.yaml, main.go
**Description:** User reported being unable to set webhook port
Fixes bug introduced in https://github.com/open-telemetry/opentelemetry-operator/pull/2923
=> Bring back webhook port

tests/e2e-openshift/monitoring/check_metrics.sh, tests/e2e-openshift/otlp-metrics-traces/check_metrics.sh
In OpenShift 4.16 tokens for service account are not generated by default and we have to now use the TokenRequest API to create token. The PR fixes the check_metrics.sh script to create a token from prometheus-user-workload SA. 
Tested on OpenShift 4.15 and 4.16:
```
--- PASS: chainsaw (173.73s)
--- PASS: chainsaw/monitoring (96.42s)
--- PASS: chainsaw/otlp-metrics-traces (77.32s)
PASS
- Passed  tests 2
Done.
```
=> [Chore] Fix test cases querying OpenShift user workload monitoring stack.

README.md, apis/v1beta1/targetallocator_types.go, cmd/otel-allocator/README.md, docs/api.md, docs/crd-changelog.md
It's not clear that you need to use an empty selector in `v1beta1` CRs to select all the resources. See #2993 for an example of the kind of confusion this can create. Update the documentation to make this clearer.
I've also deleted some outdated content from the target allocator README.
=> Update selector documentation for Target Allocator

tests/e2e-openshift/kafka/00-create-kafka-instance.yaml, tests/e2e-openshift/kafka/chainsaw-test.yaml
Kafka version 3.5.0 is not available anymore. Update the version in test to Kafka 3.7.0
```
--- PASS: chainsaw/kafka (201.57s)
PASS
Done.
```
=> [Chore] Update Kafka version in e2e test

.github/workflows/changelog.yaml, .github/workflows/continuous-integration.yaml, .github/workflows/e2e.yaml, .github/workflows/release.yaml, .github/workflows/scorecard.yaml
Should we just remove these version pins and let the action always use the latest Go? Looks like we forget to bump this, and dependabot doesn't help with it.
Should unblock #3028.
=> Upgrade Go version in Ci to 1.22.3

.github/workflows/changelog.yaml, .github/workflows/continuous-integration.yaml, .github/workflows/e2e.yaml, .github/workflows/release.yaml, .github/workflows/scorecard.yaml
1.22.4 fixes an annoying toolchain version parsing issue, allowing us to keep a Go directive in our go.mod without a patch number. See https://github.com/golang/go/issues/62278.
This should properly fix dependabot issues like #3028
=> Upgrade Go version in Ci to 1.22.4

cmd/otel-allocator/config/config.go, cmd/otel-allocator/config/config_test.go, cmd/otel-allocator/config/flags.go, cmd/otel-allocator/config/flags_test.go, cmd/otel-allocator/config/testdata/config_test.yaml, controllers/builder_test.go, controllers/reconcile_test.go, internal/manifests/targetallocator/configmap.go, internal/manifests/targetallocator/configmap_test.go, internal/manifests/targetallocator/container.go, internal/manifests/targetallocator/container_test.go, tests/e2e-targetallocator/targetallocator-features/00-assert.yaml
Prometheus CR was arbitrarily enabled by a command-line flag instead of the configuration file setting. Use the config file instead for consistency. This also lets us avoid adding the PrometheusCR section altogether if it's not enabled.
I've also added proper support for `Args` in the TargetAllocator CRD. This is currently a no-op, as this field cannot be set via the embedded TA struct.
=> Enable Prometheus CR via the TA config file

apis/v1alpha1/targetallocator_types.go, apis/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/opentelemetry.io_targetallocators.yaml, internal/manifests/collector/targetallocator.go, internal/manifests/collector/targetallocator_test.go, internal/manifests/targetallocator/configmap.go, internal/manifests/targetallocator/configmap_test.go
Doing this as per the decision made in https://github.com/open-telemetry/opentelemetry-operator/issues/2422#issuecomment-2154655906. We're going to use a label to manage this relationship instead.
On a separate note, I'd like to give the TargetAllocator builder a different Params struct, so we can more clearly indicate this relationship. That's a more involved change, though, and I'll make it separately.
=> Remove collectorSelector field from TA CRD

cmd/otel-allocator/README.md
Updated Target Allocator README. The sample code for using the TA with `v1beta1` of the `OpenTelemetryCollector` CR was not using the correct constructs as per the [API docs](https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api.md#opentelemetrycollector-1).
**Link to tracking Issue(s):** n/a
**Testing:** n/a (doc update)
**Documentation:** See description above
=> Fix OpenTelemetryCollector example YAML in Target Allocator README

controllers/common.go, internal/manifests/builder.go, internal/manifests/collector/collector.go, internal/manifests/opampbridge/opampbridge.go, internal/manifests/targetallocator/annotations_test.go, internal/manifests/targetallocator/configmap.go, internal/manifests/targetallocator/configmap_test.go, internal/manifests/targetallocator/deployment.go, internal/manifests/targetallocator/deployment_test.go, internal/manifests/targetallocator/poddisruptionbudget.go, internal/manifests/targetallocator/poddisruptionbudget_test.go, internal/manifests/targetallocator/service.go, internal/manifests/targetallocator/service_test.go, internal/manifests/targetallocator/serviceaccount.go, internal/manifests/targetallocator/serviceaccount_test.go, internal/manifests/targetallocator/servicemonitor.go, internal/manifests/targetallocator/servicemonitor_test.go, internal/manifests/targetallocator/targetallocator.go
Make the builder definitions more generic to allow different Params structures for different builders. Use this to define a separate Params structure for the TargetAllocator.
=> Add a separate Params struct for Target Allocator

.chloggen/chore_upgrade-go-122.yaml, .github/workflows/publish-images.yaml, .github/workflows/publish-operator-opamp-bridge.yaml, .github/workflows/publish-target-allocator.yaml, go.mod, tests/e2e-openshift/Dockerfile, tests/instrumentation-e2e-apps/golang/Dockerfile
As we haven't merged our Go support policy yet, let's upgrade to 1.22 ahead of time to unblock some dependency updates.
**Link to tracking Issue(s):** #2757
=> Require Go 1.22 for building the operator

controllers/builder_test.go, controllers/common.go, controllers/opentelemetrycollector_controller.go, internal/manifests/collector/config_replace.go, internal/manifests/collector/config_replace_test.go, internal/manifests/collector/configmap.go, internal/manifests/collector/suite_test.go, internal/manifests/params.go, internal/naming/main.go, pkg/sidecar/pod.go
Refactor how the target allocator is treated by collector reconciliation.
I've converted `params.TargetAllocator` to a pointer, and now whenever any of the collector manifest builders want to know if a Target Allocator is enabled, they check that pointer instead of `params.OtelCol.Spec.TargetAllocator.Enabled`. The reason for this is that there will be more ways to assign a target allocator to a collector after the TargetAllocator CRD is introduced.
Logically, this PR doesn't change anything.
**Link to tracking Issue(s):** #2422
=> Prepare Collector reconciliation for TargetAllocator CRD

README.md
This is to make it easier for users to check if a specific prometheus-operator feature is supported by the target allocator. Trying to use an unsupported feature will typically fail silently.
This was suggested in #2839.
=> Add prometheus-operator versions to README

.chloggen/feat_drop-lease-on-exit.yaml, main.go
This will make rollouts and restarts much faster. See #3058 for more detail.
- Resolves: #3058
**Testing:**
Tested the default manifests in a kind cluster.
=> Release leader election lease on exit

.chloggen/main.yaml, controllers/reconcile_test.go, internal/manifests/mutate.go, internal/manifests/mutate_test.go
Allow custom annotations on service accounts. OpenShift 4.16 adds an annotation (`openshift.io/internal-registry-pull-secret-ref: simplest-collector-dockercfg-jwq66`) to SA which then configures pull secret. 
See https://docs.openshift.com/container-platform/4.16/release_notes/ocp-4-16-release-notes.html   (`Legacy service account API token secrets are no longer generated for each service account`)
=> Allow custom annotations on service accounts

.chloggen/fix-parsing-bug.yaml, apis/v1beta1/config.go, apis/v1beta1/config_test.go, controllers/reconcile_test.go, controllers/suite_test.go, controllers/testdata/otlp_test.yaml, internal/components/exporters/helpers.go, internal/components/exporters/helpers_test.go, internal/components/multi_endpoint.go, internal/components/nop_parser.go, internal/manifests/collector/service_test.go
Fixes a bug where we trying to parse endpoint for exporters which is unnecessary.
- Resolves #3124 
**Testing:** unit tests and envtest
=> Add nop parser for exporters

tests/e2e-openshift/Dockerfile
The PR bumps the Chainsaw version used the OpenShift CI test runner image.
=> [Chore] Bump Chainsaw version in tests/e2e-openshift/Dockerfile

.chloggen/feat_python-prometheus-exporter.yaml, CHANGELOG.md, autoinstrumentation/python/requirements.txt
promethues exporter used for python metrics
- Resolves: #3122
autoinstrumentation python agent to my python project after compile with `opentelemetry-exporter-prometheus==0.46b0` working fine.
=> ✨ feat(autoinstrumentation): prometheus expoter

.github/workflows/publish-operator-bundle.yaml
Fix the GitHub Workflow for the image bundle: https://github.com/open-telemetry/opentelemetry-operator/actions/runs/9993322308/job/27620413998
=> [chor] Fix container bundle image build

bundle/openshift/manifests/opentelemetry-operator.clusterserviceversion.yaml, config/overlays/openshift/manager-patch.yaml
The PR enables the OTEL OpenShift dashboard feature in the OpenShift bundle by default. Refer feature [changelog](https://github.com/open-telemetry/opentelemetry-operator/blob/main/.chloggen/2995-openshift-dashboard.yaml#L16).
=> [Chore] Enable the OTEL dashboard feature in OpenShift operator bundle

Makefile, cmd/operator-opamp-bridge/agent/agent.go, cmd/operator-opamp-bridge/agent/agent_test.go, cmd/operator-opamp-bridge/config/config.go, cmd/operator-opamp-bridge/metrics/reporter.go, go.mod, go.sum, tests/e2e-opampbridge/opampbridge/00-install.yaml, tests/test-e2e-apps/bridge-server/opampsrv/opampsrv.go
Bumps to latest opamp go
- Resolves #3019 
**Testing:** unit tests updated
=> bump opamp go to v0.15.0

.chloggen/3151-feat-annotations-filter.yaml, controllers/builder_test.go, controllers/reconcile_test.go, internal/manifests/collector/configmap.go, internal/manifests/collector/daemonset_test.go, internal/manifests/collector/deployment_test.go, internal/manifests/collector/rbac.go, internal/manifests/collector/service.go, internal/manifests/collector/service_test.go, internal/manifests/collector/serviceaccount.go, internal/manifests/collector/statefulset_test.go, internal/manifests/manifestutils/annotations.go, internal/manifests/manifestutils/annotations_test.go
=> feat: configmap, rbac, service, serviceaccount apply annotations-filter

.chloggen/3189-openshift-dashboard-differentiate-otelcols.yaml, internal/openshift/dashboards/metrics-dashboard.json
Allow the dropdown menu to show the different collector instances in a namespace.
- Resolves:  #3189
=> Fix dropdown menu to select individual OpenTelemetry Collector instances

.chloggen/fix-ta-with-proxy.yaml, controllers/builder_test.go, internal/manifests/collector/config_replace.go, internal/manifests/collector/config_replace_test.go, internal/manifests/collector/configmap_test.go, internal/manifests/collector/testdata/config_expected_targetallocator.yaml, internal/manifests/collector/testdata/relabel_config_expected_with_sd_config.yaml, internal/manifests/targetallocator/adapters/config_to_prom_config.go, internal/manifests/targetallocator/adapters/config_to_prom_config_test.go, tests/e2e-targetallocator/targetallocator-kubernetessd/00-assert.yaml, tests/e2e-targetallocator/targetallocator-kubernetessd/chainsaw-test.yaml, tests/e2e-targetallocator/targetallocator-prometheuscr/00-assert.yaml, tests/e2e-targetallocator/targetallocator-prometheuscr/chainsaw-test.yaml, tests/e2e/smoke-targetallocator/00-assert.yaml, tests/e2e/smoke-targetallocator/chainsaw-test.yaml
Operator image: docker.io/pavolloffay/opentelemetry-operator:dev-b67d063e-1722432504 
See the changelog for more info.
On clusters with global proxy following error was happening on the collector
```
2024-07-22T21:11:58.189Z       info    [service@v0.102.1/service.go:113](mailto:service@v0.102.1/service.go:113)       Setting up own telemetry...
2024-07-22T21:11:58.189Z       info    [service@v0.102.1/telemetry.go:96](mailto:service@v0.102.1/telemetry.go:96)      Serving metrics {"address": ":8888", "level": "Normal"}
2024-07-22T21:11:58.189Z       info    [exporter@v0.102.1/exporter.go:275](mailto:exporter@v0.102.1/exporter.go:275)     Development component. May change in the future.  {"kind": "exporter", "data_type": "metrics", "name": …
```
=> Fix TA in clusters with global proxy

.chloggen/extract-resources-ns.yaml, README.md, pkg/constants/env.go, pkg/instrumentation/sdk.go, pkg/instrumentation/sdk_test.go
change_type: sdk.go
- Modified the logic for iterating over pod annotations, utilizing pod.GetAnnotations() to identify and extract resources using the specified namespace prefix (constants.ReservedNamespace).
- Implemented the use of the OpenTelemetry.io namespace for extracting resource annotations from Kubernetes pods.
- Enhanced handling to streamline the extraction process and avoid overwriting existing resource mappings.
issues: [https://github.com/open-telemetry/opentelemetry-operator/issues/2181]
https://github.com/open-telemetry/opentelemetry-operator/pull/2330
TestCase :white_check_mark: 
```
?       github.com/open-telemetry/opentelemetry-operator/pkg/constants  [no test files]
ok      github.com/open-telemetry/opentelemetry-operator/pkg/collector/upgrade  
ok …
```
=>  using opentelemetry.io* namespace for extracing resource based on annotations  from k8s Api #2330 

Makefile
The PR fixes the following issue when building the images on Mac, Windows which uses Docker/Podman Desktop. 
```
=> [certificates 1/2] FROM docker.io/library/alpine:3.20@sha256:0a4eaa0eecf5f8c050e5bba433f58c052be7587ee8af3e8b3910ef9a  0.0s
=> => resolve docker.io/library/alpine:3.20@sha256:0a4eaa0eecf5f8c050e5bba433f58c052be7587ee8af3e8b3910ef9ab5fbe9f5       0.0s
=> [stage-1 1/3] WORKDIR /root/                                                                                           0.0s
=> [internal] load build context                                                                                          1.4s
=> => transferring context: 97.21MB                                                                                       1.4s
=> CACHED [certificates 2/2] RUN …
```
=> [Chore] Fix image push for Mac and Windows using Docker/Podman Desktop

tests/e2e-openshift/Dockerfile, tests/e2e-openshift/export-to-cluster-logging-lokistack/chainsaw-test.yaml, tests/e2e-openshift/export-to-cluster-logging-lokistack/check_logs.sh, tests/e2e-openshift/export-to-cluster-logging-lokistack/generate-logs-assert.yaml, tests/e2e-openshift/export-to-cluster-logging-lokistack/generate-logs.yaml, tests/e2e-openshift/export-to-cluster-logging-lokistack/install-loki-assert.yaml, tests/e2e-openshift/export-to-cluster-logging-lokistack/install-loki.yaml, tests/e2e-openshift/export-to-cluster-logging-lokistack/install-minio-assert.yaml, tests/e2e-openshift/export-to-cluster-logging-lokistack/install-minio.yaml, tests/e2e-openshift/export-to-cluster-logging-lokistack/logging-uiplugin-assert.yaml, tests/e2e-openshift/export-to-cluster-logging-lokistack/logging-uiplugin.yaml, tests/e2e-openshift/export-to-cluster-logging-lokistack/otel-collector-assert.yaml, tests/e2e-openshift/export-to-cluster-logging-lokistack/otel-collector.yaml
The PR adds a test case for exporting logs through an OTEL collector to OpenShift in-cluster Logging LokiStack instance. 
```
--- PASS: chainsaw/export-to-cluster-logging-lokistack (173.06s)
PASS
Done.
```
=> [Chore] Export logs to OpenShift in-cluster logging LokiStack

README.md
I now work for Elastic, and wanted to reflect that in the README.
=> Update @swiatekm's affiliation in the README

.chloggen/fix_dont-own-volumes.yaml, bundle/community/manifests/opentelemetry-operator.clusterserviceversion.yaml, bundle/openshift/manifests/opentelemetry-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/opentelemetrycollector_controller.go
Fixed a bug where we'd unnecessarily watch PVs and PVCs without ever creating any. For mysterious reasons, this caused issues when running the operator scoped to a single namespace, using a Role for RBAC. See #3042.
**Link to tracking Issue(s):** #3042
=> Don't unnecessarily take ownership of PersistentVolumes and PersistentVolumeClaims

internal/manifests/collector/targetallocator.go, internal/manifests/collector/targetallocator_test.go, internal/manifests/targetallocator/configmap.go, internal/manifests/targetallocator/configmap_test.go
This is in preparation for the Target Allocator CRD. For that CRD, the Collector instance may be specified via a label or ownership relation. Therefore, we need to pull the necessary data from the Collector instance during TA config generation. It's more convenient to do this in all cases, which is what this change does.
No current behaviour should change as a result.
**Link to tracking Issue(s):** #2516 
**Testing:**
Added tests for some new helper functions I introduced.
=> Move TA config parsing to configmap manifest builder

.chloggen/3216-ta-retry-namespace-informer-creation.yaml, cmd/otel-allocator/watcher/promOperator.go
Added retry mechanism for namespace informer creation in promOperator CRD watcher.
In case of the namespace informer creation still fails, then exit the target allocator with error.
**Link to tracking Issue(s):** [3216](https://github.com/open-telemetry/opentelemetry-operator/issues/3216)
- Resolves: #3216 
**Testing:**
Done some manual testing
If I changed the context to have timeout, and configured the timeout to 1 nanosecond:
```
$ go run cmd/otel-allocator/main.go
{"level":"info","ts":"2024-08-29T23:17:08+02:00","msg":"Starting the Target Allocator"}
{"level":"error","ts":"2024-08-29T23:17:08+02:00","logger":"setup.prometheus-cr-watcher","msg":"Retrying namespace informer creation in promOperator CRD watcher","error":"client rate limiter Wait returned an error: …
```
=> Retry failed namespace informer creation in promOperator CRD watcher

.chloggen/3258-autoscaler-utilization-greater-than-99.yaml, apis/v1beta1/collector_webhook.go, apis/v1beta1/collector_webhook_test.go
Allowing the autoscaler targetCPUUtilization and TargetMemoryUtilization to be greater than 99.
Added an extra test for checking the TargetMemoryUtilization value.
[3258](https://github.com/open-telemetry/opentelemetry-operator/issues/3258)
- Resolves: #3258 
TestOTELColValidatingWebhook tests the modified conditions
N/A
=> Allow autoscaler targetCPUUtilization and TargetMemoryUtilization to be greater than 99

.chloggen/3242-rollback-of-3187.yaml, controllers/builder_test.go, internal/manifests/collector/config_replace.go, internal/manifests/collector/config_replace_test.go, internal/manifests/collector/configmap_test.go, internal/manifests/collector/testdata/config_expected_targetallocator.yaml, internal/manifests/collector/testdata/relabel_config_expected_with_sd_config.yaml, internal/manifests/targetallocator/adapters/config_to_prom_config.go, internal/manifests/targetallocator/adapters/config_to_prom_config_test.go, tests/e2e-targetallocator/targetallocator-kubernetessd/00-assert.yaml, tests/e2e-targetallocator/targetallocator-kubernetessd/chainsaw-test.yaml, tests/e2e-targetallocator/targetallocator-prometheuscr/00-assert.yaml, tests/e2e-targetallocator/targetallocator-prometheuscr/chainsaw-test.yaml, tests/e2e/smoke-targetallocator/00-assert.yaml, tests/e2e/smoke-targetallocator/chainsaw-test.yaml
**Description:** Rollback #3187 
Fix #3242 with rollback of 3187. Please make sure this change works for clusters with custom domains before re submitting.
**Link to tracking Issue(s):** #3242 
**Testing:** This rolls back to previously working code.
**Documentation:** None
=> Rollback 3187

apis/v1alpha1/targetallocator_types.go, controllers/common.go, controllers/suite_test.go, controllers/targetallocator_controller.go, controllers/targetallocator_controller_test.go, internal/manifests/targetallocator/configmap.go, internal/manifests/targetallocator/configmap_test.go, internal/manifests/targetallocator/deployment_test.go, internal/manifests/targetallocator/serviceaccount_test.go, internal/manifests/targetallocator/targetallocator.go, internal/status/targetallocator/handle.go, internal/status/targetallocator/targetallocator.go, main.go
Add the controller for the TargetAllocator CRD. This is just the controller code with unit tests, it is not actually enabled and there's no user-facing impact.
Some associated changes include:
* The Collector in TargetAllocator manifest generation parameters becomes optional. This is necessary because we need to be able to reconcile a TargetAllocator without a collector. This, in effect, starts a Target Allocator which doesn't allocate targets anywhere, but still computes them.
* There's some associated changes to TA ConfigMap generation enabling the above.
**Link to tracking Issue(s):** #2422 
=> Add controller for TargetAllocator CR

.chloggen/container-names.yaml, pkg/instrumentation/podmutator.go
Found through code inspection, the ApacheHttpd, Nginx and SDK injectors do not honour their container-names annotations.
I have changed the annotation used for the container list to match the expected annotation constant which already existed in each case but was unused in the code base.
This is a breaking change if anyone is using the enablement flag with container names for these 3 injectors, which I believe would work as truthy would treat a list of container names as true.
=> fix: fix container names annotations for sdk, apache, nginx

.chloggen/add_all_receiver_defaults.yaml, internal/components/multi_endpoint.go, internal/components/receivers/helpers.go, internal/components/single_endpoint.go, tests/e2e/smoke-targetallocator/00-assert.yaml, tests/e2e/statefulset-features/00-assert.yaml, tests/e2e/statefulset-features/01-assert.yaml
- Resolves: https://github.com/open-telemetry/opentelemetry-operator/issues/3126
=> set default address for all parsed receivers

cmd/otel-allocator/watcher/promOperator_test.go
The test involves measuring the rate limit for the Prometheus CR watcher , which is difficult to do given the potential timing differences between hosts. I basically just relaxed a lot of the checks - the test now passes if we take a lot longer than expected, and the tested interval is also larger to begin with.
=> Fix flaky target allocator test

.chloggen/native_sidecar.yaml, .github/workflows/e2e.yaml, Makefile, pkg/featuregate/featuregate.go, pkg/sidecar/pod.go, pkg/sidecar/pod_test.go, tests/e2e-native-sidecar/00-assert.yaml, tests/e2e-native-sidecar/00-install.yaml, tests/e2e-native-sidecar/chainsaw-test.yaml
=> add featuregate for k8s 1.28 native sidecar container

.chloggen/inst-tls.yaml, apis/v1alpha1/instrumentation_types.go, bundle/community/manifests/opentelemetry-operator.clusterserviceversion.yaml, bundle/community/manifests/opentelemetry.io_instrumentations.yaml, bundle/openshift/manifests/opentelemetry-operator.clusterserviceversion.yaml, bundle/openshift/manifests/opentelemetry.io_instrumentations.yaml, config/crd/bases/opentelemetry.io_instrumentations.yaml, docs/api.md, tests/e2e-instrumentation/instrumentation-java-tls/00-install-instrumentation.yaml
This PR aligns instrumentation TLS options with collector config: 
```yaml
receivers:
otlp:
protocols:
grpc:
endpoint: 0.0.0.0:4317
tls:
cert_file: /otelcol-certs/tls.crt
key_file: /otelcol-certs/tls.key
http:
endpoint: 0.0.0.0:4318
tls:
cert_file: /otelcol-certs/tls.crt
key_file: /otelcol-certs/tls.key
```
=> Align insrumentation TLS config with collector

tests/e2e-openshift/export-to-cluster-logging-lokistack/chainsaw-test.yaml, tests/e2e-openshift/export-to-cluster-logging-lokistack/install-loki.yaml
Update the test to detect storageclass available on the cluster. 
```
% oc get storageclasses.storage.k8s.io 
NAME                     PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ssd-csi                  pd.csi.storage.gke.io   Delete          WaitForFirstConsumer   true                   3h56m
standard-csi (default)   pd.csi.storage.gke.io   Delete          WaitForFirstConsumer   true                   3h56m
--- PASS: chainsaw/export-to-cluster-logging-lokistack (192.23s)
PASS
Done.
```
=> [Chore] Update test export-to-cluster-logging-lokistack to detect storageclass

pkg/collector/upgrade/suite_test.go, pkg/collector/upgrade/upgrade.go, pkg/collector/upgrade/v0_104_0_test.go, pkg/collector/upgrade/v0_105_0_test.go, pkg/collector/upgrade/v0_15_0_test.go, pkg/collector/upgrade/v0_19_0_test.go, pkg/collector/upgrade/v0_24_0_test.go, pkg/collector/upgrade/v0_31_0_test.go, pkg/collector/upgrade/v0_36_0_test.go, pkg/collector/upgrade/v0_38_0_test.go, pkg/collector/upgrade/v0_39_0_test.go, pkg/collector/upgrade/v0_41_0_test.go, pkg/collector/upgrade/v0_43_0_test.go, pkg/collector/upgrade/v0_56_0_test.go, pkg/collector/upgrade/v0_57_2_test.go, pkg/collector/upgrade/v0_61_0_test.go, pkg/collector/upgrade/v0_9_0_test.go
**Description:** Fixes a bug in the upgrade testing that ran all the upgrades despite a version being set. This will now let us run each upgrades in isolation (future upgrades will not effect the current one.) i.e. a test for 0.9.0 would have to take 0.15.0 into account, this is no longer the case.
=> Fix upgrade testing

.github/workflows/reusable-operator-hub-release.yaml, README.md, RELEASE.md
**Description:** Promote @iblancasa to promoter :tada:
=> Promote iblancasa to approvers

.chloggen/3330-python-otel-logs-exporter.yaml, pkg/instrumentation/podmutator_test.go, pkg/instrumentation/python.go, pkg/instrumentation/python_test.go, pkg/instrumentation/sdk_test.go, tests/e2e-instrumentation/instrumentation-python-multicontainer/01-assert.yaml, tests/e2e-instrumentation/instrumentation-python-multicontainer/02-assert.yaml, tests/e2e-instrumentation/instrumentation-python/01-assert.yaml, tests/e2e-multi-instrumentation/instrumentation-multi-multicontainer-go/02-assert.yaml, tests/e2e-multi-instrumentation/instrumentation-multi-multicontainer/01-assert.yaml
Set `OTEL_LOGS_EXPORTER` to `otlp` to match the other signals. Logging is still disabled because it requires `OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED` set to true but that's a bigger change and may require a discussion.
- Resolves: none
**Testing:**
make test
=> Set OTEL_LOGS_EXPORTER for python

.github/workflows/e2e.yaml, Makefile
=> Update chainsaw in makefile

.chloggen/default_telemetry_settings.yaml, apis/v1beta1/collector_webhook_test.go, apis/v1beta1/config.go, apis/v1beta1/config_test.go, internal/manifests/collector/container.go, internal/manifests/collector/service.go, pkg/collector/upgrade/upgrade_test.go, pkg/collector/upgrade/v0_111_0.go, pkg/collector/upgrade/v0_111_0_test.go, pkg/collector/upgrade/versions.go, tests/e2e-multi-instrumentation/instrumentation-multi-multicontainer-go/02-assert.yaml, tests/e2e-multi-instrumentation/instrumentation-multi-multicontainer/01-assert.yaml, tests/e2e-ta-collector-mtls/ta-collector-mtls/00-assert.yaml, tests/e2e-targetallocator/targetallocator-features/00-assert.yaml, tests/e2e-targetallocator/targetallocator-kubernetessd/00-assert.yaml, tests/e2e-targetallocator/targetallocator-prometheuscr/00-assert.yaml, tests/e2e/managed-reconcile/02-assert.yaml, tests/e2e/multiple-configmaps/00-assert.yaml, tests/e2e/smoke-targetallocator/00-assert.yaml, tests/e2e/statefulset-features/00-assert.yaml, tests/e2e/statefulset-features/01-assert.yaml, tests/e2e/versioned-configmaps/00-assert.yaml, tests/e2e/versioned-configmaps/01-assert.yaml
=> v1beta1: apply telemetry config defaults in webhook

.chloggen/nodejs-ibm-platforms.yaml, .github/workflows/publish-autoinstrumentation-nodejs.yaml
=> Add nodejs auto-instrumentation support for linux/s390x,linux/ppc64le

Makefile
controller-tools and envtest were installed in a different way than other tools for no good reason. Fix this. I think this is the main reason for weird CI issues in #3360.
=> Install all tools using the same macro

.chloggen/ta-no-root.yaml, cmd/otel-allocator/Dockerfile
**Description:**  Changes the TA image to match what is done for the main operator image
- Resolves: #3378 
=> target allocator don't run as root

.chloggen/1814-java-configmap.yaml, config/manager/kustomization.yaml, pkg/instrumentation/javaagent.go, pkg/instrumentation/javaagent_test.go, pkg/instrumentation/sdk.go, tests/e2e-instrumentation/instrumentation-java-multicontainer/01-assert.yaml, tests/e2e-instrumentation/instrumentation-java-multicontainer/02-assert.yaml, tests/e2e-instrumentation/instrumentation-java-other-ns/03-assert.yaml, tests/e2e-instrumentation/instrumentation-java-tls/01-assert.yaml, tests/e2e-instrumentation/instrumentation-java/01-assert.yaml, tests/e2e-instrumentation/instrumentation-java/01-install-app.yaml, tests/e2e-multi-instrumentation/instrumentation-multi-multicontainer/01-assert.yaml
Supersedes #3373
This PR is much simpler it does not require fetching configmaps/secrets. 
If the `JAVA_TOOL_OPTIONS` is set (e.g. from configmap the operator sets another `JAVA_TOOL_OPTIONS=$(JAVA_TOOL_OPTIONS) -javaagent`
- Resolves: #1814 
=> Support configuring java runtime from configmap or secret (env.valueFrom)

.chloggen/3384-build-musl-python-autoinstrumentation.yaml, autoinstrumentation/python/Dockerfile
As discussed [here](https://github.com/open-telemetry/opentelemetry-operator/pull/3332#discussion_r1812285084) this introduce in the python image autoinstrumentation built from a musl container.
This is a prerequisite to actually add support for an annotation to use the musl based instrumentation instead of the default glibc one: https://github.com/open-telemetry/opentelemetry-operator/pull/3332
- Refs: #2264 
**Testing:** image builds fine
=> autoinstrumentation: install musl based autoinstrumentation in Python Docker image

tests/e2e-openshift/must-gather/assert-install-app.yaml, tests/e2e-openshift/must-gather/assert-install-target-allocator.yaml, tests/e2e-openshift/must-gather/chainsaw-test.yaml, tests/e2e-openshift/must-gather/check_must_gather.sh, tests/e2e-openshift/must-gather/install-app.yaml, tests/e2e-openshift/must-gather/install-collector-sidecar.yaml, tests/e2e-openshift/must-gather/install-instrumentation.yaml, tests/e2e-openshift/must-gather/install-target-allocator.yaml, tests/e2e-openshift/otlp-metrics-traces/00-install-jaeger.yaml, tests/e2e-openshift/otlp-metrics-traces/02-otel-metrics-collector.yaml, tests/e2e-openshift/otlp-metrics-traces/chainsaw-test.yaml, tests/e2e-openshift/otlp-metrics-traces/check_must_gather.sh
The PR adds tests for OpenTelemetry Operator must-gather script, which collects troubleshooting data from the operator and CR instances. 
```
--- PASS: chainsaw (89.11s)
--- PASS: chainsaw/otlp-metrics-traces (89.11s)
--- PASS: chainsaw/must-gather (76.85s)
PASS
- Passed  tests 2
Done.
```
=> [Chore] Test OpenTelemetry must-gather script

.chloggen/3380-ta-serviceaccount-check.yaml, apis/v1alpha1/targetallocator_webhook.go, apis/v1alpha1/targetallocator_webhook_test.go, apis/v1beta1/collector_webhook.go, apis/v1beta1/collector_webhook_test.go, apis/v1beta1/targetallocator_rbac.go, internal/rbac/format.go, internal/rbac/format_test.go
Permission check fixed for the serviceaccount of the target allocator.
If the `opentelemetrycollector.spec.targetAllocator.serviceAccount` is not set, the operator 
checks the `system:serviceaccount:default:<EMPTY SA NAME>` serviceaccount instead of [the generated serviceaccount name](https://github.com/open-telemetry/opentelemetry-operator/blob/22e8c06f20f0be6eee1df3e139040240cfa13f07/internal/manifests/targetallocator/serviceaccount.go#L28-L32).
```
Warning: missing the following rules for networking.k8s.io/ingresses: [get,system:serviceaccount:default:,list,system:serviceaccount:default:,watch,system:serviceaccount:default:]
Warning: missing the following rules for nodes: [get,system:serviceaccount:default:,list,system:serviceaccount:default …
```
=> Permission check fixed for the serviceaccount of the target allocator

README.md, RELEASE.md, docs/compatibility.md
Add a compatibility document and move existing content from the README there. I wanted to add the Kubernetes support policy, looked at how other projects do this, and decided it'd be better to have everything in a dedicated document. Let me know what you think.
=> Add a separate compatibility document

README.md, docs/compatibility.md
- Resolves: https://github.com/open-telemetry/opentelemetry-operator/issues/2757
=> docs: outline go support policy

.github/workflows/e2e.yaml, Makefile, bundle/community/manifests/opentelemetry-operator.clusterserviceversion.yaml, bundle/openshift/manifests/opentelemetry-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/builder_test.go, controllers/common.go, controllers/opentelemetrycollector_controller.go, controllers/reconcile_test.go, controllers/suite_test.go, controllers/targetallocator_controller.go, controllers/targetallocator_reconciler_test.go, internal/manifests/collector/collector.go, internal/manifests/collector/targetallocator_test.go, internal/manifests/mutate.go, main.go, pkg/featuregate/featuregate.go
Currently when the target allocator is enabled on the collector CR, the collector reconciler generates the target allocator manifests directly. This PR introduces a feature flag that causes it to generate a Target Allocator CR instead, and lets the Target Allocator reconciler take care of the rest.
All the changes are gated behind the flag, including actually enabling the TA controller and webhook. Users who don't set the flag are completely unaffected.
I'm not adding a changelog entry for this, because it's only really meant for testing. I'll add the entry alongside the documentation when we actually enable the controller and webhook unconditionally.
- Related to: #2422
**Testing:**
Added: 
* new unit tests
* new builder tests for cases …
=> Generate only TargetAllocator CR from Collector CR

cmd/otel-allocator/benchmark_test.go, cmd/otel-allocator/target/discovery.go
Add a benchmark for the whole scrape target processing pipeline in the target allocator. I'd like to make some changes to this pipeline in subsequent PRs that will improve its performance, and wrote this benchmark to measure the improvement. I did my best to use realistic data, and the labels in the benchmark are taken directly from a real production cluster.
Current output is as follows on my machine:
```
goos: linux
goarch: amd64
pkg: github.com/open-telemetry/opentelemetry-operator/cmd/otel-allocator
cpu: AMD Ryzen 9 7950X3D 16-Core Processor          
BenchmarkProcessTargets/per-node-32            	      14	  79449090 ns/op	47902082 B/op	  132380 allocs/op
BenchmarkProcessTargets/per-node-32            	      14	  80049443 ns/op	47898982 B/op	  132376 allocs/op …
```
=> Add a benchmark for the whole targets pipeline

cmd/otel-allocator/server/bench_test.go, cmd/otel-allocator/server/server.go, cmd/otel-allocator/server/server_test.go, cmd/otel-allocator/target/target.go
Use a different struct for serializing HTTP server output than we use for internally representing targets. Out internal target struct should only hold the information necessary for target allocation, it doesn't need to concern itself with what the HTTP endpoints ultimately output. I removed the JSON tags from the struct, and introduced a separate struct used exclusively by the server.
As a result, we save some memory on target generation and allocation, but introduce additional allocations for the HTTP endpoint. Given that in larger clusters, the latter accounts for the vast majority of target allocator runtime, I think this is a worthwhile trade.
Benchstat doesn't show much of a difference:
```
goos: linux
goarch: amd64
pkg: github.com/open-telemetry/opentelemetry-operator/cmd/otel-alloca …
```
=> Use a different struct for scrape target serialization

.github/workflows/e2e.yaml, Makefile, apis/v1beta1/collector_webhook.go, apis/v1beta1/collector_webhook_test.go, controllers/opentelemetrycollector_controller.go, controllers/suite_test.go, controllers/targetallocator_controller.go, controllers/targetallocator_reconciler_test.go, main.go, pkg/constants/env.go, tests/e2e-targetallocator-cr/targetallocator-label/00-assert.yaml, tests/e2e-targetallocator-cr/targetallocator-label/00-install.yaml, tests/e2e-targetallocator-cr/targetallocator-label/01-add-ta-label.yaml, tests/e2e-targetallocator-cr/targetallocator-label/01-assert.yaml, tests/e2e-targetallocator-cr/targetallocator-label/02-assert.yaml, tests/e2e-targetallocator-cr/targetallocator-label/02-change-collector-config.yaml, tests/e2e-targetallocator-cr/targetallocator-label/03-assert.yaml, tests/e2e-targetallocator-cr/targetallocator-label/chainsaw-test.yaml
Allow connecting the OpenTelemetryCollector and TargetAllocator CRs by setting a label on the Collector CR.
- Related to: #2422 
**Testing:**
Added some basic unit tests and an e2e test showing how label changes affect the Collector manifests.
=> Allow setting target allocator via label

.github/workflows/changelog.yaml
Looking at some recent failures of the changelog workflow on PRs: https://github.com/open-telemetry/opentelemetry-operator/actions/workflows/changelog.yaml, I noticed the link check doesn't do anything useful. The changelog tool's preview command actually outputs the new changelog segment to stderr (and not stdout as the docs claim), so we're running markdown-link-check on some random chloggen output. 
Furthermore, it doesn't even make sense to check this - what we should do instead is check changelog links during releases, or check links in all of our docs at different points. For now, I'm removing the blocker.
=> [chore] Don't check changelog links in CI

.github/workflows/continuous-integration.yaml
Our lint action produces annoying warnings because it tries to restore the Go module cache unnecessarily. See: https://github.com/open-telemetry/opentelemetry-operator/actions/runs/11745657003 for example.
Instead, only preserve golangci-lint's own cache.
=> Stop unnecessarily caching in the CI lint workflow

tests/e2e-instrumentation/instrumentation-nginx-contnr-secctx/01-install-app.yaml, tests/e2e-instrumentation/instrumentation-nginx-multicontainer/01-install-app.yaml, tests/e2e-instrumentation/instrumentation-nginx-multicontainer/02-install-app.yaml, tests/e2e-instrumentation/instrumentation-nodejs-volume/01-assert.yaml, tests/e2e-instrumentation/instrumentation-nodejs-volume/01-install-app.yaml, tests/e2e-targetallocator/targetallocator-features/00-install.yaml
We have some invalid resource manifests in e2e tests. Kubernetes doesn't care, and just ignores the invalid fields, and so does chainsaw 0.2.8, but chainsaw 0.2.11 errors. Fix these problems so we can upgrade.
=> Fix invalid manifests in e2e tests

cmd/otel-allocator/allocation/allocator_test.go, cmd/otel-allocator/allocation/consistent_hashing.go, cmd/otel-allocator/allocation/per_node_test.go, cmd/otel-allocator/allocation/testutils.go, cmd/otel-allocator/benchmark_test.go, cmd/otel-allocator/prehook/relabel.go, cmd/otel-allocator/prehook/relabel_test.go, cmd/otel-allocator/server/bench_test.go, cmd/otel-allocator/server/server.go, cmd/otel-allocator/server/server_test.go, cmd/otel-allocator/target/discovery.go, cmd/otel-allocator/target/discovery_test.go, cmd/otel-allocator/target/target.go
Store labels for targets in the target allocator the same way Prometheus itself does - as a key+value list of type `labels.Labels` instead of a `model.Labelset` map. The former is what relabelling acts on, so we get to skip the conversion there, and building the list is faster as well. This makes looking up values of specific labels slower, but we don't really do that outside of determining the Node name.
I've modified the benchmark to actually drop half the targets during relabelling to make it more realistic.
Benchstat shows some nice gains:
```
goos: linux
goarch: amd64
pkg: github.com/open-telemetry/opentelemetry-operator/cmd/otel-allocator
cpu: AMD Ryzen 9 7950X3D 16-Core Processor          
│ bench_targets_main.txt │      bench_targets_branch.txt       │
│ …
```
=> Store Prometheus labels as a slice instead of a map

.chloggen/3429.yaml, internal/components/receivers/helpers.go, internal/components/receivers/k8sobjects.go, internal/components/receivers/k8sobjects_test.go, tests/e2e-automatic-rbac/receiver-k8sobjects/00-install.yaml, tests/e2e-automatic-rbac/receiver-k8sobjects/01-assert.yaml, tests/e2e-automatic-rbac/receiver-k8sobjects/01-install.yaml, tests/e2e-automatic-rbac/receiver-k8sobjects/chainsaw-test.yaml
=> Add automatic RBAC creation for k8sobjects receiver

tests/e2e-openshift/multi-cluster/04-assert.yaml
For the multi-cluster test, the Kubernetes job completion status has changed in OCP 4.18 
```
status:
completionTime: "2024-11-21T05:35:45Z"
conditions:
- lastProbeTime: "2024-11-21T05:35:45Z"
lastTransitionTime: "2024-11-21T05:35:45Z"
message: Reached expected number of succeeded pods
reason: CompletionsReached
status: "True"
type: SuccessCriteriaMet
- lastProbeTime: "2024-11-21T05:35:45Z"
lastTransitionTime: "2024-11-21T05:35:45Z"
message: Reached expected number of succeeded pods
reason: CompletionsReached
status: "True"
type: Complete
ready: 0
startTime: "2024-11-21T05:35:41Z"
succeeded: 1
terminating: 0
uncountedTerminatedPods: {} 
```
This condition is not available anymore:
```
status:
conditions:
- status: "True"
type: Complete 
``` …
=> [Chore] Fix assert for multi-cluster test

.chloggen/bump-base-instrumentation-mem-limit.yaml, apis/v1alpha1/instrumentation_webhook.go
- When auto-instrumenting applications, I have noticed that default memory limits are too tight for some languages. This leads to the following:
- Intermitent OOMKilled events in init container when auto-instrumenting python applications. Eventually the pods are able to start.
- OOMKilled events for sidecar containers in go applications. The pods are not able to start.
- 64Mi seems to be enough to fix these issues. While some tweaking by users may still be necessary, the operator should work out-of-the-box for all supported languages.
https://github.com/open-telemetry/opentelemetry-operator/issues/3479
=> Bump base memory requirements for python and go

.chloggen/chore_change-kube-rbac-proxy-image-registry.yaml, bundle/community/manifests/opentelemetry-operator.clusterserviceversion.yaml, bundle/openshift/manifests/opentelemetry-operator.clusterserviceversion.yaml, config/default/manager_auth_proxy_patch.yaml, tests/e2e-upgrade/upgrade-test/opentelemetry-operator-v0.86.0.yaml
This pull request updates the kube-rbac-proxy dependency to use the image hosted on quay.io/brancz/kube-rbac-proxy.
Why is this change necessary? 
- 	[Deprecation](https://cloud.google.com/artifact-registry/docs/transition/prepare-gcr-shutdown) of gcr.io: Images hosted under gcr.io will no longer be available after March 18, 2025.
- 	[Announcement from kubebuilder](https://book.kubebuilder.io/reference/metrics#metrics)
What does this PR do?
-  Replaces references to gcr.io/kubebuilder/kube-rbac-proxy with quay.io/brancz/kube-rbac-proxy.
=> chore: replace gcr.io for kube-rbac-proxy image

tests/e2e/operator-restart/assert-operator-pod.yaml, tests/e2e/operator-restart/chainsaw-test.yaml
Tests operator pod restart to detect issues like https://github.com/open-telemetry/opentelemetry-operator/issues/3446
=> [Chore] Test operator restart

.chloggen/auto_instr_node_up.yaml, autoinstrumentation/nodejs/package.json
This updates the dependencies of the autoinstrumentation for nodejs to the latest available versions.
There have been some important bugfixes for us recently.
=> [autoinstrumentation/nodejs] update node dependencies

controllers/builder_test.go, controllers/reconcile_test.go
We haven't been unsetting feature gates in controller tests after ending the test, leading to them being enabled for the duration of the test suite. In one case, a test actually depended on this fact, and I needed to set the gate in it explicitly.
=> [chore] Fix featuregate usage in controller tests

.chloggen/service-extension.yaml, apis/v1beta1/config.go, internal/components/extensions/helpers.go, internal/manifests/collector/collector.go, internal/manifests/collector/service.go, internal/manifests/collector/service_test.go, internal/naming/main.go, tests/e2e/extension/00-assert.yaml, tests/e2e/extension/00-install.yaml, tests/e2e/extension/chainsaw-test.yaml
The Otel Operator doesn't creates a service for extensions. This will help the operator to create Service for extensions which will be consumed by an Ingress so that users can interact with it directly. This is related to deployment of Jaeger V2 in k8s.
- https://github.com/jaegertracing/jaeger-operator/issues/2717
- https://github.com/open-telemetry/opentelemetry-operator/issues/3460
=> Create service for extensions

.chloggen/revert-3379-otel-configmap.yaml, config/manager/kustomization.yaml, pkg/instrumentation/javaagent.go, pkg/instrumentation/javaagent_test.go, pkg/instrumentation/sdk.go, tests/e2e-instrumentation/instrumentation-java-multicontainer/01-assert.yaml, tests/e2e-instrumentation/instrumentation-java-multicontainer/02-assert.yaml, tests/e2e-instrumentation/instrumentation-java-other-ns/03-assert.yaml, tests/e2e-instrumentation/instrumentation-java-tls/01-assert.yaml, tests/e2e-instrumentation/instrumentation-java/01-assert.yaml, tests/e2e-instrumentation/instrumentation-java/01-install-app.yaml, tests/e2e-multi-instrumentation/instrumentation-multi-multicontainer/01-assert.yaml
Reverts open-telemetry/opentelemetry-operator#3379
closes https://github.com/open-telemetry/opentelemetry-operator/issues/3463
=> Revert "Support configuring java runtime from configmap or secret (env.valueFrom)"

Makefile, renovate.json
Add a renovate configuration, enabling a single manager to update tool versions in the Makefile. The updates are enabled by adding a comment above the version declaration in the Makefile, specifying where to look for the dependency and how to update it.
I've ignored operator-sdk for now, because I'm not sure what the upgrade strategy should be there.
#3450 
**Testing:**
I have this configuration active in my [fork](https://github.com/swiatekm/opentelemetry-operator/blob/main/renovate.json). Here's an example of a tool update PR: https://github.com/swiatekm/opentelemetry-operator/pull/71.
=> Update tools using renovate

README.md
Hey, I would like formally request to be made an Maintainer for opentelemetry-operator.
=> Promote frzifus to maintainer

.chloggen/fix_apache-instrumentation-with-lifecycle.yaml, README.md, pkg/instrumentation/apachehttpd.go, pkg/instrumentation/apachehttpd_test.go, tests/e2e-instrumentation/instrumentation-apache-httpd/01-install-app.yaml
Apache instrumentation sidecar needs to remove lifecycle as it's not supported, same as https://github.com/open-telemetry/opentelemetry-operator/issues/2366
fix #3547
=> fix: apache instrumentation with lifecycle

.chloggen/fix_remove-optional-resources.yaml, controllers/common.go, controllers/opentelemetrycollector_controller.go, controllers/opentelemetrycollector_reconciler_test.go, controllers/reconcile_test.go, controllers/suite_test.go, tests/e2e/smoke-deletion/00-assert.yaml, tests/e2e/smoke-deletion/00-install.yaml, tests/e2e/smoke-deletion/01-assert.yaml, tests/e2e/smoke-deletion/01-install.yaml, tests/e2e/smoke-deletion/chainsaw-test.yaml
I've refactored and cleaned up our owned resource tracking:
* I've added a method that returns all the tracked resources for the reconciler. During registration, we loop over that list.
* To be able to easily find the owned resources, I added an index with a custom field, similar to what the [kubebuilder docs](https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller.go) suggest. This makes test setup more annoying, as we need to make sure to use the caching client in controller tests, but makes the code much more robust.
* We now track ownership of all namespaced resources instead of just a subset of them. This way we actually delete a target allocator Deployment if it's disabled in …
=> Fix optional resource deletion for collector CR

controllers/opentelemetrycollector_controller.go, controllers/reconcile_test.go, controllers/suite_test.go
Fix a flaky controller test. I'm still not sure why it can take so long for this test to see that the ConfigMap was deleted, but it is a fact of life. 30 seconds looks like enough from local tests.
I've also enabled logging for these tests, as it really helps debugging failures. If this is annoying to have in the general unit test output, then maybe we can run these in a separate step?
=> Fix flaky controller tests

controllers/reconcile_test.go
#3560 wasn't enough. I reverted those changes, as they didn't really help and just made the code more complex for no benefit.
Kubernetes creation timestamps only have a seconds-level precision. The ConfigMap versioning feature for collectors deleted the oldest ConfigMaps. For the test to work correctly, we need to wait at least 1 second between CR changes.
=> Fix flaky controller test for versioned ConfigMaps

go.mod
This is because go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp 1.33.0 requires it. This would unblock #3551.
=> [chore] Bump required Go version to 1.22.7

cmd/operator-opamp-bridge/agent/agent.go, cmd/operator-opamp-bridge/agent/agent_test.go, cmd/operator-opamp-bridge/agent/testdata/basic.yaml, cmd/operator-opamp-bridge/agent/testdata/updated.yaml
Kubernetes (and Go in general) allow for signed unix timestamps representing dates before 01-01-1970. However, OpAMP only accepts unsigned timestamps. Until now, opamp bridge simply assumed the conversion could always be carried out. This change instead returns errors when either the bridge or the respective K8s resources have negative Unix timestamps.
Unblocks #3538 and building the operator with Go 1.23 by addressing gosec errors.
=> Fix timestamp conversion in opamp bridge

renovate.json
This should always be the latest version of Go, but should also be explicitly pinned at least at the minor level. Renovate can do this for us, and the maintenance burden of merging the update PRs should be minimal.
- Resolves: https://github.com/open-telemetry/opentelemetry-operator/issues/3450
**Testing:**
Tested on my fork, here's an example update PR: https://github.com/swiatekm/opentelemetry-operator/pull/70.
=> Update Go version used in the CI using renovate

tests/e2e-openshift/export-to-cluster-logging-lokistack/check_logs.sh, tests/e2e-openshift/export-to-cluster-logging-lokistack/otel-collector.yaml
The PR updates the export-to-cluster-logging-lokistack test case to use OTLP/http for sending logs to LokiStack
- Resolves: https://issues.redhat.com/browse/TRACING-5054 
```
--- PASS: chainsaw/export-to-cluster-logging-lokistack (157.85s)
PASS
Done.
```
=> [Chore] Update export-to-cluster-logging-lokistack test case to use otlphttp exporter

cmd/otel-allocator/allocation/allocator.go, cmd/otel-allocator/allocation/strategy.go, cmd/otel-allocator/main.go
Rename the AllocationOption type to Option, and simplify the handling of strategies and the registry in the allocation package.
=> [chore] simplify allocation Option and registry

cmd/otel-allocator/target/discovery.go
Clarify err is only used in the for loop and returns right away, err is never returned by the last instruction.
=> [chore] clarify err variable scope

cmd/otel-allocator/allocation/allocator.go
Apply go best practice to avoid assigning an empty slice.
=> [chore] do not initialize empty slices

internal/openshift/dashboards/dashboards.go
Unless this type is meant to be used in an API, best to unexport it.
=> [chore] unexport type

internal/status/opampbridge/handle.go, internal/status/targetallocator/handle.go
The TODO points to an issue that is marked as completed, hence removing the line.
=> [chore] remove TODO

cmd/otel-allocator/collector/collector.go
Set the map capacity to avoid resizing which is done by in-memory copy.
=> [chore] initialize the map with a given length to avoid memory copy 

.github/workflows/shellcheck.yaml
add shellcheck to CI to check .ci and hack folders.
Fixes #3647
=> [chore] add shellcheck to CI

renovate.json, tests/e2e-openshift/Dockerfile, tests/e2e-openshift/scrape-in-cluster-monitoring/create-clusterrolebinding.yaml
Update the Chainsaw version to the latest 0.2.12 for the OpenShift CI job runs.
=> [Chore] Update Chainsaw version

.chloggen/3452.yaml, apis/v1beta1/config.go, apis/v1beta1/config_test.go, apis/v1beta1/testdata/issue-3452.yaml
=> Fix defaulting a component with empty value

cmd/otel-allocator/server/bench_test.go, cmd/otel-allocator/server/server.go
jsoniter is no longer maintained; this PR switches over to github.com/goccy/go-json
=> [chore] change JSON marshaler to goccy-json

docs/api.md, docs/api/README.md
- Thanks again for solving https://github.com/open-telemetry/opentelemetry.io/issues/6200 by refactoring the API docs.
- This PRs suggests a few copyedits to the API pages:
- Avoids the use of "here" as link text.
- Adds "API reference" back into the (new) page title.
/cc @open-telemetry/docs-maintainers
=> [docs] API reference copyedits

internal/components/extensions/healthcheckv1.go, internal/components/extensions/healthcheckv1_test.go, internal/components/extensions/helpers.go, internal/components/extensions/helpers_test.go
Unexport all that can be unexported, and simplify the code overall.
=> [chore] simplify extension code

.chloggen/cap-urllib3-for-py38-support.yaml, autoinstrumentation/python/requirements.txt
Adds an upper version limit to `urllib3` for Python auto-instrumentation. [Python OTLP HTTP exporter](https://github.com/open-telemetry/opentelemetry-operator/blob/main/autoinstrumentation/python/requirements.txt#L4) depends on [requests ~= 2.7](https://github.com/open-telemetry/opentelemetry-python/blob/main/exporter/opentelemetry-exporter-otlp-proto-http/pyproject.toml#L37) and that depends on ["urllib3>=1.21.1,<3"](https://github.com/psf/requests/blob/main/setup.py#L39). [urllib 2.3.0](https://github.com/urllib3/urllib3/releases/tag/2.3.0) is the latest and drops support of Python 3.8. We are still supporting Python 3.8.
- Resolves: #3616
- Short-term patch for: #3712
**Testing:** …
=> Add urllib3 upper limit to Python auto-instrumentation

.github/workflows/shellcheck.yaml, renovate.json
Update the shellcheck version in CI using renovate.
- Resolves: https://github.com/open-telemetry/opentelemetry-operator/issues/3676
=> Update shellcheck version via renovate

controllers/reconcile_test.go
Another flaky test due to #3494. This one has been causing CI test runs to fail recently, and I think it's the last one in need of a fix. The problem, yet again, is that our controller client now serves GET requests from a cache, so we need to wait for changes to resources in the envtest API Server to propagate before doing checks in tests.
=> Fix another flaky controller test

internal/status/collector/collector.go, internal/status/collector/collector_test.go, internal/status/collector/handle.go
This function is only used inside this package and called once. Unexporting it helps reduce the API to manage.
=> [chore] unexport updateCollectorStatus function

.chloggen/fix-3726.yaml, controllers/targetallocator_controller.go
Add an additional check for installed Prometheus CRDs before owning Service and Pod Monitor resources in the `TargetAllocator` controller.
- Resolves: #3726 
=> fix(target-allocator): check for Prometheus CRDs before watching Service/Pod Monitors

Makefile
golangci-lint stopped publishing the Go package we used to check the available versions. Use the github release instead.
=> Fix renovate config for golangci-lint

renovate.json
The regex was missing a question mark for one of the optional capture groups. It was removed in https://github.com/open-telemetry/opentelemetry-operator/pull/3657, I assume by mistake.
=> Fix renovate custom manager regex

.github/workflows/continuous-integration.yaml, .github/workflows/e2e.yaml, .github/workflows/scorecard.yaml
Give the tools cache a more descriptive name and add a missing step id to the lint step.
It looks like the lint step is currently failing on main due to getting oomkilled, hopefully this will improve it.
=> [chore] Clean up tool caching in CI

.chloggen/feat_ta-namespace-setting.yaml, cmd/otel-allocator/internal/collector/collector.go, cmd/otel-allocator/internal/collector/collector_test.go, cmd/otel-allocator/internal/config/config.go, cmd/otel-allocator/internal/config/config_test.go, cmd/otel-allocator/internal/config/testdata/config_test.yaml, cmd/otel-allocator/internal/config/testdata/pod_service_selector_camelcase_expressions_test.yaml, cmd/otel-allocator/internal/config/testdata/pod_service_selector_camelcase_test.yaml, cmd/otel-allocator/internal/config/testdata/pod_service_selector_expressions_test.yaml, cmd/otel-allocator/internal/config/testdata/pod_service_selector_test.yaml, cmd/otel-allocator/main.go
Currently, setting the collector namespace for the target allocator is done via an environment variable. This variable is read in the module that uses it, rather than during configuration loading. Make this namespace part of the config and only read the environment variable during config loading.
Part of https://github.com/open-telemetry/opentelemetry-operator/issues/3782.
=> [target allocator] Allow setting collector namespace via the config file

go.mod, go.sum
* https://github.com/golang/go/issues/71490
* https://github.com/aquasecurity/trivy-operator/pull/2480
=> Bump golang x/oauth2 to fix CVE-2025-22868

internal/config/main.go
=> cleanup: remove unused defaultAutoDetectFrequency variable

cmd/otel-allocator/internal/config/config.go, cmd/otel-allocator/internal/config/config_test.go, cmd/otel-allocator/internal/watcher/promOperator.go, cmd/otel-allocator/internal/watcher/promOperator_test.go
Currently namespace selectors work correctly in target allocator by accident. By default, Prometheus config generation which we import from prometheus-operator only watches the Prometheus CR namespace for ServiceMonitors. We don't set that, and it just so happens that the config generation code treats that as "all namespaces". This is not the case anymore in newer versions of prometheus-operator, and so we are forced to fix this problem.
This PR explicitly sets default selectors to "all namespaces" in the target allocator config. We also set our internal Prometheus CR namespace to the collector namespace. This doesn't change anything by default, but it makes target allocator behave more similarly to Prometheus.
Part of …
=> Refactor namespace selector handling in target allocator

cmd/otel-allocator/benchmark_test.go, cmd/otel-allocator/internal/allocation/allocator.go, cmd/otel-allocator/internal/allocation/allocator_test.go, cmd/otel-allocator/internal/allocation/least_weighted_test.go, cmd/otel-allocator/internal/allocation/per_node_test.go, cmd/otel-allocator/internal/allocation/strategy.go, cmd/otel-allocator/internal/allocation/testutils.go, cmd/otel-allocator/internal/prehook/prehook.go, cmd/otel-allocator/internal/prehook/relabel.go, cmd/otel-allocator/internal/prehook/relabel_test.go, cmd/otel-allocator/internal/server/mocks_test.go, cmd/otel-allocator/internal/server/server_test.go, cmd/otel-allocator/internal/target/discovery.go, cmd/otel-allocator/internal/target/discovery_test.go, cmd/otel-allocator/internal/target/target.go
Instead of hashing scrape targets when they're received from service discovery, wait until the allocator actually needs the hash. This has the following benefits
* We can avoid calculating hashes for targets filtered out by relabeling.
* We hold targets in a slice, which is more performant.
* It becomes easier to solve issues which rely on accessing post-relabelling target state, like #3617.
Makes it much easier to resolve #3617.
**Testing:**
Existing unit and e2e tests suffice.
=> Delay hashing scrape targets

versions.txt
PHP was recently added to [versions.txt](https://github.com/open-telemetry/opentelemetry-operator/blob/main/versions.txt#L37), which is great for progressing towards expanding language support. However, I’d like to keep versions.txt focused on features that are currently available in the operator.
Our downstream project relies on versions.txt for CI/CD, ensuring that only functional and accessible Docker images are referenced. Since PHP support isn’t ready yet, this is causing CI/CD failures due to the lack of a defined PHP image and the operator not having support for PHP implemented.
To avoid breaking CI/CD, this PR comments out the PHP version until official support is available.
=> Comment out autoinstrumentation-php in versions.txt

cmd/otel-allocator/internal/allocation/allocator.go, cmd/otel-allocator/internal/allocation/strategy.go, cmd/otel-allocator/internal/allocation/strategy_test.go, cmd/otel-allocator/internal/diff/diff.go, cmd/otel-allocator/internal/diff/diff_test.go, cmd/otel-allocator/internal/server/mocks_test.go, cmd/otel-allocator/internal/server/server_test.go, cmd/otel-allocator/internal/target/target.go
We use a (relatively long) string as our target hash for no good reason in the target allocator. Since what we're really hashing are labels, and these come with a built-in hash method that returns a uint64, we use that instead. This gives some impressive performance benefits for such a simple change:
```
goos: linux
goarch: amd64
pkg: github.com/open-telemetry/opentelemetry-operator/cmd/otel-allocator
cpu: AMD Ryzen 9 7950X3D 16-Core Processor          
│ bench_main.txt │        bench_branch_hash.txt        │
│     sec/op     │   sec/op     vs base                │
ProcessTargets/per-node/1000-32                                   1.058m ± 3%   1.015m ± 3%   -4.12% (p=0.000 n=10)
ProcessTargets/least-weighted/1000-32                             1.064m ± 0%   1.015m ± 1%   -4.60% (p=0.000 …
```
=> [target allocator] Use a uint64 hash instead of a string

.chloggen/ta_not_assign_targets_to_bad_collectors.yaml, cmd/otel-allocator/internal/collector/collector.go, cmd/otel-allocator/internal/collector/collector_test.go, cmd/otel-allocator/internal/config/config.go, cmd/otel-allocator/main.go
Ideally, TargetAllocator should not assign targets to an unhealthy pod that is not ready for accepting traffic.
By discussing with Mikolaj in [#3781](https://github.com/open-telemetry/opentelemetry-operator/issues/3781), we believe that it will be a good idea to NOT assign targets to an unhealthy collector pod that has been staying in the bad state for a grace period of `30s` or something.
Note that the `unhealthy` here not only necessarily means `Pod Phase is non-Running`, but more of saying the pod's `PodCondition Ready is non-True`.
- `Running` is a Pod Phase that is defined as: "The Pod has been bound to a node, and all of the containers have been created. At least one container is still running, or is in the process of starting or restarting."
- `Ready` is a Pod …
=> Do not assign targets to a collector pod that are not Ready for accepting traffic more than a while

Makefile
Currently, we can't pass arguments to the go test command, but it would be useful if we could—for example, `-coverprofile=cover.out` or `-run TestSomeFunc` . To support this, I've added a variable called GOTEST_OPTS to pass the options. Thanks for your review!
N/A
=> Add GOTEST_OPTS for unit tests

cmd/otel-allocator/README.md
* Update Allocator Docs to include Selectors
* Since that Readme is already referencing `opentelemetry.io/v1beta1` I found the information to be missing
* Took me a while to figure it out after visiting the [troubleshooting tips](https://opentelemetry.io/docs/platforms/kubernetes/operator/troubleshooting/target-allocator/#did-you-configure-a-servicemonitor-or-podmonitor-selector)
* Feel like this could help other people who land on that page as well.
* N/A
* Let me know if an issue is needed, I can create one
* Docs Only
* Update Allocator Docs to …
=> Docs: Update Allocator Docs to include Selectors

cmd/otel-allocator/internal/watcher/promOperator_test.go, controllers/reconcile_test.go
I've looked at some recent test failures and I think they mostly come down to timeouts being too short for Github Actions runners. I've increased them, hopefully this'll be enough.
=> Fix some flaky tests by increasing timeouts

.chloggen/feat_update-instrumentation-memory-limits.yaml, apis/v1alpha1/instrumentation_webhook.go, apis/v1alpha1/instrumentation_webhook_test.go
Increase default memory limit for instrumentation init containers to 256Mi. This should help mitigate #3479 while we investigate what's actually going on.
- Mitigates #3479
=> Increase default instrumentation memory limit to 256Mi

cmd/otel-allocator/internal/collector/collector_test.go, cmd/otel-allocator/internal/watcher/promOperator_test.go
Attempt to fix flaky unit tests. I'm fairly confident in the fix to `TestNamespaceLabelUpdate`, as the problem there was the fact that we could get an additional notification before the data was actually ready. The fix to the collector discovery test is a shot in the dark.
=> Fix flaky informer tests

.github/workflows/continuous-integration.yaml, .github/workflows/e2e.yaml, .github/workflows/publish-autoinstrumentation-apache-httpd.yaml, .github/workflows/publish-autoinstrumentation-dotnet.yaml, .github/workflows/publish-autoinstrumentation-java.yaml, .github/workflows/publish-autoinstrumentation-nodejs.yaml, .github/workflows/publish-autoinstrumentation-php.yaml, .github/workflows/publish-autoinstrumentation-python.yaml, .github/workflows/publish-images.yaml, .github/workflows/publish-must-gather.yaml, .github/workflows/publish-operator-bundle.yaml, .github/workflows/publish-operator-opamp-bridge.yaml, .github/workflows/publish-target-allocator.yaml, .github/workflows/release.yaml, .github/workflows/reusable-publish-test-e2e-images.yaml, .github/workflows/scorecard.yaml, .github/workflows/shellcheck.yaml
We don't care much about the underlying runner image, and this way we can avoid having to bump the version ever.
This also unblocks https://github.com/open-telemetry/opentelemetry-operator/pull/3917, where a deprecated ubuntu-20.04 is causing the CI to fail.
=> Run all CI jobs on ubuntu-latest

.github/workflows/e2e.yaml, Makefile
Build container images for e2e tests in a separate step, create an image archive, and then load that into kind before running the test proper.
To facilitate this, I've added a new target for building the archive: `create-image-archive`. The `prepare-e2e` target doesn't directly depend on targets for building container images - this is now done as part of the `load-image-all` target, which does something different depending on whether an archive file is provided.
This change doesn't have that many benefits in itself, but it will let us more easily run e2e tests with instrumentation images built with PR changes.
=> [chore] Build container images once for e2e tests

tests/e2e/smoke-daemonset/00-assert.yaml, tests/e2e/smoke-simplest-v1beta1/00-assert.yaml, tests/e2e/smoke-statefulset/00-assert.yaml, tests/e2e/smoke-statefulset/00-install.yaml
We don't check the status at all in E2E tests, but it's quite easy to do with chainsaw.
=> Check OpenTelemetryCollector status in e2e tests

.chloggen/nikola-jokic_fix-status-replicas.yaml, internal/status/collector/collector.go, internal/status/collector/collector_test.go, tests/e2e/smoke-daemonset/00-assert.yaml
Fixing a bug - the `statusReplicas` field is not being set for the `DaemonSet`.
- Resolves: #3930
**Testing:** Ran tests and confirmed it manually
**Documentation:** Fixing the behavior documented [here](https://github.com/open-telemetry/opentelemetry-operator/blob/02e42e5db45616e982343a87cc6519df1c21578c/apis/v1beta1/opentelemetrycollector_types.go#L300).
=> Fix status replicas

.github/workflows/reusable-publish-test-e2e-images.yaml
https://github.com/open-telemetry/opentelemetry-operator/pull/3870 explicitly set permissions for a bunch of workflows, and then https://github.com/open-telemetry/opentelemetry-operator/pull/3871 added some missing permissions for image publishing. However, it missed the publishing step for E2E test images, resulting in failures like [this one](https://github.com/open-telemetry/opentelemetry-operator/actions/runs/14592777292).
Add the missing permissions.
=> Fix permissions for E2E test image publishing

.chloggen/fix_ta-cmdline-values.yaml, cmd/otel-allocator/internal/config/config.go, cmd/otel-allocator/internal/config/config_test.go, cmd/otel-allocator/internal/config/flags.go, cmd/otel-allocator/internal/config/flags_test.go, cmd/otel-allocator/main.go
Fix the target allocator's config loading priority to reflect our intent. We had a problem where some values were taken from command-line flag defaults even if the flags weren't set, making it impossible to set them through the config file.
To achieve this, I've:
* Set all the defaults in the defaulting function.
* Use flag values only if they're actually set, for flags where this wasn't the case.
* Add tests for the config loading priority.
Partially fixes #3928.
=> [target allocator] Fix config loading priority

tests/test-e2e-apps/golang/Dockerfile, tests/test-e2e-apps/golang/main.go
Update the Golang test app to generate telemetry data.
=> [Chore] Update Golang test app to generate telemetry data

.chloggen/keep_going_if_collector_crd_is_not_present.yaml, internal/autodetect/collector/operator.go, internal/autodetect/main.go, internal/config/config.go, internal/config/config_test.go, internal/config/options.go, internal/controllers/reconcile_test.go, internal/controllers/suite_test.go, main.go
Skip registering the webhook and keep the operator working.
Related to #3568 - after merging this, adding an option to disable watching with the collector CRD is easy.
=> [webhook] do not crash if collector CRD is not present in the cluster

.chloggen/override_with_env.yaml, cmd/otel-allocator/internal/config/config.go, cmd/otel-allocator/internal/config/config_test.go
do not override the config file value of collector namespace if env var is not set
=> [targetallocator] collector namespace overridden by env var

cmd/operator-opamp-bridge/internal/config/config_test.go, internal/manifests/collector/container_test.go, internal/manifests/targetallocator/container_test.go
Test change only. Prefer to use t.Setenv for all env var setting in tests.
=> [chore] use t.Setenv across tests

docs/rfcs/managed.md
RFC for managed operator custom resource.
See #3819
=> [docs] Add RFC for managed CR

.chloggen/fix_ta-volume.yaml, internal/manifests/targetallocator/volume.go, internal/manifests/targetallocator/volume_test.go, tests/e2e-targetallocator-cr/01-assert.yaml, tests/e2e-targetallocator-cr/01-install.yaml
Fixed a bug which caused user-defined volumes for the Target Allocator CR to be ignored. Also fixed an e2e test which failed to catch the issue due to unrelated problems.
- Resolves: #3992 
**Testing:**
Added a unit test and fixed an existing e2e test.
=> [target allocator] Fix user-defined volumes

apis/v1alpha1/targetallocator_types.go, apis/v1alpha1/zz_generated.deepcopy.go
The definition of the Go struct for TargetAllocator lists was incorrect. Interestingly, this doesn't affect the CRD itself, as the notion of a resource list is a built-in feature of the K8s API Server. It only affects the operator's own ability to use these lists, which it currently doesn't do. I noticed this while trying to enable the `operator.collector.targetallocatorcr` flag by default.
=> Fix TargetAllocatorList definition

cmd/operator-opamp-bridge/README.md
Creates a README for the OpAMP Bridge component with an introduction to its responsibilities and usage.
- Resolves: https://github.com/open-telemetry/opentelemetry-operator/issues/4022
Added new README for `cmd/operator-opamp-bridge`.
=> [opamp] Add README for OpAMP Bridge

CONTRIBUTING.md, Makefile
Add a make target to delete the cluster generated by the `start-kind` target.
Add instructions on the CONTRIBUTING.md file to help the end user to clean up their environment after the tests.
- Resolves: #4033
**Testing:**
```
make start-kind
make stop-kind
```
=> [chore] Add stop-kind make target to delete the cluster created by start-kind

main.go
A continuation of #4070
This controller eventually times out when running without the CRD present and kills the manager.
=> Do not register reconciler if CRD is not present

.github/workflows/continuous-integration.yaml, Makefile, internal/controllers/reconcile_test.go
`TestOpenTelemetryCollectorReconciler_RemoveDisabled` is the source of most of our flaky failures. This change attempts to fix it, as well as the upgrade test. I'm not actually sure what the root cause of the failures is, but the generic improvement I made in this PR appears to have fixed it. I've restarted the CI tests over 10 times and haven't gotten a failure.
I've also added `gotestsum` to the tools list in the Makefile.
=> Fix flaky reconcile tests

tests/e2e/operator-metrics/chainsaw-test.yaml
The operator Helm Chart runs the operator e2e tests in its CI. However, it uses different labels for the operator Pod, and the test fails. Relax the label selector we use in the operator metrics test so it can pass with the default Helm Chart installation.
See https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1728 for an example of the failure.
=> Update the operator metrics test to pass for the Helm Chart

.chloggen/remove_invalid_featuregate_refs.yaml, apis/v1alpha1/opentelemetrycollector_types.go, apis/v1beta1/opentelemetrycollector_types.go, bundle/community/manifests/opentelemetry-operator.clusterserviceversion.yaml, bundle/openshift/manifests/opentelemetry-operator.clusterserviceversion.yaml, config/manifests/community/bases/opentelemetry-operator.clusterserviceversion.yaml, config/manifests/openshift/bases/opentelemetry-operator.clusterserviceversion.yaml, config/overlays/openshift/manager-patch.yaml, docs/api/opentelemetrycollectors.md, docs/api/targetallocators.md
The PR fixes the failing operator install due to the operator.observability.prometheus feature flag by removing the flag from the bundle and remove the references for the flag from API and docs. 
```
% operator-sdk run bundle --timeout=5m --security-context-config=restricted quay.io/rhn_support_ikanse/opentelemetry-operator-bundle:latest
INFO[0034] Creating a File-Based Catalog of the bundle "quay.io/rhn_support_ikanse/opentelemetry-operator-bundle:latest" 
INFO[0038] Generated a valid File-Based Catalog         
INFO[0044] Created registry pod: quay-io-rhn-support-ikanse-opentelemetry-operator-bundle-latest 
INFO[0044] Created CatalogSource: opentelemetry-operator-catalog 
INFO[0045] OperatorGroup "operator-sdk-og" created      
INFO[0045] …
```
=> Remove operator.observability.prometheus feature gate flag from OpenShift bundle and remove feature flag references.

tests/e2e-instrumentation/instrumentation-python/01-install-app.yaml, tests/e2e-instrumentation/instrumentation-python/app-request.yaml, tests/e2e-instrumentation/instrumentation-python/chainsaw-test.yaml, tests/e2e-instrumentation/instrumentation-python/check-telemetry-data.yaml, tests/e2e-instrumentation/instrumentation-python/wait-for-telemetry-data.yaml, tests/step-templates/openshift-namespace-annotations.yaml
Python instrumentation libraries currently support Python 3.9. Run our instrumentation e2e tests on a test app running Python 3.9 to verify that our dependency manifest is valid for that version.
I've cleaned up the e2e test in question by using chainsaw step templates. We can do this for a lot more of our tests - let this PR serve as an example for future efforts.
- Relates: https://github.com/open-telemetry/opentelemetry-operator/issues/3712
=> Run python instrumentation tests on older Python version

cmd/otel-allocator/internal/watcher/promOperator.go, cmd/otel-allocator/internal/watcher/promOperator_test.go
Stop pretending to be Prometheus 2.55.1 when generating the Scrape-Configs using PrometheusCRs.
I mentioned in https://github.com/open-telemetry/opentelemetry-operator/pull/4000#issuecomment-3107764602 that this hardcoded version number results in some ugly warnings. I don't know if there are any worse consequences than just the warnings.
Anyway, @swiatekm agreed that this hardcoded version should be removed in https://github.com/open-telemetry/opentelemetry-operator/pull/4000#issuecomment-3107912757.
**Link to tracking Issue(s):** https://github.com/open-telemetry/opentelemetry-operator/pull/4000#issuecomment-3107912757.
- Resolves: https://github.com/open-telemetry/opentelemetry-operator/pull/4000#issuecomment-3107764602
**Testing:** …
=> fix(target-allocator): Stop pretending to be Prometheus 2.55.1

.chloggen/autoscaler-maxreplica-check.yaml, apis/v1beta1/collector_webhook.go, apis/v1beta1/collector_webhook_test.go
bugfix - added a validation check when minReplica is set but maxReplica is not. This returns an error and does not allow the number of replicas to be updated.
- Resolves: #4160
**Testing:** 
- added unit test for this change
- also tested the fix locally, by trying to update autoscaler without maxReplica when minReplica is set:
```
error: opentelemetrycollectors.opentelemetry.io "simplest" could not be patched: admission webhook "vopentelemetrycollectorcreateupdatebeta.kb.io" denied the request: spec.maxReplica must be set when spec.minReplica is set
```
=> bugfix: validate maxReplica when minReplica is set for autoscaler

.chloggen/rbac_for_config.extensions.k8s_observer.yaml, apis/v1beta1/config.go, internal/components/extensions/helpers.go, internal/components/extensions/k8sobserver.go, internal/components/extensions/k8sobserver_test.go, internal/manifests/collector/rbac_test.go, internal/manifests/collector/testdata/rbac_k8sobserver_extension.yaml, internal/manifests/collector/testdata/rbac_k8sobserver_partial.yaml
This pull request adds support for generating RBAC rules for the k8s_observer extension in the OpenTelemetry Collector when used in the operator. The change addresses the issue where the collector lacked necessary permissions to list and watch Kubernetes resources 
- Resolves: #4113
Added  tests in `internal/components/extensions/k8sobserver_test` & `internal/manifests/collector/rbac_test.go`
=> [chore] Rbac for config.extensions.k8s observer

.chloggen/rm_opencensus_receiver_parsing.yaml, internal/components/receivers/helpers.go, internal/components/receivers/single_endpoint_receiver_test.go
remove opencensus receiver from parsing logic
- Resolves: #4239
=> remove opencensus receiver from parsing logic

.chloggen/remove-cert-manager-annotations.yaml, apis/v1alpha1/instrumentation_webhook.go, bundle/community/manifests/opentelemetry-operator.clusterserviceversion.yaml, bundle/community/manifests/opentelemetry.io_opampbridges.yaml, bundle/community/manifests/opentelemetry.io_targetallocators.yaml, bundle/openshift/manifests/opentelemetry-operator.clusterserviceversion.yaml, bundle/openshift/manifests/opentelemetry.io_opampbridges.yaml, bundle/openshift/manifests/opentelemetry.io_opentelemetrycollectors.yaml, bundle/openshift/manifests/opentelemetry.io_targetallocators.yaml, config/crd/kustomization.yaml, config/overlays/openshift/kustomization.yaml, config/overlays/openshift/remove-cert-manager-annotations.yaml
It fixes error messages in the cert-manager
```
E0704 15:55:03.868022 1 sources.go:106] "unable to fetch associated certificate" err="Certificate.cert-manager.io \"opentelemetry-operator-serving-cert\" not found" logger="cert-manager" kind="customresourcedefinition" kind="customresourcedefinition" name="opampbridges.opentelemetry.io" certificate="opentelemetry-operator-system/opentelemetry-operator-serving-cert"
E0704 15:55:03.870725 1 sources.go:106] "unable to fetch associated certificate" err="Certificate.cert-manager.io \"opentelemetry-operator-serving-cert\" not found" logger="cert-manager" kind="customresourcedefinition" kind="customresourcedefinition" name="opentelemetrycollectors.opentelemetry.io" …
```
=> Remove unnecessary cert-manager CA annotation from CRDs

.chloggen/api-conversion-resilience.yaml, apis/v1alpha1/convert.go, apis/v1alpha1/convert_test.go, tests/e2e/conversion-webhook-invalid-config/00-assert-created.yaml, tests/e2e/conversion-webhook-invalid-config/00-create-invalid-config.yaml, tests/e2e/conversion-webhook-invalid-config/01-assert-deployment-created.yaml, tests/e2e/conversion-webhook-invalid-config/chainsaw-test.yaml
**Description:** Returns a valid, empty configuration struct in the v1alpha1 conversion webhook rather than returning a failure.
**Link to tracking Issue(s):** #4288
- Resolves: #4288 
**Testing:** Added a few tests with invalid YAML configuration strings to ensure that a valid configuration, and no error, is returned from the webhook.
**Documentation:** None
=> Return an empty, valid configuration struct in v1alpha1 conversion webhook

versions.txt
Bump the otel collector to 0.136.0. This is in preparation for the next release, bumping it earlier to see if the e2e tests pass.
=> Bump default otel collector version to 0.136.0

tests/e2e-instrumentation/instrumentation-apache-httpd/chainsaw-test.yaml, tests/e2e-instrumentation/instrumentation-apache-multicontainer/chainsaw-test.yaml, tests/e2e-instrumentation/instrumentation-dotnet-multicontainer/chainsaw-test.yaml, tests/e2e-instrumentation/instrumentation-dotnet-musl/chainsaw-test.yaml, tests/e2e-instrumentation/instrumentation-dotnet/chainsaw-test.yaml, tests/e2e-instrumentation/instrumentation-go/chainsaw-test.yaml, tests/e2e-instrumentation/instrumentation-java-multicontainer/chainsaw-test.yaml, tests/e2e-instrumentation/instrumentation-java-other-ns/chainsaw-test.yaml, tests/e2e-instrumentation/instrumentation-java-tls/chainsaw-test.yaml, tests/e2e-instrumentation/instrumentation-java/chainsaw-test.yaml, tests/e2e-instrumentation/instrumentation-nginx-contnr-secctx/chainsaw-test.yaml, tests/e2e-instrumentation/instrumentation-nginx-multicontainer/chainsaw-test.yaml, tests/e2e-instrumentation/instrumentation-nginx/chainsaw-test.yaml, tests/e2e-instrumentation/instrumentation-nodejs-multicontainer/chainsaw-test.yaml, tests/e2e-instrumentation/instrumentation-nodejs-volume/chainsaw-test.yaml, tests/e2e-instrumentation/instrumentation-nodejs/chainsaw-test.yaml, tests/e2e-instrumentation/instrumentation-python-multicontainer/chainsaw-test.yaml, tests/e2e-instrumentation/instrumentation-python-musl/chainsaw-test.yaml, tests/e2e-instrumentation/instrumentation-sdk/chainsaw-test.yaml, tests/e2e-multi-instrumentation/instrumentation-multi-multicontainer-go/chainsaw-test.yaml, tests/e2e-multi-instrumentation/instrumentation-multi-multicontainer/chainsaw-test.yaml, tests/e2e-multi-instrumentation/instrumentation-multi-no-containers/chainsaw-test.yaml, tests/e2e-multi-instrumentation/instrumentation-single-instr-first-container/chainsaw-test.yaml, tests/e2e-openshift/must-gather/chainsaw-test.yaml, tests/e2e-targetallocator-cr/chainsaw-test.yaml, tests/e2e-targetallocator/targetallocator-features/chainsaw-test.yaml, tests/step-templates/openshift-namespace-annotations-root.yaml
Move adding openshift namespace annotations in e2e tests to a step template. This removes a lot of unnecessary duplication.
Some tests require the annotation to permit root users. Passing arguments into the template steps was a bit annoying, so I just created two separate steps. We can optimize this further later if we want.
=> Move openshift namespace annotation setup into a step template
