open-telemetry/opentelemetry-operator

.ci/publish-images.sh
=> Change the publishing script to fail the build upon failure

.github/workflows/continuous-integration.yaml
=> Removed codecov until the secret is added to the repository

deploy/olm-catalog/opentelemetry-operator/0.0.2/opentelemetry-operator.v0.0.2.clusterserviceversion.yaml, deploy/olm-catalog/opentelemetry-operator/0.0.2/opentelemetry.io_opentelemetrycollectors_crd.yaml, deploy/olm-catalog/opentelemetry-operator/opentelemetry-operator.package.yaml
=> Added olm-catalog for 0.0.2

.ci/release.sh, opentelemetry.version
=> Added release script

Makefile
=> Changed default zap configuration on 'make run'

README.md, examples/simplest.yaml, opentelemetry.version, pkg/apis/opentelemetry/flagset.go, pkg/upgrade/v0_2_0.go, pkg/upgrade/versions.go
=> Updated OpenTelemetry Collector to 0.2.0

deploy/crds/opentelemetry.io_opentelemetrycollectors_crd.yaml, examples/with-volumes.yaml, pkg/apis/opentelemetry/v1alpha1/opentelemetrycollector_types.go, pkg/apis/opentelemetry/v1alpha1/zz_generated.deepcopy.go, pkg/apis/opentelemetry/v1alpha1/zz_generated.openapi.go, pkg/controller/opentelemetrycollector/reconcile_deployment.go, pkg/controller/opentelemetrycollector/reconcile_deployment_test.go
=> Added support for volumes

README.md
Fixes https://github.com/open-telemetry/opentelemetry-operator/issues/18
=> Fix example to reference most recent collector image

pkg/parser/receiver_generic_test.go, pkg/parser/receiver_signalfx.go
Related to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/351
Signed-off-by: Gary Brown <gary@brownuk.com>
=> Fix signalfx default port

Makefile, main.go
=> Allow logger to be configured via CLI flags

config/samples/exporter-with-tls.yaml
=> Added an example for connecting to a TLS-secured Jaeger collector

internal/config/main_test.go, internal/config/options.go, main.go
=> Fixed the notation for config options

api/v1alpha1/opentelemetrycollector_types.go, api/v1alpha1/opentelemetrycollector_webhook.go, config/crd/bases/opentelemetry.io_opentelemetrycollectors.yaml, controllers/opentelemetrycollector_controller_test.go, pkg/collector/reconcile/deployment.go
=> Set default mode via webhook

config/rbac/role.yaml, controllers/opentelemetrycollector_controller.go, pkg/collector/collector_suite_test.go, pkg/collector/container.go, pkg/collector/container_test.go, pkg/collector/daemonset.go, pkg/collector/daemonset_test.go, pkg/collector/deployment.go, pkg/collector/deployment_test.go, pkg/collector/labels_test.go, pkg/collector/reconcile/configmap.go, pkg/collector/reconcile/daemonset.go, pkg/collector/reconcile/deployment.go, pkg/collector/reconcile/service.go, pkg/collector/reconcile/serviceaccount.go, pkg/collector/serviceaccount.go, pkg/collector/serviceaccount_test.go, pkg/collector/volume.go, pkg/collector/volume_test.go, pkg/naming/main.go
=> Unified naming and building of core objects

api/v1alpha1/opentelemetrycollector_types.go, config/crd/bases/opentelemetry.io_opentelemetrycollectors.yaml, config/rbac/role.yaml, config/samples/sidecar.yaml, config/webhook/manifests.yaml, internal/podinjector/main.go, internal/podinjector/main_test.go, internal/podinjector/podinjector_suite_test.go, main.go, pkg/collector/reconcile/service.go, pkg/collector/reconcile/serviceaccount.go, pkg/sidecar/annotation.go, pkg/sidecar/annotation_test.go, pkg/sidecar/pod.go, pkg/sidecar/pod_test.go, pkg/sidecar/sidecar_suite_test.go
=> Implemented pod injector webhook

internal/config/main.go
Fixes [https://github.com/open-telemetry/opentelemetry-operator/issues/43](https://github.com/open-telemetry/opentelemetry-operator/issues/43)
=> Use otel/opentelemetry-collector image

versions.txt
=> Use OpenTelemetry Collector v0.11.0

.ci/create-release-github.sh, .ci/publish-bundle-images.sh, .ci/publish-images.sh, .ci/tagAndPushFunc.sh, .github/workflows/release.yaml, .gitignore, CHANGELOG.md, Dockerfile, Makefile, RELEASE.md, config/crd/patches/webhook_in_opentelemetrycollectors.yaml, config/manifests/bases/opentelemetry-operator.clusterserviceversion.yaml, config/manifests/kustomization.yaml, versions.txt
=> Add release script

.github/workflows/release.yaml
=> Add operator-sdk to release workflow

.github/workflows/release.yaml
=> Add kubebuilder to release workflow

README.md
=> Update the readme to include installation of released operator

CHANGELOG.md, versions.txt
=> Bumped OpenTelemetry Collector to v0.12.0

.github/labeler-needs-triage.yaml, .github/workflows/labeler.yml
=> Add labeler, setting 'needs-triage' to all new issues

.github/workflows/labeler.yml
=> Added missing config option to issue-labeler

.github/labeler-needs-triage.yaml
=> regex for issue labeler

.github/mergify.yml
=> Set mergify to dismiss stale reviews

Makefile, pkg/collector/reconcile/deployment.go
=> Small local dev workflow improvements

CODEOWNERS, CONTRIBUTING.md, README.md
=> Add CONTRIBUTING.md

.github/workflows/continuous-integration.yaml, controllers/opentelemetrycollector_controller_test.go, controllers/suite_test.go, internal/config/main.go, internal/config/main_test.go, internal/podinjector/main_test.go, main.go, pkg/autodetect/main_test.go, pkg/collector/container_test.go, pkg/collector/parser/receiver.go, pkg/collector/parser/receiver_test.go, pkg/collector/reconcile/configmap.go, pkg/collector/reconcile/daemonset.go, pkg/collector/reconcile/deployment.go, pkg/collector/reconcile/service.go, pkg/collector/reconcile/serviceaccount.go, pkg/collector/upgrade/noop.go, pkg/collector/upgrade/upgrade.go
=> Add golangci-lint to CI

.github/mergify.yml, .github/workflows/continuous-integration.yaml
This is GitHub's action for CodeQL, for security analysis.
=> Add CodeQL check

.github/mergify.yml
=> Fix check names in mergify config

Makefile
=> Use latest stable cert-manager

CONTRIBUTING.md, api/v1alpha1/groupversion_info.go, config/README.md, controllers/opentelemetrycollector_controller.go, internal/config/main.go, internal/podinjector/main.go, internal/version/main.go, pkg/autodetect/main.go, pkg/collector/adapters/config_from.go, pkg/collector/parser/receiver.go, pkg/collector/reconcile/opentelemetry.go, pkg/collector/upgrade/upgrade.go, pkg/collector/volume.go, pkg/naming/main.go, pkg/platform/main.go, pkg/sidecar/pod.go
This PR is for issue https://github.com/open-telemetry/opentelemetry-operator/issues/104
Add the package descriptions from [CONTRIBUTING.md](https://github.com/open-telemetry/opentelemetry-operator/blob/master/CONTRIBUTING.md) to the per-package godoc.
Some packages do not contain any Go files, so they are not modified in this PR.
=> Add package godoc from CONTRIBUTING.md

CHANGELOG.md, versions.txt
=> Bumped OpenTelemetry Collector to v0.14.0

.github/mergify.yml
=> Auto-merge dependabot PRs when they pass CI

.github/workflows/release.yaml
=> Bump setup-operator-sdk to v1.0.2

.github/workflows/release.yaml
=> Fix image prefix for release image

.github/workflows/publish-images.yaml
=> Add login step to publishing of images

CHANGELOG.md, RELEASE.md, versions.txt
=> Bumped OpenTelemetry Collector to v0.17.0

.ci/create-release-github.sh
=> Remove OpenShift bundle from release

.github/workflows/publish-images.yaml
=> Adjust container image tags

config/rbac/role.yaml, controllers/opentelemetrycollector_controller.go
=> Add permissions for leases.coordination.k8s.io

CHANGELOG.md, versions.txt
=> Release v0.17.1

.github/workflows/release.yaml, .gitignore, CONTRIBUTING.md, Makefile, RELEASE.md, api/v1alpha1/opentelemetrycollector_types.go, bundle.Dockerfile, bundle/manifests/opentelemetry-operator-controller-manager-metrics-service_v1_service.yaml, bundle/manifests/opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1beta1_clusterrole.yaml, bundle/manifests/opentelemetry-operator-webhook-service_v1_service.yaml, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, bundle/manifests/opentelemetry.io_opentelemetrycollectors.yaml, bundle/metadata/annotations.yaml, config/certmanager/certificate.yaml, config/default/manager_webhook_patch.yaml, config/manifests/bases/opentelemetry-operator.clusterserviceversion.yaml
=> Update operator-sdk to 1.2.0

.github/workflows/e2e.yaml, .gitignore, CONTRIBUTING.md, Makefile, hack/install-kuttl.sh, kuttl-test.yaml, tests/e2e/smoke-simplest/00-assert.yaml, tests/e2e/smoke-simplest/00-install.yaml
=> Add e2e tests

.github/mergify.yml, go.mod
=> Revert change to controller-runtime, require e2e before automatic merge

CHANGELOG.md, versions.txt
=> Bumped OpenTelemetry Collector to v0.18.0

Makefile
Signed-off-by: Granville Schmidt <1246157+gramidt@users.noreply.github.com>
Resolves Issue: #170
=> Fixed testing image from being used in non-test artifacts (fixes #170)

CHANGELOG.md, versions.txt
=> Release 0.18.1

CHANGELOG.md, pkg/collector/upgrade/v0_19_0.go, pkg/collector/upgrade/v0_19_0_test.go, pkg/collector/upgrade/versions.go, tests/e2e/smoke-simplest/00-install.yaml, versions.txt
=> Bumped OpenTelemetry Collector to v0.19.0

.github/workflows/release.yaml
Signed-off-by: sheetalsingala <ssingala@redhat.com>
=> Bump to Operator SDK 1.3.0

README.md
=> Added contributors to the readme, as well as a list of approvers and maintainers

.github/CODEOWNERS, .github/mergify.yml, .github/workflows/continuous-integration.yaml, .github/workflows/e2e.yaml, .github/workflows/publish-images.yaml, README.md, RELEASE.md
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>
=> Update links after master -> main branch change

.github/workflows/release.yaml
=> Bump up operator SDK to 1.4.0

CHANGELOG.md, versions.txt
=> Bump OpenTelemetry Collector to v0.20.0

.github/workflows/continuous-integration.yaml, .github/workflows/e2e.yaml, .github/workflows/release.yaml
=> Use Go 1.15 for the build/test/release

CHANGELOG.md, RELEASE.md, versions.txt
=> Update to collector v0.21.0

CHANGELOG.md, versions.txt
=> Update to collector v0.22.0

CHANGELOG.md, versions.txt
Fixes #231 
Signed-off-by: lastchiliarch <lastchiliarch@163.com>
=> Update to collector v0.23.0

Makefile
=> Bumped cert-manager to v1.1.1

.github/workflows/release.yaml
- bump operator-sdk version to 1.5.0
=> Bump operator-sdk version to 1.6.1

CHANGELOG.md, pkg/collector/upgrade/v0_24_0.go, pkg/collector/upgrade/v0_24_0_test.go, pkg/collector/upgrade/versions.go, versions.txt
=> Update to collector v0.24.0

CHANGELOG.md, versions.txt
Bumps collector to v0.25.0
Resolves #263
=> Update to collector v0.25.0

CHANGELOG.md, versions.txt
Bumps collector to v0.27.0
Fixes #287
=> Update to collector v0.27.0

bundle.Dockerfile, bundle/metadata/annotations.yaml
Remove scorecard test annotations as we don't have any scorecard tests. Update operator-sdk (builder) version in annotations.
=> Fix bundle

CHANGELOG.md, versions.txt
=> Bumps collector to v0.28.0

README.md, RELEASE.md
=> Add v0.28.0 to the compat matrix

README.md, docs/otelcol_cr_spec.md, pkg/collector/container_test.go, tests/e2e/smoke-sidecar/00-install.yaml, tests/e2e/smoke-simplest/00-install.yaml
Add unit, e2e tests for args that are passed from otelcol CR spec to otelcol container args.
fixes: #12
=> Add tests, docs for otelcol container args

CHANGELOG.md, versions.txt
=> Bumps collector version to v0.29.0

README.md, RELEASE.md, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml
=> Small manual adjusts for docs and bundle for v0.29.0

.github/workflows/continuous-integration.yaml, CONTRIBUTING.md, Makefile, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, versions.txt
add CI validation check to make sure all auto-generated files are part of the PR.
fixes: #331
=> Add CI check for auto-generated files

CHANGELOG.md, README.md, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, versions.txt
=> Bumps collector version to v0.30.0

hack/install-kuttl.sh
=> Bump kubectl-kuttl to v0.11.0

bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, config/default/manager_auth_proxy_patch.yaml
Fixes #355 
Update gcr.io/kubebuilder/kube-rbac-proxy to v0.8.0
=> Update gcr.io/kubebuilder/kube-rbac-proxy to v0.8.0

CHANGELOG.md, Makefile, README.md, RELEASE.md, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, versions.txt
=> Bump collector to v0.31.0

.github/workflows/continuous-integration.yaml, .github/workflows/release.yaml, Makefile, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml
=> Bump operator-sdk to v1.10.0

Makefile
=> Update cert-manager to v1.4.3

hack/install-kuttl.sh
=> Bump kuttl to v0.11.1

CHANGELOG.md, README.md, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, versions.txt
=> Update to collector v0.33.0

Makefile
=> Update cert-manager to v1.5.2

pkg/collector/parser/receiver_generic_test.go, pkg/collector/parser/receiver_influxdb.go, pkg/collector/parser/receiver_influxdb_test.go
[Influxdb receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/influxdbreceiver#influxdb-receiver)
Part of #128
=> Add influxdb receiver

pkg/collector/parser/receiver_generic_test.go, pkg/collector/parser/receiver_splunk-hec.go, pkg/collector/parser/receiver_splunk-hec_test.go
[Splunk Hec receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/splunkhecreceiver#splunk-hec-receiver)
Part of #128
=> Add Splunk Hec receiver

pkg/collector/parser/receiver.go
As all these three receivers do not have a default port in their config. I am not adding any new receiver parsers for this set of receivers. 
More details here:
[syslog receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/syslogreceiver#syslog-receiver)
[tcplog receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/tcplogreceiver#tcp-receiver)
[udplog receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/udplogreceiver#udp-receiver)
Part of #128
=> Add syslog tcplog and udplog receivers

CHANGELOG.md, README.md, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, versions.txt
=> Update to collector v0.34.0

CHANGELOG.md, README.md, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, versions.txt
=> Update to collector v0.35.0

pkg/collector/upgrade/v0_36_0_test.go
Created from: https://github.com/open-telemetry/opentelemetry-operator/pull/475#issuecomment-958964494
=> Fix flaky 0.36.0 upgrade test

bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, config/samples/core_v1alpha1_opentelemetrycollector.yaml, config/samples/sidecar.yaml
=> Use OTLP receiver in alm-examples in CSV

.github/workflows/publish-autoinstrumentation-java.yaml
=> Change publishing java auto-instrumentation image to GHCR

README.md
=> Change javaagent image to upstream

README.md
=> Fix typos in Readme for auto-instrumentation

tests/e2e/instrumentation-java/00-install-collector.yaml, tests/e2e/instrumentation-java/00-install-instrumentation.yaml, tests/e2e/instrumentation-java/01-assert.yaml, tests/e2e/instrumentation-java/01-install-app.yaml
=> Add e2e tests for java auto-instrumentation

pkg/collector/upgrade/v0_38_0.go, pkg/collector/upgrade/v0_38_0_test.go, pkg/collector/upgrade/versions.go
=> Add upgrade routine for 0.38.0

pkg/collector/upgrade/v0_38_0.go, pkg/collector/upgrade/v0_38_0_test.go
=> Fix flaky upgrade test by sorting flags in status message

CHANGELOG.md, Makefile, README.md, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, docs/otelcol_cr_spec.md, tests/e2e/instrumentation-java/00-install-collector.yaml, tests/e2e/smoke-pod-annotations/00-install.yaml, tests/e2e/smoke-sidecar/00-install.yaml, tests/e2e/smoke-simplest/00-install.yaml, versions.txt
=> Update collector to 0.38.0

README.md
=> Fix code block type in readme

bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, config/samples/core_v1alpha1_opentelemetrycollector.yaml, config/samples/instrumentation_v1alpha1_instrumentation.yaml, config/samples/kustomization.yaml
=> Add opentelemetry sample to CSV

apis/instrumentation/v1alpha1/instrumentation_types.go, apis/instrumentation/v1alpha1/zz_generated.deepcopy.go, bundle/manifests/opentelemetry.io_instrumentations.yaml, config/crd/bases/opentelemetry.io_instrumentations.yaml, pkg/instrumentation/javaagent.go, pkg/instrumentation/podmutator.go, pkg/instrumentation/podmutator_test.go, pkg/instrumentation/sdk.go, pkg/instrumentation/sdk_test.go, tests/e2e/instrumentation-java/01-assert.yaml
Notable changes:
* add resources to instrumentation CR
* automatically inject some k8s resources
=> Add resources to instrumentation CR

README.md, apis/instrumentation/v1alpha1/instrumentation_types.go, apis/instrumentation/v1alpha1/propagation.go, apis/instrumentation/v1alpha1/zz_generated.deepcopy.go, bundle/manifests/opentelemetry.io_instrumentations.yaml, config/crd/bases/opentelemetry.io_instrumentations.yaml, pkg/instrumentation/sdk.go, pkg/instrumentation/sdk_test.go, tests/e2e/instrumentation-java/00-install-instrumentation.yaml, tests/e2e/instrumentation-java/01-assert.yaml
=> Add propagators configuration to the Instrumentation kind

Dockerfile, Makefile, internal/version/main.go, internal/version/main_test.go, main.go, pkg/instrumentation/podmutator.go, pkg/instrumentation/podmutator_test.go
This PRs set default auto-instrumentation java image if the image is not specified in the CR. The operator does the same for OTELcol and allocator images.
=> Set default auto-instrumentation java image

apis/v1alpha1/instrumentation_types.go, apis/v1alpha1/instrumentation_webhook.go, apis/v1alpha1/instrumentation_webhook_test.go, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, config/webhook/manifests.yaml
=> Add validating webhook for Instrumentation kind

autoinstrumentation/nodejs/package.json, versions.txt
=> Upgrade nodejs auto instrumentation to 1.27.0

versions.txt
=> Use java auto-instrumentation 1.7.2 by default

apis/v1alpha1/instrumentation_types.go, apis/v1alpha1/opentelemetrycollector_types.go, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, bundle/tests/scorecard/config.yaml, config/manifests/bases/opentelemetry-operator.clusterserviceversion.yaml, config/scorecard/patches/olm.config.yaml
Updates #526 
See https://sdk.operatorframework.io/docs/testing-operators/scorecard/
=> Add scorecard resources test

pkg/collector/upgrade/v0_24_0_test.go, pkg/collector/upgrade/v0_39_0.go, pkg/collector/upgrade/v0_39_0_test.go, pkg/collector/upgrade/versions.go
=> Add 0.39.0 upgrade routine

CHANGELOG.md, README.md, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, versions.txt
Fixes: #577 
Dependent on #578
=> Update collector to 0.39.0

.github/workflows/release.yaml
=> Fix image path name for gh release

kind-1.22.yaml
=> Enabling kind version 1.22.4

CHANGELOG.md, README.md, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, versions.txt
=> Bump otel collector to 0.40.0

cmd/otel-allocator/go.mod, cmd/otel-allocator/main.go
Added a missing `pflag.Parse()`
=> [target-allocator] add missing command line parsing

bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, config/manifests/bases/opentelemetry-operator.clusterserviceversion.yaml
=> Fix container image field in CSV

internal/config/main.go, internal/config/options.go, main.go
=> Extract component dependencies to a separate function

RELEASE.md
=> Fixing links on RELEASE doc

pkg/collector/upgrade/v0_41_0.go, pkg/collector/upgrade/v0_41_0_test.go, pkg/collector/upgrade/versions.go
=> Add 0.41.0 upgrade routine

CHANGELOG.md, README.md, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, versions.txt
=> Bump otel collector to 0.41.0

pkg/collector/upgrade/v0_41_0_test.go
I'm getting lucky during PR CI :)
Fixes: #629
=> Fix flaky tests for 0.41.0 upgrade tests

Makefile
=> Make scorecard tests more reliable

.github/workflows/e2e.yaml, README.md, kind-1.23.yaml
… and removing the 1.19, 1.20 and adding 1.23
=> Update comp matrix to include Kubernetes 1.23

.github/workflows/publish-images.yaml
=> Remove publishing operator image to quay.io

CHANGELOG.md, README.md, RELEASE.md, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, versions.txt
=> Bump OTEL collector to 0.42.0

tests/e2e/instrumentation-java/00-install-instrumentation.yaml, tests/e2e/instrumentation-java/01-install-app.yaml, tests/e2e/instrumentation-nodejs/01-install-app.yaml, tests/e2e/instrumentation-python/01-install-app.yaml
=> Test file permissions for auto-instrumentations

versions.txt
=> Bump default instrumentation versions

apis/v1alpha1/instrumentation_webhook.go
=> Fix logger in instrumentation webhook

CHANGELOG.md, README.md, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, versions.txt
=> Adding release v0.45.0

.github/workflows/continuous-integration.yaml
=> Bump golangci GHA to v3

main.go
Great explanation is provided here https://issues.redhat.com/browse/TRACING-2407
=> Make operator more resiliant to etcd defrag activity

README.md
/cc @Aneurysm9 @dmitryax @jrcamp @james-bebbington @owais @mx-psi if you want to be kept as an "active approver" say something in this PR.
A separate PR will be done for maintainers.
=> Move all approvers to emeritus, remove inheritance from collector-approver

README.md
=> Move collector-maintainers with limited involvement in the operator to emeritus

.github/workflows/publish-images.yaml, .github/workflows/release.yaml
=> Fix publishing operator image on release

CHANGELOG.md, README.md, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, versions.txt
=> Release OTEL Operator 0.47.0

CHANGELOG.md, README.md, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, versions.txt
=> Release v0.48.0

pkg/collector/reconcile/opentelemetry.go
=> Fix Missing parameter on labels function

bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, config/default/manager_auth_proxy_patch.yaml
=> Bump kube-rbac-proxy image version to 0.11

CHANGELOG.md, README.md, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, versions.txt
=> Release v0.49.0

tests/e2e/instrumentation-java-multicontainer/01-assert.yaml, tests/e2e/instrumentation-java-multicontainer/02-assert.yaml, tests/e2e/instrumentation-nodejs-multicontainer/01-assert.yaml, tests/e2e/instrumentation-nodejs-multicontainer/02-assert.yaml, tests/e2e/instrumentation-python-multicontainer/01-assert.yaml, tests/e2e/instrumentation-python-multicontainer/02-assert.yaml
(simple order change on merge on main between injected attributes)  #871
=> Fix e2e tests

tests/e2e/targetallocator-features/02-assert.yaml
=> Print targetallocator logs on test failure

.gitignore, CHANGELOG.md, README.md, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, versions.txt
=> Adding Otel Operator v0.52.0

.github/workflows/e2e.yaml, .github/workflows/scorecard.yaml, kind-1.24.yaml
=> Test on Kubernetes 1.24

hack/install-kuttl.sh
=> Bump kuttl version

README.md
Unfortunately I don't have enough time to contribute to this repository at this point.
=> Remove @dmitryax from approvers

CHANGELOG.md, README.md, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, versions.txt
=> Adding Otel Operator v0.54.0

CHANGELOG.md, README.md, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, versions.txt
=> Release Otel Operator v0.55.0

versions.txt
This PR can be merged only after https://github.com/open-telemetry/opentelemetry-operator/pull/955
=> chore(nodejs): update versions.txt to 0.31.0

CHANGELOG.md, README.md, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, versions.txt
=> Release v0.60.0

CHANGELOG.md
@yuriolisa could you please review?
=> Add missing entry to 0.60.0 changelog

versions.txt
=> Bump default python image version

Makefile
=> Remove unused make target

CHANGELOG.md
=> Changelog: mention that jaeger extention and receiver need different ports

.github/workflows/e2e.yaml, Makefile, kuttl-test-upgrade.yaml, tests/e2e-upgrade/upgrade-test/01-upgrade-operator.yaml, tests/e2e-upgrade/upgrade-test/opentelemetry-operator-v0.49.0.yaml
log the operator if e2e test failed. 
add manifest to the test.
=> debug e2e upgrade test

README.md
Adding some docs for installation using helm charts, let me know what you think?
CC @TylerHelmuth @dmitryax
=> docs: add link to helm-chart

bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, config/default/manager_auth_proxy_patch.yaml
=> Make logging easier to configure

Makefile
=> Bump cert-manager to 1.10

.github/workflows/publish-autoinstrumentation-dotnet.yaml, .github/workflows/publish-autoinstrumentation-java.yaml, .github/workflows/publish-autoinstrumentation-nodejs.yaml, .github/workflows/publish-autoinstrumentation-python.yaml, .github/workflows/publish-images.yaml, .github/workflows/publish-target-allocator.yaml
=> Minimize dependabot PRs for GHA deps

.github/workflows/publish-autoinstrumentation-dotnet.yaml, .github/workflows/publish-autoinstrumentation-java.yaml, .github/workflows/publish-autoinstrumentation-nodejs.yaml, .github/workflows/publish-autoinstrumentation-python.yaml, .github/workflows/publish-images.yaml, CHANGELOG.md, README.md, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, versions.txt
Please have a look @Aneurysm9
Closes #1176
=> Prepare release 0.62.1

CHANGELOG.md, README.md
Depends on:
- https://github.com/open-telemetry/opentelemetry-operator/pull/1217
Belongs to:
- https://github.com/open-telemetry/opentelemetry-operator/issues/1176
What do you think?
cc @Aneurysm9
=> mention v0.62.1 release in changelog and readme

README.md
add @frzifus to approver section. 
belongs to https://github.com/open-telemetry/opentelemetry-operator/issues/1207#issuecomment-1308464224
=> update approver section in readme

CHANGELOG.md, README.md, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, versions.txt
=> Release - v0.64.1

kind-1.25.yaml
=> Updated Kind 1.25 version

autoinstrumentation/nodejs/package.json
PR updates NodeJS auto-instrumentation to latest available packages.
=> feat(nodejs): update nodejs autoinstrumentation

.chloggen/1333-update-python-ai-version.yaml, versions.txt
Update used Python auto-instrumentation image version to 0.36b0
=> feat(instrumentation): update python version 0.36b0

.chloggen/1334-update-nodejs-ai-version.yaml, versions.txt
Update used Nodejs auto-instrumentation image version to 0.34.0
=> feat(instrumentation): update nodejs version 0.34.0

hack/check-operator-ready.go
=> Add nicer logs to the check-operator-ready script

README.md
Signed-off-by: fengshunli <1171313930@qq.com>
=> Update README.md document Kubernetes Operator Introduction

cmd/otel-allocator/target/target.go, internal/config/main.go, pkg/collector/volumeclaim_test.go, pkg/instrumentation/upgrade/upgrade.go, pkg/naming/main.go, pkg/targetallocator/volume_test.go
Signed-off-by: fengshunli <1171313930@qq.com>
=> [chore] Comment format

README.md, RELEASE.md
This is based on the SIG discussion https://docs.google.com/document/d/1Unbs2qp_j5kp8FfL_lRH-ld7i5EOQpsq0I4djkOOSL4/edit
@jpkrohling @VineethReddy02 @yuriolisa @frzifus @jaronoff97  please review.
=> Document release managers with initial schedule

README.md
Signed-off-by: Guillaume Hérail <guillaume@herail.net>
=> docs: Fix broken link in the README

tests/e2e/smoke-sidecar-other-namespace/01-install-app.yaml, tests/e2e/smoke-sidecar/01-install-app.yaml
- update k8s registry domain
Part of https://github.com/kubernetes/k8s.io/issues/4780
=> update k8s registry domain

tests/e2e/smoke-sidecar-other-namespace/01-install-app.yaml, tests/e2e/smoke-sidecar/01-install-app.yaml
follow up of #1482 
/assign @pavolloffay
=> update echosever to use release 1.10

CHANGELOG.md, RELEASE.md
Created from https://github.com/open-telemetry/opentelemetry-operator/pull/1474#issuecomment-1434351690
=> Include component versions in the changelog

.github/workflows/continuous-integration.yaml, .github/workflows/release.yaml, Makefile, hack/install-kustomize.sh
=> Bump kustomize to 5.x

.chloggen/1516-update-HPA-behavior.yaml, pkg/collector/reconcile/horizontalpodautoscaler.go, tests/e2e/autoscale/00-install.yaml, tests/e2e/autoscale/02-install.yaml, tests/e2e/autoscale/03-verify-simplest-set-collector-hpa-metrics.yaml, tests/e2e/autoscale/cmd/verify/wait-and-validate-metrics.go
Resolves https://github.com/open-telemetry/opentelemetry-operator/issues/1516
=> [HPA] Properly update HPA behavior field

.github/workflows/continuous-integration.yaml, .github/workflows/release.yaml, hack/install-kubebuilder.sh
=> Remove unused kubebuilder

.chloggen/golang119.yaml, .github/workflows/changelog.yaml, .github/workflows/continuous-integration.yaml, .github/workflows/e2e.yaml, .github/workflows/release.yaml, .github/workflows/scorecard.yaml, Dockerfile, cmd/operator-opamp-bridge/Dockerfile, cmd/operator-opamp-bridge/go.mod, cmd/otel-allocator/Dockerfile, cmd/otel-allocator/go.mod, cmd/otel-allocator/server/bench_test.go, go.mod
Resolves #1566 
Replaces #1434
=> Use golang 1.20

.chloggen/1517-fix-service-internal-traffic-policy.yaml, pkg/collector/reconcile/service.go, pkg/collector/reconcile/service_test.go, pkg/collector/reconcile/suite_test.go
fixes: https://github.com/open-telemetry/opentelemetry-operator/issues/1401
=> set ServiceInternalTrafficPolicyLocal when using daemonset mode

.github/workflows/changelog.yaml, .github/workflows/continuous-integration.yaml, .github/workflows/e2e.yaml, .github/workflows/scorecard.yaml
=> Bump setup-go to v4 and remove explicit go cache

CHANGELOG.md, README.md, RELEASE.md, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, versions.txt
=> Prepare release v0.74.0

.github/workflows/reusable-operator-hub-release.yaml
Fixes https://github.com/k8s-operatorhub/community-operators/pull/2560#issuecomment-1490408938
=> Fix bundle path in opentelemetrybot PRs to operatorhubs

.chloggen/1681-update-nodejs-deps.yaml, autoinstrumentation/nodejs/package.json
Update `ot-js` deps to latest.
Issue: https://github.com/open-telemetry/opentelemetry-operator/issues/1682
=> chore(nodejs): update dependencies

.chloggen/1742-fix-config.yaml, pkg/collector/reconcile/config_replace.go, pkg/collector/reconcile/configmap.go, pkg/collector/reconcile/configmap_test.go, pkg/collector/testdata/http_sd_config_servicemonitor_test_ta_set.yaml
=> Fix bug where CRD with http_sd_config would fail to startup

README.md
=> Release Addendum - 0.77.0

.github/workflows/e2e.yaml, .github/workflows/scorecard.yaml
Adds a parent job to the e2e test matrix to allow the matrix to change with having to change the required tests for the repo's CI checks.
=> [chore] Add parent job that can check the matrix

.chloggen/1777-override-label.yaml, pkg/collector/daemonset.go, pkg/collector/deployment.go, pkg/collector/horizontalpodautoscaler.go, pkg/collector/labels.go, pkg/collector/labels_test.go, pkg/collector/reconcile/configmap.go, pkg/collector/reconcile/opentelemetry.go, pkg/collector/reconcile/service.go, pkg/collector/reconcile/service_test.go, pkg/collector/serviceaccount.go, pkg/collector/statefulset.go, pkg/targetallocator/deployment.go, pkg/targetallocator/labels.go, pkg/targetallocator/labels_test.go, pkg/targetallocator/serviceaccount.go
This PR fixes #1777 which prevented someone from overriding the app name label
=> Override the app label name

.chloggen/update-operator-sdk128.yaml, Makefile, bundle.Dockerfile, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, config/default/manager_auth_proxy_patch.yaml
=> Upgrade Operator-SDK v1.29.0

.chloggen/readme-updates.yaml, README.md, cmd/otel-allocator/README.md
Provide clarifications on the Target Allocator functionality.
=> Update OTel Operator readme and Target Allocator readme

pkg/featuregate/featuregate.go
=> Add version to the different feature flags

internal/manifests/collector/container.go, internal/manifests/collector/container_test.go
=> Fix getPrometheusExporterPorts incorrectly matching to prometheusremotewrite exporter (#2016)

.chloggen/chore_dockerfile-base-scratch.yaml, Dockerfile
Fixes #2011, an alternative to #2010.
=> Use scratch as the base image for operator

.github/workflows/publish-operator-bundle.yaml
Resolves https://github.com/open-telemetry/opentelemetry-operator/actions/runs/6172550151/job/16753034267 
Resolves https://github.com/open-telemetry/opentelemetry-operator/issues/2001
=> Fix publishing of bundle image to GHCR

.chloggen/add-tolerations.yaml, apis/v1alpha1/opentelemetrycollector_types.go, apis/v1alpha1/zz_generated.deepcopy.go, bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, bundle/manifests/opentelemetry.io_opentelemetrycollectors.yaml, config/crd/bases/opentelemetry.io_opentelemetrycollectors.yaml, docs/api.md, internal/manifests/targetallocator/deployment.go, internal/manifests/targetallocator/deployment_test.go
Add support for Toleration on target allocator.
Fixes https://github.com/open-telemetry/opentelemetry-operator/issues/2172
=> Add support for Tolerations on target allocator

bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, config/manifests/bases/opentelemetry-operator.clusterserviceversion.yaml
Resolves https://github.com/k8s-operatorhub/community-operators/pull/3101#issuecomment-1684187410
=> Specify Kube version in CSV

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/feature_request.yaml, .github/ISSUE_TEMPLATE/other.yaml, .github/pull_request_template.md
Add issue templates for people to make issues from
=> [chore] Add issue templates

config/manager/kustomization.yaml
Accidentally merged this, should be removed
=> [chore] Revert bad kustomization

cmd/operator-opamp-bridge/go.mod, cmd/operator-opamp-bridge/go.sum, cmd/otel-allocator/go.mod, cmd/otel-allocator/go.sum
=> Bump grpc-go to fix CVE-2023-44487

Makefile
Strip the symbol table (`-s`) and DWARF debug information (`-w`) from published binaries. This is basically standard practice - it's how collector releases are built, for example.
Note that the Go runtime will still retain enough information to annotate stack traces in panic logs.
The gains in terms of binary size are very significant:
```
78M     bin/manager_amd64_after
108M    bin/manager_amd64_before
```
```
116M   cmd/otel-allocator/bin/targetallocator_amd64_before
83M     cmd/otel-allocator/bin/targetallocator_amd64_after
```
```
36M     cmd/operator-opamp-bridge/bin/opampbridge_amd64_before
52M     cmd/operator-opamp-bridge/bin/opampbridge_amd64_after
```
=> Strip debug info from binaries

.chloggen/TA-healthcheck.yaml, cmd/otel-allocator/server/server.go, cmd/otel-allocator/server/server_test.go
Add livenessProbe endpoint for target allocator, another PR will be created for operator following this 
#2258
I wasn't sure if this should be added to the tests, but I still added a simple test just in case.
=> implement livenessProbe endpoint to target allocator

go.mod, go.sum, internal/manifests/mutate.go
Upgrade dario.cat/mergo v1.0.0
=> Upgrade dario.cat/mergo v1.0.0

CONTRIBUTING.md
=> Docs: add docker version requirement to CONTRIBUTING.md

.chloggen/bump-autoinstrumentation-version.yaml, autoinstrumentation/nodejs/package.json
Bump NodeJS dependencies
Resolves #2459 
=> Bump NodeJS dependencies

.github/workflows/publish-images.yaml
=> [chore] Fix image typo in publish workflow

.chloggen/fix_filterstrategy-default.yaml, apis/v1alpha1/opentelemetrycollector_types.go, bundle/manifests/opentelemetry.io_opentelemetrycollectors.yaml, config/crd/bases/opentelemetry.io_opentelemetrycollectors.yaml, controllers/builder_test.go, controllers/reconcile_test.go, internal/manifests/targetallocator/configmap.go, internal/manifests/targetallocator/configmap_test.go, internal/manifests/targetallocator/deployment_test.go, tests/e2e/targetallocator-features/00-install.yaml
=> [target allocator] Set the default filter strategy in the CRD

apis/v1alpha1/opentelemetrycollector_types.go
=> Document empty or nil prometheus service/pod monitors

.chloggen/optional-annotations.yaml, apis/v1alpha1/opentelemetrycollector_types.go, bundle/manifests/opentelemetry.io_opentelemetrycollectors.yaml, config/crd/bases/opentelemetry.io_opentelemetrycollectors.yaml, docs/api.md, internal/manifests/collector/annotations.go, internal/manifests/collector/annotations_test.go
Addresses this issue: https://github.com/open-telemetry/opentelemetry-operator/issues/2554#event-11560677640
https://github.com/open-telemetry/opentelemetry-operator/issues/2554#event-11560677640
make test
Added API docs for the new flag available.
=> Optional annotations

cmd/otel-allocator/watcher/promOperator_test.go, tests/e2e-autoscale/autoscale/00-install.yaml
**Description:** Fixes a flaky unit test by increasing the timeout.
**Link to tracking Issue:** n/a
**Testing:** n/a
=> Fix flaky unit test

controllers/reconcile_test.go, pkg/collector/upgrade/upgrade.go
**Description:** Adds better test coverage for the deployment update strategy feature. Makes the upgrade a debug log, it's very noisy right now.
**Link to tracking Issue:** n/a
**Testing:** unit
=> Add better test coverage, debug log

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/feature_request.yaml, .github/ISSUE_TEMPLATE/other.yaml, .github/pull_request_template.md
=> Update PR/issue templates

README.md
**Description:** Small typos found while reading the readme. Couldn't resist fixing them 😅
=> Fix small typos in Readme

apis/v1alpha1/convert.go, apis/v1beta1/opentelemetrycollector_types.go
=> Convert status object to v1beta1

apis/v1alpha1/convert.go, apis/v1alpha1/convert_test.go
The conversion webhook requires converting from old to new version and vice-versa. 
Updates #2620 
=> Add conversion from v1beta1 to v1alpha1

tests/e2e-multi-instrumentation/instrumentation-multi-multicontainer/01-assert.yaml, tests/e2e-multi-instrumentation/instrumentation-multi-multicontainer/01-install-app.yaml, tests/e2e-multi-instrumentation/instrumentation-multi-multicontainer/chainsaw-test.yaml, tests/e2e-multi-instrumentation/instrumentation-multi-no-containers/01-assert.yaml, tests/e2e-multi-instrumentation/instrumentation-multi-no-containers/01-install-app.yaml, tests/e2e-multi-instrumentation/instrumentation-multi-no-containers/chainsaw-test.yaml, tests/e2e-multi-instrumentation/instrumentation-single-instr-first-container/01-assert.yaml, tests/e2e-multi-instrumentation/instrumentation-single-instr-first-container/01-install-app.yaml, tests/e2e-multi-instrumentation/instrumentation-single-instr-first-container/chainsaw-test.yaml
* Checks for the status of instrumented application pods, if the pods have failed containers, collect and display the logs for all the containers in the pod.
* Fix failing instrumented apps starting due to port conflict. Run each app on different port.
=> [Chore] Fix multi instrumentation test asserts

apis/v1alpha1/convert_test.go
=> Add test for prometheus selectors in conversion

apis/v1alpha1/convert.go, apis/v1alpha1/convert_test.go
=> Handle deprecated replicas in conversion

.chloggen/target-allocator-respect-endpointslice.yaml
=> chore(changelog): entry for #2720

controllers/suite_test.go, internal/webhook/podmutation/webhookhandler_suite_test.go, pkg/collector/upgrade/suite_test.go, pkg/instrumentation/instrumentation_suite_test.go, pkg/instrumentation/upgrade/upgrade_suite_test.go
Use utilruntime package wrap AddToScheme method
=> test: use utilruntime package wrap AddToScheme method

.chloggen/2788-fix-k8sattributes-rbac-creation.yaml, internal/manifests/collector/adapters/config_to_ports.go, internal/manifests/collector/adapters/config_to_rbac.go, internal/manifests/collector/parser/processor/processor_k8sattributes.go, internal/manifests/collector/parser/processor/processor_k8sattributes_test.go
Closes #2788.
Also, fixes some errors in the log output.
=> Fix RBAC creation resources for k8sattributes

README.md
=> readme: register defined processors in example

apis/v1beta1/collector_webhook.go, apis/v1beta1/collector_webhook_test.go, apis/v1beta1/ingress.go, controllers/builder_test.go, internal/manifests/collector/ingress.go, internal/manifests/collector/ingress_test.go
=> Remove nginx from ingress type

bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml, config/samples/core_v1alpha1_opentelemetrycollector.yaml, config/samples/exporter-with-tls.yaml, config/samples/sidecar.yaml
=> Make CSV samples v1beta1 friendly

.chloggen/fix-selector-bug.yaml, controllers/reconcile_test.go, internal/manifests/mutate.go
Fixes a very tricky bug that was caused by [this PR](https://github.com/open-telemetry/opentelemetry-operator/pull/2455) which modified the selector for the TA
- Resolves: #2873
**Testing:** added a unit test
=> Fixes internal bug for modified selector

apis/v1alpha1/convert.go
Resolves #2860 
The objective here is to catch missing types if new strategies are added to v1beta1
=> Explicitly convert TA allocation and filter strategy

autoinstrumentation/nodejs/package.json
Bumped NodeJS autoinstrumentation to 0.45.0
- Resolves: #2909
=> [autoinstrumentation] Bump NodeJS autoinstrumentation to 0.45.0 #2909

README.md
Closes https://github.com/open-telemetry/opentelemetry-operator/issues/2855
=> [chore] update readme featuregate section

apis/v1beta1/collector_webhook.go, apis/v1beta1/collector_webhook_test.go
=> [chore] fix typo on warning, improved reading of the message

controllers/common.go, controllers/opentelemetrycollector_controller.go
**Description:** Simplifies deletion logic by making it generic to the type
**Link to tracking Issue(s):** n/a
**Testing:** Unit testing
=> Make deletion logic generic

.github/workflows/reusable-operator-hub-release.yaml
=> Update maintainers in the operator hub PR

.chloggen/kind130.yaml, .github/workflows/e2e.yaml, .github/workflows/scorecard.yaml, Makefile, kind-1.30.yaml
**Description:** Support for kubernetes 1.30 version
- Resolves: #2881
=> Support for kubernetes 1.30 version

pkg/instrumentation/podmutator.go
=> Fix pod name in the webhook

cmd/otel-allocator/collector/collector_test.go
**Description:** Attempts to fix a flaky TA test
- Resolves: closes #3032 
**Testing:** this is a test
=> Fix Flaky TA test

.chloggen/make-otelcol-mode-immutable.yaml, apis/v1beta1/collector_webhook.go, apis/v1beta1/collector_webhook_test.go
=> make OpenTelemetryCollector spec.mode immutable

.github/workflows/reusable-operator-hub-release.yaml, README.md, RELEASE.md
I've renamed my account, reflecting that change wherever necessary. As far as I'm aware, this doesn't cause any issues with group membership or access, please let me know if I missed anything.
=> [chore] Rename @swiatekm-sumo to @swiatekm

autoinstrumentation/nodejs/package.json
Updating NodeJS Instrumentation to v0.48.0: https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/auto-instrumentations-node-v0.48.0
=> [autoinstrumentation/nodejs] Update to v0.48.0

tests/test-e2e-apps/bridge-server/opampsrv/opampsrv.go
=> Bind to proper addr

RELEASE.md
I will be OOO for the next week so swapping the release with @yuriolisa
=> Move pavolloffay as release manager to 0.106.0

tests/e2e-autoscale/autoscale/01-install.yaml, tests/e2e-instrumentation/instrumentation-dotnet-musl/00-install-collector.yaml, tests/e2e-instrumentation/instrumentation-nginx-contnr-secctx/00-install-collector.yaml, tests/e2e-instrumentation/instrumentation-nginx-multicontainer/00-install-collector.yaml, tests/e2e-instrumentation/instrumentation-nginx/00-install-collector.yaml, tests/e2e-multi-instrumentation/instrumentation-multi-multicontainer/00-install-collector.yaml, tests/e2e-multi-instrumentation/instrumentation-multi-no-containers/00-install-collector.yaml, tests/e2e-multi-instrumentation/instrumentation-single-instr-first-container/00-install-collector.yaml, tests/e2e-opampbridge/opampbridge/01-assert.yaml, tests/e2e-opampbridge/opampbridge/01-install.yaml, tests/e2e-pdb/pdb/00-install.yaml, tests/e2e-pdb/target-allocator/00-install.yaml, tests/e2e/smoke-dns-config/00-install.yaml
**Description:** Replaces logging with debug everywhere
=> replace logging with debug in all tests

tests/e2e-openshift/monitoring/01-assert.yaml
*Fix the monitoring test case.
=> [Chore] Fix monitoring test case.

README.md
=> link to offical docs page

.chloggen/operator31.yaml, .github/workflows/e2e.yaml, .github/workflows/scorecard.yaml, Makefile, kind-1.31.yaml
**Description:** Support for kubernetes 1.31 version
=> Support for kubernetes 1.31 version

.chloggen/bug-fix-hpa.yaml, tests/e2e-autoscale/autoscale/00-assert.yaml, tests/e2e-autoscale/autoscale/00-install.yaml, tests/e2e-autoscale/autoscale/01-assert.yaml, tests/e2e-autoscale/autoscale/01-install.yaml
**Description:** adds a test to confirm memory utilization propagates effectively
- Resolves: #3283
**Testing:** adds a test
=> update tests for memory utilization coverage

README.md
Description: Fix a mistake in README.md, replace "pod" with "container"
=> Fix a tiny mistake in README.md

internal/components/component.go
=> internal/components: remove unused type

README.md
Changing myself to an emeritus TA maintainer 🥲
=> Become emeritus TA maintainer

pkg/collector/upgrade/v0_110_0_test.go
Seems this test got somehow lost..
=> upgrade: add test for version 0.110.0

.github/CODEOWNERS, README.md
=> Remove TA maintainers code ownership

autoinstrumentation/nodejs/package.json
updates the nodejs auto-instrumentation to the latest versions
=> [autoinstrumentation/nodejs] Update to v0.52.0

.github/workflows/publish-autoinstrumentation-nodejs.yaml, autoinstrumentation/nodejs/package.json
Updates https://github.com/open-telemetry/opentelemetry-operator/issues/3465 
=> Cleanup nodejs dependencies

.chloggen/revert-3379-otel-configmap.yaml
=> chlog added

CHANGELOG.md
updates the chlog which was preventing the draft release from being created.
=> [chore] update chlog

README.md
Fix some documentation about instrumentation
=> fix(doc): instrumentation documentation

.chloggen/fix-allocator-metric.yaml, cmd/otel-allocator/allocation/strategy.go
=> Fix: opentelemetry_allocator_targets_remaining should be a gauge

go.mod
Unifies `indirect` require dependencies. nits.
=> fix(deps): unifies indirect require dependencies

README.md
The attribute is `deployment.environment.name`, not `deployment`. See https://opentelemetry.io/docs/specs/semconv/attributes-registry/deployment/
N/A
This is a documentation PR
=> Update README.md - use `deployment.environment.name`, not `deployment`

.chloggen/add-python-instr-aiokafka-click.yaml, autoinstrumentation/python/requirements.txt
Adds new Python instrumentors for aiokafka, click:
* https://pypi.org/project/opentelemetry-instrumentation-aiokafka/#history
* https://pypi.org/project/opentelemetry-instrumentation-click/#history
- Resolves: https://github.com/open-telemetry/opentelemetry-operator/issues/3611
`docker build` finishes without error.
=> Add new Python instrumentors for aiokafka, click

.github/workflows/continuous-integration.yaml
Run govulncheck as part of the build.
Fixes #3646
=> [chore] Add govulncheck

README.md
Change yurioliveira's affiliation to OllyGarden.
- Resolves: #3655 
=> Change yuriolivera's affiliation to OllyGarden

pkg/featuregate/featuregate.go
=> [chore] Add from version for `operator.sidecarcontainers.native` gate

renovate.json
Broke this in #3706 by accident.
=> [chore] Fix renovate go version regex

README.md
Inspired by @bogdandrutu's PR https://github.com/open-telemetry/opentelemetry-collector/pull/8816
=> [chore] update jaronoff97 affiliation

internal/components/component.go, internal/components/component_test.go
=> [chore] remove unused func GetPortsForConfig

docs/rfcs/template.md
Fix a copy/pasta comment and offer a bit more detail on goal setting.
=> [chore] offer some changes to RFC template

.chloggen/remove-label-flag.yaml, main.go
Label flag has been deprecated, we can remove it.
- Resolves: #3236 
=> chore: Remove deprecated label flag

cmd/otel-allocator/internal/target/discovery.go
ScratchBuilder is intended exactly for this use case - building labels from scratch. This results in the following performance improvement:
```
goos: linux
goarch: amd64
pkg: github.com/open-telemetry/opentelemetry-operator/cmd/otel-allocator
cpu: AMD Ryzen 9 7950X3D 16-Core Processor          
│ bench_main.txt │          bench_branch2.txt           │
│     sec/op     │    sec/op     vs base                │
ProcessTargets/least-weighted/1000-32                           1069.7µ ±  6%   638.4µ ±  8%  -40.32% (p=0.000 n=10)
ProcessTargets/consistent-hashing/1000-32                       1040.9µ ±  6%   666.9µ ± 11%  -35.92% (p=0.000 n=10)
ProcessTargets/per-node/1000-32                                 1061.3µ ± 13%   655.9µ ±  7%  -38.21% (p=0.000 n=10) …
```
=> [target allocator] Use ScratchBuilder for building targets

README.md, docs/compatibility.md
Fixes a few spelling and grammatical errors. 
**Link to tracking Issue(s):** None
**Testing:** None
**Documentation:** Fixed spelling and grammatical errors.
=> Fix a few typos.

autoinstrumentation/dotnet/Dockerfile, autoinstrumentation/java/Dockerfile, autoinstrumentation/nodejs/Dockerfile, autoinstrumentation/php/Dockerfile, autoinstrumentation/python/Dockerfile
Fixes a typo
**Link to tracking Issue(s):** None
**Testing:** None
**Documentation:** Fixes a typo
=> [chore] s/availabe/available/

.chloggen/3913.yaml, apis/v1beta1/config.go, apis/v1beta1/config_test.go
=> Preserve telemetry config fields in default webhook

internal/config/tls.go, internal/config/tls_test.go, main.go
=> [chore]move tlsConfig out to the config package, outside of main.go

tests/test-e2e-apps/dotnet/DiceRoller/DiceRoller.csproj, tests/test-e2e-apps/dotnet/DiceRoller/Program.cs, tests/test-e2e-apps/dotnet/Dockerfile
The PR updates the Dotnet test app with DiceRoller app for generating telemetry data.
=> [Chore] Update Dotnet test app to generate telemetry data.

tests/e2e-instrumentation/instrumentation-dotnet-multicontainer/00-install-collector.yaml, tests/e2e-instrumentation/instrumentation-dotnet-multicontainer/00-install-instrumentation.yaml, tests/e2e-instrumentation/instrumentation-dotnet-multicontainer/01-assert.yaml, tests/e2e-instrumentation/instrumentation-dotnet-multicontainer/01-install-app.yaml, tests/e2e-instrumentation/instrumentation-dotnet-multicontainer/02-assert.yaml, tests/e2e-instrumentation/instrumentation-dotnet-multicontainer/02-install-app.yaml, tests/e2e-instrumentation/instrumentation-dotnet-multicontainer/chainsaw-test.yaml, tests/e2e-instrumentation/instrumentation-dotnet-musl/00-install-collector.yaml, tests/e2e-instrumentation/instrumentation-dotnet-musl/00-install-instrumentation.yaml, tests/e2e-instrumentation/instrumentation-dotnet-musl/01-assert.yaml, tests/e2e-instrumentation/instrumentation-dotnet-musl/01-install-app.yaml, tests/e2e-instrumentation/instrumentation-dotnet/00-install-collector.yaml, tests/e2e-instrumentation/instrumentation-dotnet/00-install-instrumentation.yaml, tests/e2e-instrumentation/instrumentation-dotnet/01-assert.yaml, tests/e2e-instrumentation/instrumentation-dotnet/01-install-app.yaml, tests/e2e-instrumentation/instrumentation-dotnet/chainsaw-test.yaml
The PR updates the Dotnet instrumentation tests to assert the telemetry data. To be retested and merged after PR https://github.com/open-telemetry/opentelemetry-operator/pull/3946 is merged.
=> [Chore] Update Dotnet instrumentation tests to assert telemetry data

tests/e2e-instrumentation/instrumentation-apache-httpd/00-install-collector.yaml, tests/e2e-instrumentation/instrumentation-apache-httpd/00-install-instrumentation.yaml, tests/e2e-instrumentation/instrumentation-apache-httpd/01-assert.yaml, tests/e2e-instrumentation/instrumentation-apache-httpd/01-install-app.yaml, tests/e2e-instrumentation/instrumentation-apache-httpd/chainsaw-test.yaml, tests/e2e-instrumentation/instrumentation-apache-multicontainer/00-install-collector.yaml, tests/e2e-instrumentation/instrumentation-apache-multicontainer/00-install-instrumentation.yaml, tests/e2e-instrumentation/instrumentation-apache-multicontainer/01-assert.yaml, tests/e2e-instrumentation/instrumentation-apache-multicontainer/01-install-app.yaml, tests/e2e-instrumentation/instrumentation-apache-multicontainer/02-assert.yaml, tests/e2e-instrumentation/instrumentation-apache-multicontainer/02-install-app.yaml, tests/e2e-instrumentation/instrumentation-apache-multicontainer/chainsaw-test.yaml, tests/e2e-instrumentation/instrumentation-nginx-contnr-secctx/00-install-collector.yaml, tests/e2e-instrumentation/instrumentation-nginx-contnr-secctx/00-install-instrumentation.yaml, tests/e2e-instrumentation/instrumentation-nginx-contnr-secctx/01-assert.yaml, tests/e2e-instrumentation/instrumentation-nginx-contnr-secctx/01-install-app.yaml, tests/e2e-instrumentation/instrumentation-nginx-contnr-secctx/chainsaw-test.yaml, tests/e2e-instrumentation/instrumentation-nginx-multicontainer/00-install-collector.yaml, tests/e2e-instrumentation/instrumentation-nginx-multicontainer/00-install-instrumentation.yaml, tests/e2e-instrumentation/instrumentation-nginx-multicontainer/01-assert.yaml, tests/e2e-instrumentation/instrumentation-nginx-multicontainer/01-install-app.yaml, tests/e2e-instrumentation/instrumentation-nginx-multicontainer/02-assert.yaml, tests/e2e-instrumentation/instrumentation-nginx-multicontainer/02-install-app.yaml, tests/e2e-instrumentation/instrumentation-nginx-multicontainer/chainsaw-test.yaml, tests/e2e-instrumentation/instrumentation-nginx/00-install-collector.yaml, tests/e2e-instrumentation/instrumentation-nginx/00-install-instrumentation.yaml, tests/e2e-instrumentation/instrumentation-nginx/01-assert.yaml, tests/e2e-instrumentation/instrumentation-nginx/01-install-app.yaml, tests/e2e-instrumentation/instrumentation-nginx/chainsaw-test.yaml
The PR updates the Nginx and Apache instrumentation tests to assert telemetry data.
=> [Chore] Update Apache and Nginx instrumentation tests to assert telemetry data

tests/e2e-instrumentation/instrumentation-apache-httpd/chainsaw-test.yaml, tests/e2e-instrumentation/instrumentation-apache-multicontainer/chainsaw-test.yaml, tests/e2e-instrumentation/instrumentation-nginx-contnr-secctx/chainsaw-test.yaml, tests/e2e-instrumentation/instrumentation-nginx-multicontainer/chainsaw-test.yaml, tests/e2e-instrumentation/instrumentation-nginx/chainsaw-test.yaml, tests/e2e/smoke-daemonset/00-assert.yaml
The PR fixes the assert for smoke-daemonset test when running on Kubernetes cluster with more than 1 worker nodes and some other minor fixes.
=> [Chore] Fix smoke-daemonset test assert

.chloggen/ocpdashboards.yaml, internal/openshift/dashboards/dashboards.go, internal/openshift/dashboards/metrics-dashboard.json
https://github.com/open-telemetry/opentelemetry-collector/issues/12458
https://opentelemetry.io/docs/collector/internal-telemetry/
=> Fix OpenShift dashboard metrics for collector 0.123.0

.chloggen/bug-fix-3996.yaml, .chloggen/fix-3872.yaml, cmd/otel-allocator/internal/config/config.go, cmd/otel-allocator/internal/config/config_test.go, cmd/otel-allocator/internal/config/testdata/global_config_test.yaml, cmd/otel-allocator/internal/watcher/promOperator.go, cmd/otel-allocator/internal/watcher/promOperator_test.go
- Resolves: #3996 
- Resolves: #3872 
=> Remove overwrite of global config SraperProtocols

.chloggen/otecol-spec-replicas-default.yaml, apis/v1alpha1/opentelemetrycollector_types.go, apis/v1beta1/common.go, bundle/community/manifests/opentelemetry-operator.clusterserviceversion.yaml, bundle/community/manifests/opentelemetry.io_opentelemetrycollectors.yaml, bundle/community/manifests/opentelemetry.io_targetallocators.yaml, bundle/openshift/manifests/opentelemetry-operator.clusterserviceversion.yaml, bundle/openshift/manifests/opentelemetry.io_opentelemetrycollectors.yaml, bundle/openshift/manifests/opentelemetry.io_targetallocators.yaml, config/crd/bases/opentelemetry.io_opentelemetrycollectors.yaml, config/crd/bases/opentelemetry.io_targetallocators.yaml, docs/api/opentelemetrycollectors.md, docs/api/targetallocators.md
=> Set default value for spec.replicas to 1 in otelcol crd

internal/autodetect/main.go, internal/autodetect/main_test.go, internal/config/config.go, internal/config/config_test.go, internal/config/options.go, internal/controllers/opampbridge_controller_test.go, internal/controllers/suite_test.go, main.go
To be merged after #4046 
This change recreates #3958
=> Invert autodetect

.chloggen/fix-ocp-finalizers.yaml, bundle/community/manifests/opentelemetry-operator.clusterserviceversion.yaml, bundle/openshift/manifests/opentelemetry-operator.clusterserviceversion.yaml, config/rbac/role.yaml, internal/controllers/opentelemetrycollector_controller.go
=> Fix RBAC for managing finalizers on OCP

.chloggen/operator33.yaml, .github/workflows/e2e.yaml, .github/workflows/scorecard.yaml, Makefile, kind-1.33.yaml
**Description:**  support for Kubernetes 1.33
=> Add support for Kubernetes 1.33

.chloggen/issue_4071.yaml, apis/v1beta1/common.go, bundle/community/manifests/opentelemetry-operator.clusterserviceversion.yaml, bundle/community/manifests/opentelemetry.io_opentelemetrycollectors.yaml, bundle/community/manifests/opentelemetry.io_targetallocators.yaml, bundle/openshift/manifests/opentelemetry-operator.clusterserviceversion.yaml, bundle/openshift/manifests/opentelemetry.io_opentelemetrycollectors.yaml, bundle/openshift/manifests/opentelemetry.io_targetallocators.yaml, config/crd/bases/opentelemetry.io_opentelemetrycollectors.yaml, config/crd/bases/opentelemetry.io_targetallocators.yaml, docs/api/opentelemetrycollectors.md, docs/api/targetallocators.md
Remove required annotation since default is present.
- Resolves: #4071
**Testing:**
```
make test
```
=> remove required annotation from spec.managementState

cmd/otel-allocator/README.md
Add configuration to TA README 
Fixes #3665
=> [chore] document collector_namespace

.chloggen/enable_webhooks.yaml, internal/config/cli.go, internal/config/config.go, internal/config/config_test.go, internal/config/env.go, internal/config/testdata/config.yaml, main.go
Turn the undocumented ENABLE_WEBHOOKS env var into part of configuration so it is exposed just like any other setting.
=> Enable webhooks

tests/e2e-targetallocator/targetallocator-metrics/chainsaw-test.yaml
Added e2e tests for collector metrics
- Resolves: #4064
Added e2e tests for collector metrics
=> [chore] Added e2e tests for collector metrics

.chloggen/add_trimpath.yaml, Makefile
add -trimpath when building binaries
- Resolves: #4078
=> Add -trimpath when building go binaries

README.md
This PR offers that I take additional responsibilities for this project as approver.
=> [chore] add atoulme as approver

.github/workflows/release.yaml
=> Add write permission for release GHA

versions.txt
=> Re-trigger 0.131.0 release

.chloggen/fix-hpa-cause-restarts.yaml, internal/manifests/collector/deployment.go, internal/manifests/collector/deployment_test.go, internal/manifests/collector/statefulset.go, internal/manifests/manifestutils/replicas.go
Fix a Deployment restart issue caused when the HPA settings changed, the webhook would modify spec.replicas.
- Resolves: #2585 
=> Fix deployments restarts issue

.github/workflows/continuous-integration.yaml
Ignore Govulncheck failure until the following issue is resolved:
- https://github.com/golang/vulndb/issues/3860
=> set govulncheck to permissive mode

tests/e2e-instrumentation/instrumentation-python/01-assert.yaml, tests/e2e-instrumentation/instrumentation-python/check-telemetry-data.yaml, tests/e2e/operator-restart/00-assert-operator-network-policy.yaml
Use the operator namespace instead of the hard coded value in the assert and fix instrumenation-python test assert.
=> [Chore] Fix operator-restart and instrumenation-python tests

tests/e2e-multi-instrumentation/instrumentation-multi-multicontainer-go/00-install-collector.yaml, tests/e2e-multi-instrumentation/instrumentation-multi-multicontainer-go/00-install-instrumentation.yaml, tests/e2e-multi-instrumentation/instrumentation-multi-multicontainer-go/02-assert.yaml, tests/e2e-multi-instrumentation/instrumentation-multi-multicontainer-go/chainsaw-test.yaml, tests/e2e-multi-instrumentation/instrumentation-multi-multicontainer/00-install-collector.yaml, tests/e2e-multi-instrumentation/instrumentation-multi-multicontainer/00-install-instrumentation.yaml, tests/e2e-multi-instrumentation/instrumentation-multi-multicontainer/01-assert.yaml, tests/e2e-multi-instrumentation/instrumentation-multi-multicontainer/chainsaw-test.yaml, tests/e2e-multi-instrumentation/instrumentation-multi-no-containers/00-install-collector.yaml, tests/e2e-multi-instrumentation/instrumentation-multi-no-containers/00-install-instrumentation.yaml, tests/e2e-multi-instrumentation/instrumentation-multi-no-containers/01-assert.yaml, tests/e2e-multi-instrumentation/instrumentation-multi-no-containers/chainsaw-test.yaml, tests/e2e-multi-instrumentation/instrumentation-single-instr-first-container/00-install-collector.yaml, tests/e2e-multi-instrumentation/instrumentation-single-instr-first-container/00-install-instrumentation.yaml, tests/e2e-multi-instrumentation/instrumentation-single-instr-first-container/01-assert.yaml, tests/e2e-multi-instrumentation/instrumentation-single-instr-first-container/chainsaw-test.yaml
Similar thing https://github.com/open-telemetry/opentelemetry-operator/pull/4310#issuecomment-3224270470
cc @IshwarKanse
=> avoid sidecar usage on e2e-multi-instrumentation tests

config/manager/kustomization.yaml
I guess that accidentally slipped in: https://github.com/open-telemetry/opentelemetry-operator/commit/a0b036c7e8617f8a78cd88517455a56dec1eba42#diff-14effe9ea1a3ddb6e419e627a3501a6c42aa2dcbc76803923e9aff2438e6ee34R3
=> remove unwanted controller image kustomization

tests/e2e-openshift/must-gather/README.md, tests/e2e-openshift/must-gather/assert-install-app.yaml, tests/e2e-openshift/must-gather/assert-install-collector-gather.yaml, tests/e2e-openshift/must-gather/chainsaw-test.yaml, tests/e2e-openshift/must-gather/check_must_gather.sh, tests/e2e-openshift/must-gather/install-app.yaml, tests/e2e-openshift/must-gather/install-collector-gather.yaml, tests/e2e-openshift/must-gather/install-instrumentation.yaml
The PR fixes must-gather test.
_Assisted by Claude using Gemini API._
=> [Chore] Fix must-gather test

README.md, apis/v1beta1/config_test.go, apis/v1beta1/testdata/otelcol-demo.yaml, config/samples/exporter-with-tls.yaml, docs/crd-changelog.md
=> remove batch processor references

.chloggen/fix-service-name-mutation.yaml, internal/manifests/mutate.go, internal/manifests/mutate_test.go
=> Allow mutating statefulset serviceName and upgrade to 0.129.1

Makefile
It would be nice if we also run `golangci-lint run --fix` in the fmt target. Thanks for the review!
N/A
=> [chore] Run golangci-lint run --fix from fmt

.chloggen/fix-ports-test.yaml, tests/e2e/smoke-ports/chainsaw-test.yaml
Discovered a bug that was preventing the operator release in the helm charts https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1864
- Resolves: #4394 
=> Fix incorrect test for traffic distribution
